### ISSUE TITLE
Strip Feeder Automatic Configuration

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#100]
Use vision to automatically locate, orient and define a cut strip feeder.

**Comment by vonnieda** [comment]
Early notes:

Strip Setup
---
* All it should take is clicking on a hole.
* We can try a black/white threshold and then a white/black threshold to figure out if it's white or black tape.
* Then search nearby for the next pitch distance hole to determine orientation. Then binary search to find end of tape.
* Then we need to try to find the part, which might require some input from the user, but think about it more.

**Comment by la3pna** [comment]
How will this work on clear plastic tape like some of the larger passives
use?

2015-06-23 5:18 GMT+02:00 Jason von Nieda <notifications@github.com>:

> Early notes:
> Strip Setup
>
>    - All it should take is clicking on a hole.
>    - We can try a black/white threshold and then a white/black threshold
>    to figure out if it's white or black tape.
>    - Then search nearby for the next pitch distance hole to determine
>    orientation. Then binary search to find end of tape.
>    - Then we need to try to find the part, which might require some input
>    from the user, but think about it more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openpnp/openpnp/issues/100#issuecomment-114339479>.
>



-- 

 Please  avoid sending  me  Word  or  PowerPoint  attachments.
 See  <http://www.gnu.org/philosophy/no-word-attachments.html>
PDF is an better alternative and there are always LaTeX!

**Comment by vonnieda** [comment]
@la3pna Hadn't considered that. I suspect it will still be possible to find the holes even though the contrast will be quite limited. Just have to try.

**Comment by FlyingLotus1983** [comment]
Short-term it wouldn't work as well as white paper tape.  But long-term it should be a piece of cake.  Might require some machine learning and other CV techniques, but it can be done.  I say get it working with white paper tape first, which will help prove out the RANSAC or whatever other algorithms calculate the direction and distance.  Then we can go back later and make it work with other tape materials.

**Comment by vonnieda** [comment]
@la3pna @FlyingLotus1983 I ran across this post last night which I think answers the question pretty well: http://www.liteplacer.com/phpBB/viewtopic.php?f=11&t=7&start=10#p81

**Comment by vonnieda** [comment]
Calling this done for now. The current implementation works pretty well.
