### ISSUE TITLE
Pick Fail Detect and Discard

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#102]
We can currently detect failed picks using vacuum in the GcodeDriver. Improvements that can be made are:

- [ ] Before place make sure we still have the part and haven't lost it along the way.
- [ ] After place make sure the part is now off the tip.

Note that error handling is being improved in #280. This ticket is purely for the functionality of detecting pick errors and raising them so they can be handled.

**Comment by vonnieda** [comment]
Another useful comment from IRC is to detect both pick and place failure:
* On pick, check if we picked and if not retry
* Before place make sure we still have the part and haven't lost it along the way
* After place make sure the part is now off the tip and if it's not either discard or try to re-place

**Comment by rene-dev** [comment]
Agree on the waste location in machine options. My machine has 2 locations configurable: one for actual waste, and one for components which are marked expensive, and are manually placed back in the tray/tube.
also, in the feeders menu, there is a pick button. there should also be a place/waste button. Might be helpful while setting up feeders.

**Comment by vonnieda** [comment]
Fixed in #265. If a pick fails we now discard and replan.

**Comment by vonnieda** [comment]
This is being reopened so that we can discuss vacuum pressure sensing with regards to pick fail detection.

**Comment by vonnieda** [comment]
Vacuum detection is now implemented and allows for pick failure and place failure detection as of #373 . Still need the options discussed in the first comment.

**Comment by vonnieda** [comment]
Fixed in https://github.com/openpnp/openpnp/commit/97e5bfc54827965a24eb710fa0932c3cf46ce29f
