### ISSUE TITLE
Machine Setup Panel

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#103]
Move all of the config related tabs at the bottom of the application into a single tree based Machine Setup panel.

**Comment by vonnieda** [comment]
Initial work on converting the wizard system to the tree panel has been completed. I believe all of the current wizards are visible there now.

The primary work remaining before this can be complete is to make use of the actions interface and add dynamic actions from the property sheet holders to the action pane of the panel.

**Comment by vonnieda** [comment]
Note: We probably should leave Feeders in a tab for now since they are not really part of machine setup and are more closely related to jobs. This would shrink the tabs down to Job, Parts, Packages, Feeders, and Machine Setup.

**Comment by FlyingLotus1983** [comment]
:+1:

**Comment by vonnieda** [comment]
With the removal of the Cameras tab in 83d4a0da601db53be9fb293f1e15c4c4c1dc9e33, this is finally done!
