### ISSUE TITLE
Can c270 support multiple cameras

### ISSUE THREAD

**Issue by yunxiang521** [openpnp/openpnp#1034]
My camera only displays images. The c270 only has BGR and i420 formats. When one camera is displayed, the other will not be displayed. Only one camera can be displayed. Is it because the compression format of the camera is not correct, this phenomenon will appear.

**Comment by bergyla** [comment]
You are speaking about using 2 * C270 on one USB-Root ?

**Comment by markmaker** [comment]
I think this is answered.
