### ISSUE TITLE
Actuator error

### ISSUE THREAD

**Issue by yunxiang521** [openpnp/openpnp#1046]
Common errors in using actuators，TypeError:null has no such function "actuate" in Canera.AfterSettle.js at line number 8

/**
 * Turn on Down Camera Lights
 */
var upCamLights = machine.getActuatorByName("UpCamLights");
 var downCamLights = machine.getActuatorByName("DownCamLights");
//javax.swing.JOptionPane.showMessageDialog(null,downCamLights);
//javax.swing.JOptionPane.showMessageDialog(null,upCamLights);
downCamLights.actuate(true);

Name:UpCamLights
Script Name:Camera.AfterSettle.js

**Comment by maisonsmd** [comment]
Did you name your light actuators same as your code?

**Comment by markmaker** [comment]
Seems abandoned.
