### ISSUE TITLE
I want to pay an OpenPnP consultant to get my Liteplacer configured

### ISSUE THREAD

**Issue by Savvy97** [openpnp/openpnp#1057]
I have my Liteplacer functioning with the Liteplacer software but I need the extra functionality of OpenPnP for my complex pcb's. I have spent a great deal of time trying to get OpenPnP working on my Liteplacer.

I'm a complete novice with PMP and CNC machines. I'm having problems understanding all the drivers and configuration options with OpenPnP.

I have run out of time. I need to be assembling my boards. I can no longer be doing this learn as I go. I want to pay a person experienced with OpenPnP for my Liteplacer. This can be done via skype, zoom, or go to my PC, or any other method. It needs to be done real time and not through emails being sent back and forth.Hopefully someone will be available today, Saturday, Monday, or Tuesday. I'm in the Pacific time zone.

**Comment by doppelgrau** [comment]
Guess it can be closed, the time is way after the the requested time slot.
