### ISSUE TITLE
G21; set millimeter mode error

### ISSUE THREAD

**Issue by cx2323** [openpnp/openpnp#1058]
I haven't been able to get open pnp to connect to my machine 
![pic1](https://user-images.githubusercontent.com/71908304/94324168-8066b200-ff4d-11ea-9b8a-859a1f353f8b.jpg)
![pic2](https://user-images.githubusercontent.com/71908304/94324171-82307580-ff4d-11ea-8a32-1e06591308c2.jpg)

**Comment by bilsef** [comment]
What does the log show?

**Comment by cx2323** [comment]
set millimeter mode error

**Comment by bilsef** [comment]
Most likely it is a communication problem.  G21 is usually the first
command sent to the printer.  This is what I would like to see in the log:

[image: image.png]

In this case OpenPnP is not connected to the machine (there is no COM13),
so the write fails, the command times out, and gives the error.

If you can show your complete TRACE log there should be some clues as to
why it is not communicating.

**Comment by Savvy97** [comment]
![20201002_093308](https://user-images.githubusercontent.com/71460603/94947988-6bc97300-0493-11eb-9ffb-b4eb58657b33.jpg) will this help

**Comment by bilsef** [comment]
It looks like there is a COM3, but there is no G-code aware controller
connected to it.  What controller are you using?  Are you connected by
USB?  Are you sure COM3 is the correct port?

**Comment by Savvy97** [comment]
Thank you for responding,

We are using TinyG. We are connected by USB, and COM3 is the correct port.

**Comment by vonnieda** [comment]
TinyG may not support Gcode comments - I can't remember offhand. Try
removing the comment after the command.

Jason

**Comment by tshiao4695** [comment]
can you working for your machine now? my openpnp is also note TimeoutG21 for me.

**Comment by frasier2k** [comment]
You have to configure the driver section as described in the link below:

https://github.com/openpnp/openpnp/wiki/TinyG

**Comment by markmaker** [comment]
I believe we can consider TinyG communications issues as being solved by proper XON/XOFF and Confirmation Flow Control configuration. Both are now suggested/warned by [Issues & Solutions](https://github.com/openpnp/openpnp/wiki/Issues-and-Solutions). Merged from test into develop.
