### ISSUE TITLE
Gcode Driver With Loadable Profiles

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#106]
# Release Plan
## Release 1
- [x] Four axes
- [x] One nozzle
- [x] Camera doesn't move in Z
- [x] Definable Gcode
- [x] Variables in Gcode
- [x] Sub-Drivers
- [x] Simple Actuator support (one gcode, variables)
- [x] Home position (user will need to set it to non zero if they want it, and send gcode to make sure controller is in sync)
- [x] Solo moves for axes
## Release 2
- [x] Definable axes
  - Define axes like X, Y, Z, C1, C2.
  - Map HeadMountables to a list of Axes like:
    - N1 -> X, Y, Z, C1
    - N2 -> X, Y, Z, C2
    - CAM1 -> X, Y
  - Axes can have Transforms applied that mutate machine positions. Something like:
    - double transform(HeadMountable, double position)
  - If you map more than one device to the same axis a transform is required on that axis.
- [x] Mapping of HeadMountables to Axes
- [x] Axis transforms
## Release 3
- [x] Map HeadMountables to Sub-Drivers
- [x] Improved actuator support (gcode per name, variables)
  - **Obsolete:** [ ] Change from head-mountable-id to just id since we can actually map to any Identifable, not just HeadMountable.
- [x] Get current position on startup
- [x] Position tracking during moves
  - [x] Read position reports as they come from controller.
  - [x] Configure and send polling requests for position reports.
  - Note on Smoothie: Suggested method is G0, M400, loop ? once per second until M400 returns ok.
- **Obsolete:** [ ] Export and import configuration profile
  - **Obsolete:** [x] Export
  - **Obsolete:** [ ] Import
- [x] Configuration Wizard
  - [x] Gcode Configuration
  - [x] Axis Configuration
- [ ] Improve logging when configuration doesn't load, particularly head-mountable-id errors.

## Release 4
- [x] Add TCP option in addition to serial

## Further
- [ ] Make line ending / send terminator configurable.
- [x] Allow MOVE_TO_COMMAND to be split across drivers.
- [x] MOVE_TO_COMMAND should be sent to all sub-drivers simultaneously to avoid doing movements sequentially. Possibly all driver interface commands should do this, as well. See #554.

**Comment by vonnieda** [comment]
The first step here should be to go through each of the existing drivers and document the gcode that is currently used. This can be used to build the profiles after the code is finished.

**Comment by PeeJay** [comment]
I've made a start on this - see https://github.com/PeeJay/openpnp/blob/GcodeDriver/src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

**Comment by FlyingLotus1983** [comment]
I've got a gcode abstraction later that j started a while back. I could
share it with you if its helpful?

On Wednesday, June 24, 2015, Jason von Nieda <notifications@github.com>
wrote:

> The first step here should be to go through each of the existing drivers
> and document the gcode that is currently used. This can be used to build
> the profiles after the code is finished.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openpnp/openpnp/issues/106#issuecomment-114732672>.
>


-- 
Neil Jansen, Co-Founder
Tin Whiskers Technology, LLC
http://tinwhiskers.io

**Comment by vonnieda** [comment]
@PeeJay Looks pretty good so far, although I'm not sure about the driverFirmware idea. I had thought we would just have gcode and regexes in the profile that would allow things like "Say hello to firmware" and "expected response from hello".

**Comment by PeeJay** [comment]
Just thinking about this some more - Do we really want each individual user to have their own set of Gcode in the settings file? And regexs? eek! That sounds like a pain to support. Would it be better to have a master file that comes with the openpnp distribution that has one set of settings? I guess long term users won't be looking in machine.xml anyway. Just some thoughts.

**Comment by PeeJay** [comment]
@FlyingLotus1983 Sure I'll take all the help I can get.

**Comment by FlyingLotus1983** [comment]
@PeeJay sent you the google docs link...

**Comment by vonnieda** [comment]
@PeeJay That's what I mean about "loadable profiles". Look at my original comments at the start of the issue. Basically, I see this working like all of the major 3D printing controllers do. You have a file you distribute that contains the profile for a machine. The user loads that file into their machine and done. Doesn't really matter where it's stored in the end, but having it in the machine.xml keeps it tidy and makes it easy to debug if I need to ask someone to send me their config.

The machine.xml is not really intended for users to edit. Over time everything is exposed in the UI. Yes, if they dig deep enough they'd be able to find the gcodes and regexes, but this is how things like Simplify3D and Cura work too. I think it's fine.

**Comment by PeeJay** [comment]
@vonnieda Ahh I get it now. So if a profile potentially got corrupted we just tell the user to reload profile X and don't mess with it. I'll keep working on it.

@FlyingLotus1983 Thanks for that. FYI it's quite similar to the list at http://reprap.org/wiki/G-code .

**Comment by vonnieda** [comment]
@PeeJay Yep, exactly! The key is that it's a separate file from the machine.xml and that it can be loaded in. That way if you DO need to reload it, or maybe there is a firmware update that requires changes, you don't have to overwrite your entire config containing all your settings, parameters, feeders, etc. You just load in the machine profile file which overwrites the gcode settings.

**Comment by vonnieda** [comment]
Also see #121

**Comment by vonnieda** [comment]
First version of three has been released. Information at https://github.com/openpnp/openpnp/wiki/GcodeDriver

**Comment by vonnieda** [comment]
Also see #273

**Comment by vonnieda** [comment]
Release 2 has been completed. More information at https://github.com/openpnp/openpnp/wiki/GcodeDriver#mapping-axes-to-headmountables

**Comment by mfarahaniasl** [comment]
HI. How can i find GcodeDriver PCB project or buy one of them?

**Comment by vonnieda** [comment]
@mfarahaniasl GcodeDriver is a software driver for connecting OpenPnP with any type of Gcode based controller board. There is no GcodeDriver PCB. I recommend the Smoothieboard for a controller: http://smoothieware.org/getting-smoothieboard

**Comment by mfarahaniasl** [comment]
Thank for your replay. There are any openSource Driver board that can work with OpenPnP project too?

**Comment by vonnieda** [comment]
@mfarahaniasl Yes, the SmoothieBoard I mentioned is completely open source. Hardware and firmware. You can also use TinyG which is open source.

**Comment by PeeJay** [comment]
I'm looking at adding tcp support to the gcode driver, but need a bit of guidance. I'm using @anthonywebb 's tcp driver at https://github.com/anthonywebb/openpnp, which replaces the AbstractSerialPortDriver class with a tcp version. The part I'm unsure of is how to use both classes. 
Normally in C++ I would just instantiate either the serial or tcp class as needed from within the gcodeDriver class, but to do that I would need to make them a full class rather than abstract, and the GcodeDriver would not inherit them any more. Am I going in the right direction here? Java is all a bit new to me.

**Comment by vonnieda** [comment]
Yep, my thought on how this would work is that we would have a base
GcodePort class and there would be GcodeSerialPort subclass and
GcodeTcpPort subclass. GcodeDriver would just have an instance of one of
these depending on how it’s configured, or, to make it easier, just have
instances of both and activate the one that’s configured.

**Comment by vonnieda** [comment]
For anyone still following along, we now have TCP/IP support thanks to @PeeJay in PR #749. Thanks @PeeJay!

**Comment by markmaker** [comment]
I think most of this is covered by Advanced Motion Control and Issues & Solutions smart G-code generation, or made obsolete (it does not make much sense to export/import profiles, if you can generate them automatically).

**Comment by vonnieda** [comment]
> I think most of this is covered by Advanced Motion Control and Issues & Solutions smart G-code generation, or made obsolete (it does not make much sense to export/import profiles, if you can generate them automatically).

Agreed - thanks. Closing this.
