### ISSUE TITLE
multiple feeders for the same part

### ISSUE THREAD

**Issue by 337529542** [openpnp/openpnp#1070]
I set up two strip feeders for the same part . when the first feeder runs out , openpnp alert some error msg , it does not use the second feeder automatically .

**Comment by vonnieda** [comment]
This has been fixed in https://github.com/openpnp/openpnp/commit/c7f0a313e0434e026ca5c9568b232d01eb000dd4. It is currently available to test in the test branch at https://openpnp.org/test-downloads/.
