### ISSUE TITLE
Solder Paste Why can't functions be used

### ISSUE THREAD

**Issue by lei111** [openpnp/openpnp#1096]
# Read This First
To submit an issue for OpenPnP you must use this template or it will be deleted. Please fill out either the Problem Report or Feature Request section below and delete the other section.

-----------------------------------------------------------------------

# Problem Report
## Describe the Issue
Solder Paste Why can't functions be used.

## Steps to Reproduce
1. I replaced the XML file according to the instructions and the program couldn't start

## Expected Result
What did you expect to happen? Be descriptive.

## Actual Result

Can start and appear Solder Paste
## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
The more information you can provide about the issue the more likely it is that a developer will be able to respond.

Whenever possible, please use the Menu -> Help -> Submit Diagnostics feature and include the URL here. Submit Diagnostics makes it easy to include log files, screen capture, debug images, configuration files, etc.

-----------------------------------------------------------------------

# Feature Request
## Describe the Feature
What do you want it to do? Be as descriptive as possible.

## How Will It Look?
If the feature will include changes to the user interface, how would they look? Include drawings or mockups if possible.

## Why Do We Need It?
1. What problem does it solve?
2. Is it useful for everyone, or does it only solve a problem for your machine?

## Provide Examples
Is this something that exists in other pick and place software? Provide examples and references if possible.

**Comment by vonnieda** [comment]
The paste dispense functionality was removed in OpenPnP 2.0: https://github.com/openpnp/openpnp/blob/develop/CHANGES.md#2019-05-27
