### ISSUE TITLE
"Write Error" when trying to power on

### ISSUE THREAD

**Issue by Savvy97** [openpnp/openpnp#1100]
(01/06/21)
For a few months now I have been able to connect OpenPnP to the Smoothie board with the Gcode driver. Last week I started getting this message when I click the power button, "Write Error" as shown in the image attached.
![write error](https://user-images.githubusercontent.com/71460603/103803535-8caae280-5005-11eb-8797-c4a656af603f.png)

I ordered a new Smoothie bard and got the same result.
I tried several different drivers with both the new and old boards getting these results for both:
Gcodedriver – Write error
LinuxCNCdriver – Connection refused: connect
OpenBuildsdriver – Write Error
NeoDen4driver – Write Error, but it connects enough for the power button to turn from green to red along with the other controls lighting up. It still says Write Error when trying to use any of the controls.
I tried another comuter that also used to connect OpenPnP to the smoothie board and I got the message "Timeout waiting for response to G21 ; Set millimeters mode"
I have tried all my USB ports with these processes as well. 

I expect to be able to power on in OpenPnp but in that moment last week I stopped being able to.

**Comment by vonnieda** [comment]
This is being addressed on the mailing list.
