### ISSUE TITLE
smoothie firmware can not be read

### ISSUE THREAD

**Issue by cx2323** [openpnp/openpnp#1117]
it will connect to the smoothie board but can not detect the firmware on the smoothie.
is there anyway to update firmware?
im on windows 7 with open pnp 2.

**Comment by markmaker** [comment]
Hi cx,

See here:

https://makr.zone/smoothieware-new-firmware-for-pnp/500/ 
<https://makr.zone/smoothieware-new-firmware-for-pnp/500/>

And more generally here:

https://github.com/openpnp/openpnp/wiki/Motion-Controller-Firmwares 
<https://github.com/openpnp/openpnp/wiki/Motion-Controller-Firmwares>

And be sure to use this:

https://github.com/openpnp/openpnp/wiki/Issues-and-Solutions 
<https://github.com/openpnp/openpnp/wiki/Issues-and-Solutions>

_Mark


Am 01.02.2021 um 23:33 schrieb cx2323:

**Comment by markmaker** [comment]
Btw. better use the user group for questions like these.

https://groups.google.com/g/openpnp

_Mark
