### ISSUE TITLE
Wiki Images

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#1118]
Do not delete.

**Comment by vonnieda** [comment]
![Screen Shot 2021-02-04 at 12 28 43 AM](https://user-images.githubusercontent.com/1182323/106854080-5605cd80-6680-11eb-9556-8cd351312214.png)

**Comment by markmaker** [comment]
Wiki images, do not delete:
___
![Nozzle tip compatibility](https://user-images.githubusercontent.com/9963310/182042739-ed3cd0de-3268-4b5e-8009-ba38215c37d2.png)
