### ISSUE TITLE
ReferenceRotatedTrayFeeder negative rotation defunct

### ISSUE THREAD

**Issue by gxurma** [openpnp/openpnp#1157]
# Problem Report
ReferenceRotatedTrayFeeder is not able to handle negative rotation of feeder tray. It always thinks it is rotated in positive direction.
ReferenceRotatedTrayFeeder is definitely able to use trays with positive rotation.

## Steps to Reproduce
1. add a new ReferenceRotatedTrayFeeder 
2. train it with the A, B, C postition.
3. adjust the row and coloumn count as needed
4. click on the "calculate offsets & tray rotation" button
Depending on the resulting rotation:
- If rotation is _positive_, everything is OK., Tray works, it goes to expected correct positions when stepping through with the "Command the selected feeder to perform a feed operation"
- if rotation is *negative*, it is moving to wrong positions when stepping through with the "Command the selected feeder to perform a feed operation". The feeder thinks it is positively rotated.

## Expected Result
Also negative rotations shall be working

## Actual Result
feeder moves tool to positively rotated position

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue

Happens also on clean fresh new install
-----------------------------------------------------------------------

**Comment by doppelgrau** [comment]
Guess it can be closed after PR #1167 ?!
