### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by jejoe16** [openpnp/openpnp#1160]
# Problem Report
I tried to install the latest version of openpnp - windows 64 bit 

## Steps to Reproduce
1) install the windows 64 version 
2) when extracting files it tries to create "Demo Board v2.TXT" however it gives error "Could not create this file. Shall I try again" 
3) if I cancel it removes all installed files.

**Comment by vonnieda** [comment]
You may need to install as admin. This sounds like a disk permissions issue.

**Comment by iovsiann** [comment]
I fixed this error by disabling the antivirus.
Running the installer with admin privileges did not help.
