### ISSUE TITLE
The latest version resets the Z axis position

### ISSUE THREAD

**Issue by bacrua** [openpnp/openpnp#1184]
The latest version resets the Z axis position. This was also observed in the version that I downloaded on 02/20/2021. But only now in the work I was able to make sure that there was an error.
1. Go to any strip feeder. Click on autosetup.
2. after the first autosetting, the storing does not change.
3. Select the second available strip feeder and click Autosetup.
4. Z axis has zeroed values.
![PNP1](https://user-images.githubusercontent.com/48532007/116163332-3969b680-a700-11eb-8b99-3f89db3d015f.png)
![PNP2](https://user-images.githubusercontent.com/48532007/116163333-3a9ae380-a700-11eb-8186-c92dea12f0a8.png)

**Comment by doppelgrau** [comment]
Not sure if that's intended behavior.
If not a fix would be quite simple, in the Wizzard lines 600ff just keep the old height instead setting it to zero.

`                                 final Location referenceHole1 = referenceHoles.get(0)
                                                                               .derive(null, null,
                                                                                       null, 0d);
                                 final Location referenceHole2 = referenceHoles.get(1)
                                                                               .derive(null, null,
                                                                                       null, 0d);
`

**Comment by markmaker** [comment]
Yep.

```
diff --git a/src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java b/src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
index df574b7e84..5ea7996df0 100644
--- a/src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
+++ b/src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
@@ -599,11 +599,15 @@ public class ReferenceStripFeederConfigurationWizard extends AbstractConfigurati
                                          firstPartLocation, secondPartLocation,
                                          part1HoleLocations, part2HoleLocations);
                                  final Location referenceHole1 = referenceHoles.get(0)
-                                                                               .derive(null, null,
-                                                                                       null, 0d);
+                                         .derive(null, null,
+                                                 null, 0d)
+                                         .derive(feeder.getReferenceHoleLocation(), 
+                                                 false,  false,  true, false);
                                  final Location referenceHole2 = referenceHoles.get(1)
-                                                                               .derive(null, null,
-                                                                                       null, 0d);
+                                         .derive(null, null,
+                                                 null, 0d)
+                                         .derive(feeder.getLastHoleLocation(), 
+                                                 false,  false,  true, false);
 
                                  feeder.setReferenceHoleLocation(referenceHole1);
                                  feeder.setLastHoleLocation(referenceHole2);

```

I traced this back to 2015 i.e. the very beginning. Are you sure, @bacrua this ever worked? 

_Mark

**Comment by markmaker** [comment]
Found the real reason and fixed it. See #1186.
