### ISSUE TITLE
Bug Report: Placement set to ignore causes machine / job to stop.

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#119]
User reports that with a placement set to ignore the machine stops. Have not verified, need to check.

**Comment by vonnieda** [comment]
Originally filed by @la3pna. I suspect that this is actually related to #120 and the fact that job pause on planner error is not working very well. Can you see if you can still reproduce this if you resolve #120 by setting your part count to 0?

**Comment by la3pna** [comment]
Yes, this is resolved if there are more parts available than used on board.

**Comment by vonnieda** [comment]
Confirmed that this is a duplicate of #120.
