### ISSUE TITLE
MarlinDriver: Multiple Gcodes in a Single Command

### ISSUE THREAD

**Issue by la3pna** [openpnp/openpnp#121]
When sending more than 1 single gcode in each command, the program don't handle the extra "ok" from the marlin driver. 

Could this be added into the function? 
 <enable-gcode>M17 (/n/r) M42 P7 S255 </enable-gcode>

**Comment by vonnieda** [comment]
Suggest switching to the new GcodeDriver https://github.com/openpnp/openpnp/wiki/GcodeDriver which includes this functionality. The MarlinDriver will soon be deprecated in favor of the GcodeDriver.
