### ISSUE TITLE
MacOSX Highlighted Tab Issue

### ISSUE THREAD

**Issue by Shaische** [openpnp/openpnp#1305]
# Problem Report
## Describe the Issue
On Mac OSX, when the tab is selected, it's not properly highlighted. The text is whited out. This happens both on iMac MacOS Big Sur 11.5.2 and MacBook Pro Big Sur.

## Steps to Reproduce
Use OpenPNP on any system running macOS Big Sur

## Expected Result
Text to be black instead of white.

## Actual Result
Text is White.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
<img width="604" alt="screenshot_1690" src="https://user-images.githubusercontent.com/2673147/136239301-9d33a3c8-3e62-4892-8a77-9df5c1f03c46.png">
<img width="374" alt="screenshot_1689" src="https://user-images.githubusercontent.com/2673147/136239304-08daea9e-955d-46ea-8235-6b5dba0eb7ff.png">

**Comment by markmaker** [comment]
See the [workaround](https://github.com/openpnp/openpnp/issues/1199#issuecomment-918392848). Merged into develop in #1322. I assume this solves it too, otherwise please reopen.

_Mark
