### ISSUE TITLE
Issues and solution tab appears twice on MacOSX

### ISSUE THREAD

**Issue by Shaische** [openpnp/openpnp#1306]
# Problem Report
## Describe the Issue
Mac OS Big Sur 11.2.2 with a fresh install of OpenPNP and fresh install of Machine.XML has tab issue where issues/solution tab appears twice. But clicking the last tab is still pointing to the log window as it should. Just the tab is not right. Sometimes when starting up OpenPNP this doesn't happen, but sometimes it does. It's random. This happened on a previous install and still happens with a fresh install. Not sure if this is related to https://github.com/openpnp/openpnp/issues/1305

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
1. Start OpenPnP on a Mac.

## Expected Result
Should have Log tab.

## Actual Result
Shows Issues/Solution tab twice.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
<img width="764" alt="screenshot_403" src="https://user-images.githubusercontent.com/2673147/136307749-f0bb3c7d-f6b2-4b46-a197-ff2886659e35.png">

**Comment by Shaische** [comment]
Just noticed this is happening when you also click the button "Find Issues/Solutions

<img width="253" alt="screenshot_404" src="https://user-images.githubusercontent.com/2673147/136308512-24ee6cc0-cb2e-40c7-a56a-6f0e95de1ada.png">
"

**Comment by markmaker** [comment]
see here:

https://github.com/openpnp/openpnp/pull/1151#issuecomment-937507609 
<https://github.com/openpnp/openpnp/pull/1151#issuecomment-937507609>

Am 07.10.2021 um 04:00 schrieb Shai:

**Comment by Shaische** [comment]
> For a workaround see here:
> [#1199 (comment)](https://github.com/openpnp/openpnp/issues/1199#issuecomment-918392848)
> _Mark

I searched for "show-indicator" and there is no text in my machine.xml even with just indicator. Seems this workaround is outdated?

**Comment by markmaker** [comment]
`test` was merged in #1322.
