### ISSUE TITLE
Panel options window not showing OK and Cancel buttons in Linux

### ISSUE THREAD

**Issue by neliooliveira** [openpnp/openpnp#1325]
# Problem Report
## Describe the Issue

Panel options window not showing OK and Cancel buttons in Linux.
The buttons are there because I can still select them using TAB.
It's probably just the size of the window that is not high enough to fit all the elements in the Linux theme.

## Steps to Reproduce

Open the panel options in a Linux machine.

## Expected Result
Buttons to be visible

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
![Captura de ecrã de 2021-11-10 11-01-35](https://user-images.githubusercontent.com/16232608/141104420-ac81cded-f789-460e-a377-8482ef212ae9.png)

**Comment by kaklik** [comment]
The same happens to me: 

![image](https://user-images.githubusercontent.com/1194177/193769605-a06c6da5-7715-48dd-a27c-18277b127d55.png)

I should use 3x Tabulator and enter to hit the "hidden" OK button. 

I am running that version of OpenPnP
![image](https://user-images.githubusercontent.com/1194177/193770250-9f5528b5-537d-401a-b346-9ee5abccabf4.png)

on Ubuntu:

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by kaklik** [comment]
The recent version of OpenPnP has changed the Panelization Settings layout which resolved this issue. 

![image](https://user-images.githubusercontent.com/1194177/222408985-632a5dff-7bfe-4908-bdde-703b5ae5c635.png)

Therefore the issue should be closed. 

FIY @neliooliveira

**Comment by markmaker** [comment]
Thanks, @kaklik!
