### ISSUE TITLE
PnP software jogs and sends signals but no movement

### ISSUE THREAD

**Issue by Savvy97** [openpnp/openpnp#1330]
# Read This First
To submit an issue for OpenPnP you must use this template or it will be deleted. Please fill out either the Problem Report or Feature Request section below and delete the other section.

-----------------------------------------------------------------------

# Problem Report
No movement - Have tried multiple Smoothie boards.
## Describe the Issue
I have a Liteplacer PnP running OpenPNP. Monday, I had finally gotten bottom vision working well enough to see the parts and correct rotation/translation for 16/16 R0805 Resistors on a sample board. Then Tuesday we had a guy come in to start learning the machine and go through our startup guide and for some reason now the machine will not move. OpenPNP lets me jog the XYZC directional buttons, the red light comes on (the smoothieboard to indicate movement when I push a button) and the XYZC values in the bottom right change correctly, but the actual motors will not spin. I have a demo machine that is a completely different board with a completely different laptop that is having the same problems. I have been struggling with this for 72Hours trying to use old backup configurations but it still does the same thing. Occasionally I get an response timeout M114 get position error.

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
1. Start OpenPnP
2. Click the Power On button.
3. Jog the machine 10mm to the right.
4. The machine in the software will jog 10mm to the right but the actual machine does nothing.

## Expected Result
What did you expect to happen? Machine to move 10mm to the right/xmotor spin accordingly.

## Actual Result
OpenPNP reports signal being sent to smoothieboard but no actual operation is handled.

## Notes, Log Files, Screen Captures, Videos, etc. 
I changed the .xml file extensions to .txt so i could upload them. Hopefully that doesn't change the format too terrible for you. 

[config.txt](https://github.com/openpnp/openpnp/files/7567136/config.txt)
![CurrentFirmware](https://user-images.githubusercontent.com/71460603/142535306-3206d204-b826-4be5-af4d-f0d8f1832705.PNG)
.
[machine.txt](https://github.com/openpnp/openpnp/files/7567145/machine.txt)
[packages.txt](https://github.com/openpnp/openpnp/files/7567146/packages.txt)
[parts.txt](https://github.com/openpnp/openpnp/files/7567147/parts.txt)

**Comment by markmaker** [comment]
Hi @Savvy97 

Please report usage problem in the _discussion group_, not here with Github Issues. 

http://groups.google.com/group/openpnp

Github Issues are for _confirmed_ bugs or feature requests related to OpenPnP. 

When you open a discussion, please add the log. Set your logging level to TRACE on the Log tab. Then try moving around a bit, then send the full log.

https://github.com/openpnp/openpnp/wiki/FAQ#where-are-configuration-and-log-files-located

I'll close this Issue.

_Mark
