### ISSUE TITLE
Increase the usage of compound assignment operators

### ISSUE THREAD

**Issue by elfring** [openpnp/openpnp#1346]
# Feature Request
## Describe the Feature
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of compound operators](https://docs.oracle.com/javase/specs/jls/se17/html/jls-15.html#jls-15.26 "Description for assignment operators") accordingly.

## Why Do We Need It?
Adjusted software run time characteristics

## Provide Examples
Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's#\b(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-*/%^]|&(?!&)|\|(?!\|)|<<|>>>?)#$+{target} $+{operator}=#gm' $(find ~/Projekte/OpenPnP/lokal -name '*.java')
```

:crystal_ball: How will development interests evolve further also according to update candidates in 43 lines of this software?

**Comment by markmaker** [comment]
Not sure I understand this.

If it is what I think it is, then please provide a PR if you like. Anyway, I'm sure JIT will optimize these. 

_Mark

**Comment by elfring** [comment]
:crystal_ball: Can any clarification help to improve the understanding for the presented source code transformation approach?

**Comment by markmaker** [comment]
I guess. Be more verbous.

**Comment by markmaker** [comment]
I assume you are a bot, right? 🤖

What is the square root of the number of squares on a chess board?

**Comment by elfring** [comment]
I am not a “bot” (even if you present another such assumption).

The square root of 64 is 8.

**Comment by markmaker** [comment]
Ok, so please explain what this is in more words. I don't get it. Kann auch in Deutsch sein.

**Comment by elfring** [comment]
Where are the remaining understanding difficulties for the shown change possibilities?
Will they vanish by a corresponding merge request?

-----

Was sind die noch verbliebenen Verständnisschwierigkeiten für die gezeigten Änderungsmöglichkeiten?
Werden diese sich durch eine dazugehörige Integrationsanfrage auflösen?

**Comment by markmaker** [comment]
Please explain the rationale for the suggested change. What is better? What is the proof? 

And yes, making it into a Pull Request would in deed make it much more understandable. Thanks.

**Comment by markmaker** [comment]
:robot:?
