### ISSUE TITLE
Linux .deb package does not create a start menu item.

### ISSUE THREAD

**Issue by ghost** [openpnp/openpnp#136]
From Thomas:
Howdy, fwiw, it seems that the linux deb package of the binaries dont make a menu item when installing, a minor but annoying issue..

From Jason:
I have no idea how start menu items are created in Linux so if someone can provide some assistance here it would be appreciated. We build installers with Install4J and the project file is checked in, so feel free to grab it and make changes.

**Comment by vonnieda** [comment]
Original requester deleted their account and no one else seems to care about this, so closing it.
