### ISSUE TITLE
Feeder Auto Setup help

### ISSUE THREAD

**Issue by bacrua** [openpnp/openpnp#1374]
Installed the latest version.
1. select a strip feeder.
2. point the camera at the selected feeder.
3 Click on the "Auto Setup" button
Gives an error message. In version # 2021-05-03 everything works.
![error](https://user-images.githubusercontent.com/48532007/152245510-20cc9b74-9c8a-42f4-97f1-db47fb1ff917.jpg)

**Comment by markmaker** [comment]
Hi @bacrua,

Please use the discussion group for seeking support, Github Issues should only be opened once a bug (or missing feature) is confirmed: 
http://groups.google.com/group/openpnp

Also, with such errors you need to attach a log and possibly a `machine.xml`.
https://github.com/openpnp/openpnp/wiki/FAQ#where-are-configuration-and-log-files-located

If I were to guess, you are using scripts for lighting. See this:
https://groups.google.com/g/openpnp/c/nCexIP3XS-g/m/Qfhozq-pBQAJ



_Mark
