### ISSUE TITLE
[FEATURE REQUEST] Add "Vision Retry Count" setting to feeders

### ISSUE THREAD

**Issue by ma-lalonde** [openpnp/openpnp#1389]
# Feature Request
## Describe the Feature
Add a "Vision Retry Count" setting to the feeders, just like there are already "Feed Retry Count" and "Pick Retry Count" settings available on the ReferencePushPullFeeder

## How Will It Look?
Exactly like the previously mentioned settings: a label and a numbers-only text box in the feeder's configuration. This would allow OpenPnP to retry OCR or sprocket hole detection when needed.

## Why Do We Need It?
1. What problem does it solve?
Label printers (P-Touch) typically have a glossy finish. For barcode detection, this a less than ideal situation, but this is a readily available way to create labels for many people. Achieving a 100% OCR success rate in this situation is difficult, without mentioning doing it across 30+ feeders. If a "good" vision pipeline has a 90% OCR success rate, then having the option to retry part detection with OCR makes the initial feeder calibration process much easier to complete.

3. Is it useful for everyone, or does it only solve a problem for your machine?
This feature should be useful for anyone using label printers with glossy paper.

## Provide Examples
Current settings:
![image](https://user-images.githubusercontent.com/52324318/158460815-f70e46e4-dbd5-48f4-b904-555cf58441f0.png)

**Comment by markmaker** [comment]
Hi @ma-lalonde 

In my experience if have almost never seen it that simply repeating the vision operation would help. 

If you see such behavior, you should check the following:

- Good, strong, diffuse lighting: the only context where I think a camera delivers significantly unstable images is when it does not have enough consistent light, i.e. where the ambient and changing light, or even strong sensor noise is present. During a machine build/setup, this is definitely not somehing you can postpone!
- [Camera Settling](https://github.com/openpnp/openpnp/wiki/Camera-Settling): make sure your camera image is stable, even after the most "energetic" motion. 
- Fix your pipelines: If a pipeline gives intermittently successful detection results, it is _almost_ always the fault of the pipeline. I have yet to see a situation where a robust pipeline cannot be achieved. Admittedly, this is sometimes difficult (the community can help you). 
- Fix the _real_ problem: glossy print labels do definitely sound problematic. I believe this _specific_ problem was discussed in the group, right? Is this still open?

_Mark

**Comment by ma-lalonde** [comment]
Yes, we discussed this in the group and came to the conclusions you mention. I forgot to update / close this issue. Thanks for the follow-up.
