### ISSUE TITLE
Fiducial check sanity check should be configurable.

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#140]
Update: Sanity check was added but needs to be configurable. See comments below from @cri-s on suggestions.

---

Right now the fiducial check can get confused by nearby fiducials or things that look like fiducials. Since it does the two point check independently of each other it's possible to end up with a resulting board orientation that is incorrect.

Suggest:
After fiducial check is complete, check the 2D distance between the found fiducials and the placements and if it's not within a couple percent of each other abort the check or try again.

**Comment by vonnieda** [comment]
Checked in a quick mockup of this idea. Checks that the fiducials are within 1% distant of where they should be. Working well so far but won't close this until tested further.

**Comment by cri-s** [comment]
Usually error is 0.75% specified by PCB producer. IPC 2221 should be
checked and bow and twist added.
Without checking, I would allow for 1.3%  and if assembling flex PCB or
laser transfered boards for prototype this value need to be increased.
Il 27/ago/2015 06:16 "Jason von Nieda" <notifications@github.com> ha
scritto:

**Comment by vonnieda** [comment]
Based on @cri-s comments, we should probably make this a per board setting that the user can configure.

**Comment by markmaker** [comment]
This is covered by the #1179 Fiducial locator **Max. Distance** field. See "Fiducial Locator" section.
