### ISSUE TITLE
Program fails to start

### ISSUE THREAD

**Issue by FLYBYME** [openpnp/openpnp#1407]
[OpenPnP.log](https://github.com/openpnp/openpnp/files/8594612/OpenPnP.log)
# Problem Report
## Describe the Issue
I keep getting this error. I delete the folder and it makes no difference.

## Steps to Reproduce
Fresh install of windows 10 with version "2022-02-03_09-01-37.370b98b" also tried "2020-12-31_20-40-49.5524445"

## Provide Examples

![pnp-error](https://user-images.githubusercontent.com/339283/166066067-8a4ece53-00b1-4b56-9d5e-c02084ebf199.png)

**Comment by markmaker** [comment]
Can this help?
https://groups.google.com/g/openpnp/c/sW4Btj0zXU0/m/Le-_8TLeAwAJ
_Mark

**Comment by FLYBYME** [comment]
I tried install the requested file (Windows6.1-KB2670838-x64.msu) but its for windows 7 not 10

**Comment by markmaker** [comment]
Maybe ask the same question on the user group:

http://groups.google.com/group/openpnp

_Mark
