### ISSUE TITLE
OpenPNP refuses to start

### ISSUE THREAD

**Issue by Coffee0297** [openpnp/openpnp#1417]
-----------------------------------------------------------------------

# Problem Report
## Describe the Issue
OpenPNP fails to start on POP!os 21.10. 

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue

[error.log](https://github.com/openpnp/openpnp/files/8732044/error.log)

**Comment by markmaker** [comment]
Please go to the [OpenPnP discussion group](http://groups.google.com/group/openpnp) where more people can help. 

We can reopen this issue, if the problem can be better described.

_Mark
