### ISSUE TITLE
OpenPNP task does not end

### ISSUE THREAD

**Issue by robermeyer** [openpnp/openpnp#143]
Under Window 7 pressing close (upper right X) closes the GUI but the OpenPnP task keep running.
Trying to restart the program gives an internal error code of 22.
Closing the task with Task Manager is only way to end Task and allow running GUI again.
![image](https://cloud.githubusercontent.com/assets/7516894/9650277/974db9c8-51b5-11e5-82aa-088af306d3ca.png)

**Comment by vonnieda** [comment]
This is likely related to #65

**Comment by vonnieda** [comment]
Fixed #65, which I believe was the root cause of this. If it's still happening please reopen this issue.
