### ISSUE TITLE
Bug / 'Next Placement' button causing exception on missing part.

### ISSUE THREAD

**Issue by noeldum** [openpnp/openpnp#1469]
# Problem Report
## Describe the Issue
When using the 'next placement' button to a missing part in the job an error appears. It looks like this is unmanaged.
![Screenshot_2022-08-13_10-30-46](https://user-images.githubusercontent.com/1875345/184478326-7ff1997b-f316-48d6-9ddc-fbf5a29ade68.png)

## Steps to Reproduce
* Load the attached job. x.job.xml
* Move the machine to the part just before the missing part. (RD1)
* Hit the 'next placement' button.
* Enjoy the exception on the screen.

## Expected Result
Machine should probably move to the position regardless of the part being defined or not. Or maybe skip it at least.

## Actual Result
The error below appears
![Screenshot_2022-08-13_10-29-58](https://user-images.githubusercontent.com/1875345/184478338-1e5222bd-c44a-445d-b97a-dbf681d30a84.png)

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
see attached x.job.xml file to reproduce it easily.
[x.zip](https://github.com/openpnp/openpnp/files/9331188/x.zip)

**Comment by markmaker** [comment]
@noeldum, thanks for reporting. This will be fixed in the upcoming roundup.

**Comment by markmaker** [comment]
Forgot to report, this was fixed in #1472.

**Comment by noeldum** [comment]
Can do but will take a while. We are busy with production at the moment. Also my openpnp machine has been temporarily decommissioned because we are getting a new pick and place. I'll surely give this a try when possible.
