### ISSUE TITLE
Typo in Named CSV Import

### ISSUE THREAD

**Issue by GeoffState** [openpnp/openpnp#1488]
# Read This First
Issues must only be opened once they are confirmed.
Please [visit the discussion group](https://groups.google.com/group/openpnp) first, so bugs or missing features can be separated from other problems.

To submit an issue for OpenPnP you must use this template or it will be deleted. Please fill out either the Problem Report or Feature Request section below and delete the other section.

-----------------------------------------------------------------------

# Problem Report
## Describe the Issue
Typo in Named CSV Import

## Steps to Reproduce
1. Open File > Import Board > Named CSV
2. Error occurs in the first word on the Files pane
3. reads Centeroid File (CSV)

## Expected Result
Should read Centroid File (CSV)

## Actual Result
reads Centeroid File (CSV)

## Screen Capture
![Centeroid](https://user-images.githubusercontent.com/7799948/191621283-64c893d7-832b-48f0-a3d0-cc51b339c221.gif)

-----------------------------------------------------------------------

**Comment by GeoffState** [comment]
**TO FIX**
**File:** NamedCSVImporter.java
**Line:** 403: JLabel lblTopFilemnt = new JLabel("Cen**ter**oid File (.csv)"); 
Centeroid should read Cen**tr**oid

**Comment by markmaker** [comment]
Thanks, @GeoffState, done in #1489

**Comment by markmaker** [comment]
Now available in the `testing` version. I don't think it is important enough to cherry-pick to the `regular` version.
