### ISSUE TITLE
Not an issue, just a holder for images related to PR1507 - New Panelization

### ISSUE THREAD

**Issue by tonyluken** [openpnp/openpnp#1509]
![newTabs](https://user-images.githubusercontent.com/50550971/209983742-d3fe111c-7c30-4cc9-9559-265e25fff5ac.png)

![classDiagram](https://user-images.githubusercontent.com/50550971/209984504-407209d2-1df0-41f5-899a-30628dc066d3.png)

<img width="826" alt="jobTabChanges" src="https://user-images.githubusercontent.com/50550971/210017043-4a1576ad-46a4-4ff7-a2a5-89939d6b7329.png">

<img width="827" alt="panelsTab" src="https://user-images.githubusercontent.com/50550971/210018592-c63081df-af58-4d2f-8848-4786da5f33f1.png">

<img width="843" alt="boardsTab" src="https://user-images.githubusercontent.com/50550971/210018963-d9320698-6675-4d05-afc9-f36f4b5a48a9.png">

<img width="732" alt="testPanel" src="https://user-images.githubusercontent.com/50550971/210029052-6d4ed200-8956-43dd-9373-102fe781277e.png">

<img width="875" alt="testPanelPhotoTop" src="https://user-images.githubusercontent.com/50550971/210090575-b79e87be-54bc-4c34-99ae-9af6c4098f24.png">

<img width="985" alt="testPanelPhotoBottom" src="https://user-images.githubusercontent.com/50550971/210090609-65c5a982-b29b-4f25-bf9d-149d86973af4.png">

**Comment by markmaker** [comment]
@tonyluken, in case you missed it: the Wiki now allows pasting images directly. In fact I believe it now takes them over anyways. 

_Mark
