### ISSUE TITLE
NozzleTip need height values.

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#152]
There exist special Nozzles for heighter components, that get used to pick and place components
over certain height if the machine don't have the needed Z excursion. 
The most use case are polarized condensators, ethernet and usb connectors, and TH Leds.
Further it's possible that nozzle get consumed and height need to be adjusted for the specific Nozzle
in order to continue to use it.

**Comment by vonnieda** [comment]
Agreed. I thought I actually already had a ticket in for this, but I can't find it. This is high on the priority list.
