### ISSUE TITLE
Improve sorting in tables.

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#159]
When Table is sorted the result is something:
Board1
Board10
Board11
Board12
Board2

Same is with coordinates .

**Comment by maaadbob** [comment]
I see no bug here.
"Board12" is indeed less than "Board2" when compared.

Perhaps you can provide some code to overcome this sorting problem ?

Bob.

On 05/10/2015 15:21, cri-s wrote:
> When Table is sorted the result is something:
> Board1
> Board10
> Board11
> Board12
> Board2
>
> Same is with coordinates .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openpnp/openpnp/issues/159>.
>

-- 

Southern Assemblies Ltd
Mob: +447758256558
Email: info@southern-assemblies.co.uk
G+: https://plus.google.com/113190327999615741877
Twitter: @SA__Ltd
Registered in England and Wales: 08149202
VAT registration No. GB183 8073 87

**Comment by cri-s** [comment]
I see the bug here, and the bug is more evident if sorting on double value.

Yes, comparator need to be written. I can do it, but not now.
In the meantime i have filled this ticked.

2015-10-05 14:25 GMT, MadBob <notifications@github.com>:

**Comment by cri-s** [comment]
Implemented and committed.

**Comment by cri-s** [comment]
Implemented and committed.

**Comment by cri-s** [comment]
Implemented and committed.
