### ISSUE TITLE
DipTrace support out of date.

### ISSUE THREAD

**Issue by hydra** [openpnp/openpnp#1625]
# Problem Report
## Describe the Issue

Importing a DipTrace CSV file doesn't handle the updated CSV column headers that were changed in DipTrace 4.3.

## Steps to Reproduce
1. Start OpenPnP
2. File/Import/Diptrace
3. Open a file saved using the default DipTrace 4.3 CSV columns.

## Expected Result
Successful import, without having to remove, rename or re-order any fields in the CSV file.

## Actual Result
Failure, user has to rename, remove or otherwise fiddle with the export dialog.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue

Diptrace < 4.3 (not sure of the exact version when they changed, check the DipTrace release notes):
```
RefDes,Name,X (mm),Y (mm),Side,Rotate,Value
```

Diptrace >= 4.3
```
RefDes,Name,Center X (mm),Center Y (mm),Side,Rotation,Value
```

I had to make a similar change in my PnPConvert tool, the commit and diff can be seen here:

https://github.com/hydra/pnpconvert/commit/7c965c0153203f3e2bf271894db739027bde4d07

Additionally:
1) the use of a CSV reader library, to correctly handle quoted CSV files, and/or values that have commas (`,`), could be considered, such as [OpenCSV](https://opencsv.sourceforge.net/).  
2) consider using a 'known column headers' to 'column index' mapping to access the values of the rows so that the exported csv file can a) have the columns in any order, b) have additional (ignored) fields, c) so better error messages can be displayed, such as 'missing column for "<column name>", Header aliases: ["aliase",...]>'  e.g. `Missing column for "X", Aliases: ["X (mm)", "Center X (mm)"]`

In PnPConvert:
* I define an enum which has keys for the required columns, each enum has alias values, e.g. column `X` has (`X (mm)` and `Center X (mm)`.
* I parse the column header, looking for acceptable required fields and build an enum value to column index mapping.
* The column index mapping is then used when accessing the values from the csv lines that contain the rows (values).

It would be great if DipTrace support could be updated and made more robust and user friendly.

**Comment by markmaker** [comment]
Yes, go ahead and submit a PR :sunglasses: 

Please also see https://github.com/openpnp/openpnp/pull/1513 and possibly consolidate that.

The idea is to not break the diptrace 3.x users' workflow, i.e. it must either somehow detect which version it is, (by the headers?) or let the user choose.

_Mark
