### ISSUE TITLE
Incorrect/non-standard naming on footprint fields.

### ISSUE THREAD

**Issue by hydra** [openpnp/openpnp#1639]
# Problem Report
## Describe the Issue

Whist looking into why `height` is on the 'part' and not the 'package' I stumbled on the XML definition of a footprint which has a `body-height` and a `pad` element with a `height` attribute which just seemed very very wrong to me.

example:
```
<openpnp-packages>
   <package version="1.1" id="FIDUCIAL-1X2" pick-vacuum-level="0.0" place-blow-off-level="0.0">
      <footprint units="Millimeters" body-width="0.0" body-height="0.0" outer-dimension="0.0" inner-dimension="0.0" pad-count="0" pad-pitch="0.0" pad-across="0.0" pad-roundness="0.0">
         <pad name="1" x="0.0" y="0.0" width="1.0" height="1.0" rotation="0.0" roundness="100.0"/>
      </footprint>
...
```

Width and Height sometimes make sense when describing 2D objects, such as rectangles normally drawn on a computer monitor oriented in an upright position (e.g. java AWT API Rectangle) but when describing a PCB footprint 'height' doesn't make sense.

IMHO, Width + Length should be used.  That is X=Width, Y=Length, not Y=Height

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
1. Start OpenPnP
2. Quit OpenPnP
3. Open the packages.xml file

## Expected Result
`height` replaced with `length` on the attributes.

```
<openpnp-packages>
   <package version="1.1" id="FIDUCIAL-1X2" pick-vacuum-level="0.0" place-blow-off-level="0.0">
      <footprint units="Millimeters" body-width="0.0" body-length="0.0" outer-dimension="0.0" inner-dimension="0.0" pad-count="0" pad-pitch="0.0" pad-across="0.0" pad-roundness="0.0">
         <pad name="1" x="0.0" y="0.0" width="1.0" length="1.0" rotation="0.0" roundness="100.0"/>
      </footprint>
...
```
What did you expect to happen? Be descriptive.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
I dug into this a bit more, and referenced some datasheets for components and their drawings and found my thoughts confirmed.

The JEDEC MO-274D standard (https://www.jedec.org/standards-documents/docs/mo-247-d)  has this:

![image](https://github.com/openpnp/openpnp/assets/57075/b63b6944-19e8-43c5-a247-3a81d987d696)

![image](https://github.com/openpnp/openpnp/assets/57075/e58681f2-927f-4a70-bcbc-12ef98da9917)

**Comment by hydra** [comment]
And of course, just after posting that, I realized that JEDEC MO-247D has X=D=LENGTH and Y=E=WIDTH

But certainly, and most importantly, Z=Height, not X or Y.

**Comment by hydra** [comment]
Other references:

https://www.geeksforgeeks.org/length-width-height/

> Length is used to measure the longest dimension of a figure
> Width is a linear measurement which is used to measure only the shorter distance of an object
> Height or depth is the third vertical dimension of object in 3D shape

https://www.cuemath.com/measurement/length-width-height/

https://boxesgen.com/length-width-height-understanding-dimensions/

https://www.math.net/depth

**Comment by markmaker** [comment]
In terms of the pads specifically, I would agree. This was reported before and we fixed it in the UI:

![Pad length](https://github.com/openpnp/openpnp/assets/9963310/4eba4ac8-84c8-424b-a072-5ee81083ac3d)

However, we can't change the naming in the code, as it would break the XML serialization.

Also from a coding point-of-view it is much less clear cut. Footprints/pads are closely intertwined with the 2D and image classes of Java, where "width" and "height" are the conventional terms. Where do you make the transition from one world to the other?

I've searched for some screenshots to see how it is is defined in E-CADs. The first I found, OrCAD calls it "Width" and "Height" too:

![Pad in OrCAD](https://github.com/openpnp/openpnp/assets/9963310/bd837404-6606-4551-828c-d4a55f94fdcc)

KiCAD calls it "X-Size" and "Y-Size", Eagle calls it "dx" and "dy", which are better than any of the "word" terms, IMHO.

_Mark

P.S. Professionally, I've written many interfaces for CAD, CAM, BOM, etc. in manufacturing and I would say that empirically these terms are _anything_ but well-defined. For instance, in the wood working industry (with exceptions proving the rule), the "length" is the direction of the fibers of the wood, regardless of which dimension is longer, or where in X/Y/Z it is pointing. And working with parametric parts, it would be an absolute nightmare to define the "length" unstably as "the longest dimension of a figure". :fearful:

**Comment by hydra** [comment]
> However, we can't change the naming in the code, as it would break the XML serialization

it can be changed, but it would require some form of migration to read in the old names and serialize with the new names.

serialization libraries I've used in the past have had the ability to support aliases for attributes and elements.

alternatively you can also define two 'setters', one for the old name, one for the new name, then when the serialization library encounters an xml attribute it will look for the setter matching the name of the attribute, this setter then simply updates the correct java field name. additionally you don't provide a 'getter' for the old field name.

e.g.

```
@deprecated
public void setHeight(Double height) {
    length = height
}

public void setLength(Double length) {
    this.length = length
}
```

I've not yet looked into what serialization system openpnp uses, but it's possible for sure.



> KiCAD calls it "X-Size" and "Y-Size", Eagle calls it "dx" and "dy", which are better than any of the "word" terms, IMHO.

yes, `x-size` / `y-size` are pretty clear and unambiguous for both 2d and 3d shapes.
they would also help if one was to support footprint generation from datasheets using the IPC-7351 standard.  https://www.protoexpress.com/blog/features-of-ipc-7351-standards-to-design-pcb-component-footprint/

**Comment by markmaker** [comment]
Agree but that's too much work for a cosmetic change in an XML that only nerds look at. And I really hope you were not toying with the idea of manipulating the `packages.xml` directly, bypassing all (future) business logic.

Plus, like I said, from a code perspective, the "wrongness" isn't even clear-cut. IMHO, mental transformations and projections between layers of software are sometimes needed and acceptable. For instance: OpenCV has the coordinate system reversed, i.e. Z is pointing away from the camera, where it points towards the camera in OpenPnP. The Y axis and the sense of rotation are therefore inverted. Consequently, we programmers always need to apply that transformation both in code, and mentally, while inside the OpenCV realm. When I say "suck it up", is it too rude? (I'm  not a native English speaker 😇) .

_Mark

**Comment by hydra** [comment]
I was indeed entertaining generating .xml files outside of openpnp, I didn't like the idea however for the reasons you mentioned, and also having to constantly maintain and match up any xml generation code to the openpnp code and/or any published xml dtd.   To this end, see #1640 which is my latest route to solving my needs.

yes, saying 'suck it up' is to rude 😱 

yes, I understand there's sometimes mental transformations, especially with various coordinate systems, I'm no stranger to that.

I'm of the opinion that:
* naming is hard.
* the first guess at a name is usually wrong.
* code review should pay close attention to the names of things that are hard to change later.
* when a naming is wrong, it should be corrected for all future readers/maintainers of the code.
* fewer mental transformations and projections results in easier to understand code, i.e. fewer '"WTF's" per minute'

**Comment by vonnieda** [comment]
I promise you those names were not my first guess. I really struggled with this. I find "length" to be very confusing and non-specific.

Making a change to the XML is possible - we've done it before. It means adding a new property, migrating the property when the file is loaded, and nulling out the old property. But the important question is: Is it worth it?

Is it worth it to change hundreds of thousands of lines of deployed, production XML files for thousands of users because the name bothers someone? I think the answer is no. IMHO it warrants a comment and explanation in the code, and leave it at that.

FWIW, I used to be a little less cautious about config file changes, but they've been quite stable now for many years, and lots of people have built tooling and scripting around them, so I am a lot more conservative about it now.

Jason

**Comment by hydra** [comment]
> Making a change to the XML is possible - we've done it before. It means adding a new property, migrating the property when the file is loaded, and nulling out the old property. But the important question is: Is it worth it?
> 
> Is it worth it to change hundreds of thousands of lines of deployed, production XML files for thousands of users because the name bothers someone? I think the answer is no. IMHO it warrants a comment and explanation in the code, and leave it at that.

It has to be weighed up against all of the other tasks, for me it's a would-be-nice kinda change, not critical, and there's other things that are more important.  Since the XML is apparently only meant to be consumed by OpenPnP itself it's less of an issue than I first thought.

I'll close this now, but we can always revisit this in the future if we desire.
