### ISSUE TITLE
Clicking stop after unplugging smoothie board locks up UI

### ISSUE THREAD

**Issue by embmicro** [openpnp/openpnp#167]
If you click start, unplug the smoothie board, then click stop, the UI locks up. I just lost a bunch of project settings because of this (teach me to save more) :/.

**Comment by vonnieda** [comment]
Are you using the OpenBuilds driver?

If so, I see the bug. It should be set to timeout after a period and it's
not.

Ideally the UI needs to be decoupled from this anyway. That's how I will
plan to fix this.

**Comment by vonnieda** [comment]
Note to myself: Easy fix will be to run setEnabled() on the machine executor.

**Comment by embmicro** [comment]
I am running it on Linux and just running everything from the tar archive.

**Comment by vonnieda** [comment]
Bug should be fixed now if you download a fresh copy.

**Comment by vonnieda** [comment]
Reopening because while the UI no longer locks up, the setEnabled(false) still doesn't time out which makes it impossible to actually close the program. Preparing a fix for that now.
