### ISSUE TITLE
The new version of the nozzle replacement function seems to have an issue

### ISSUE THREAD

**Issue by ZHUBILUO** [openpnp/openpnp#1683]
-----------------------------------------------------------------------
The latest version of PNP (beta version) has a serious bug in automatic nozzle replacement.
I am using a nozzle changer controlled by an electromagnet. When replacing the nozzle, the electromagnet starts and moves the top stopper to the right before the nozzle can be inserted into the hole,
Fault phenomenon: When using the PNP test version, the electromagnet below the suction nozzle does not start, while in the non test version, everything is normal. The configuration files during this period have not been changed or modified. Please watch the video

The reason why I am using the new beta version is that it has excellent Chinese translation, which is a great thing for someone like me who has poor English. I am very grateful for everything the openpnp team has done

https://github.com/user-attachments/assets/826a898d-824f-44c0-ac5d-766e1970102d

Looking forward to receiving a response, thank you

**Comment by markmaker** [comment]
There is no "beta" version. Did you mean the "test" version?

There has been a bug-fix in the nozzle tip changer.  The former implementation would always actuate the actuator `{True}`, i.e. no distinction can be made between loading and unloading. This is needed for some changers.

Now it is actuated `{True}` when the nozzle is loaded, and `{False}`, when it is unloaded. 

For you to get the same behavior as before, just duplicate the G-code on the Actuator from the `{True}` to the `{False}`,

https://github.com/openpnp/openpnp/pull/1620
https://groups.google.com/g/openpnp/c/hH1CKmOWX8I/m/TV64xricAgAJ

_Mark
