### ISSUE TITLE
strip feeder error when his angle is 180

### ISSUE THREAD

**Issue by JoseDanielMunozFrias** [openpnp/openpnp#178]
When a strip header is located at 180 degrees, the software thinks that it is at 0 degrees and go to the wrong side to pick the part.

**Comment by vonnieda** [comment]
Hi @JoseDanielMunozFrias, can you post a screenshot or some details to show how to reproduce this problem?

**Comment by JoseDanielMunozFrias** [comment]
Whow! You are pretty fast. I have sent a commit with the solution.

**Comment by JoseDanielMunozFrias** [comment]
Whell, A pull request.

**Comment by JoseDanielMunozFrias** [comment]
![image](https://cloud.githubusercontent.com/assets/16222692/11820851/c2ef6650-a366-11e5-9d68-bd8ae774be49.png)

**Comment by vonnieda** [comment]
Thanks @JoseDanielMunozFrias, I will test this and merge if it looks okay in a day or two.

**Comment by vonnieda** [comment]
Thanks for the report and the pull request!

**Comment by JoseDanielMunozFrias** [comment]
Thanks to you for this phenomenal project.
