### ISSUE TITLE
Wiki Images - Ignore

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#180]
Placeholder for Wiki Images. Not a real issue.

**Comment by vonnieda** [comment]
![screen shot 2015-12-17 at 7 38 36 pm](https://cloud.githubusercontent.com/assets/1182323/11888726/cd026382-a4f5-11e5-9b3b-6f9729ebeb0a.png)

**Comment by vonnieda** [comment]
![strip feeder orientation](https://cloud.githubusercontent.com/assets/1182323/12517177/6108c344-c0e6-11e5-9228-874a35a3fa5c.png)

**Comment by vonnieda** [comment]
![understanding board locations - new](https://cloud.githubusercontent.com/assets/1182323/12605892/c8e2d8e8-c47d-11e5-8b80-743e2a8d0b3d.png)

**Comment by vonnieda** [comment]
![screen shot 2016-02-21 at 2 35 27 pm](https://cloud.githubusercontent.com/assets/1182323/13205929/8a9f8272-d8a8-11e5-8509-7df8d5d4a59a.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 10 33 18 am](https://cloud.githubusercontent.com/assets/1182323/16172512/1cf472b0-3540-11e6-987a-fff822524944.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 10 34 20 am](https://cloud.githubusercontent.com/assets/1182323/16172608/8dad6e20-3541-11e6-84ab-5a87c3bfdc91.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 10 48 23 am](https://cloud.githubusercontent.com/assets/1182323/16172727/d84709b8-3542-11e6-89a3-6890e2f0492e.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 10 55 18 am](https://cloud.githubusercontent.com/assets/1182323/16172744/378a016e-3543-11e6-9e1d-f7a0474cd954.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 10 56 16 am](https://cloud.githubusercontent.com/assets/1182323/16172751/4dfac9e2-3543-11e6-8326-5cc9e18e08a1.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 11 15 41 am](https://cloud.githubusercontent.com/assets/1182323/16172859/06fbef82-3546-11e6-9666-73288748f2a3.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 11 24 59 am](https://cloud.githubusercontent.com/assets/1182323/16172909/5247ebd4-3547-11e6-9dfa-8d63af3d66cd.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 11 26 13 am](https://cloud.githubusercontent.com/assets/1182323/16172925/a0c8edf8-3547-11e6-95cf-13d5cfba0c11.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 11 29 46 am](https://cloud.githubusercontent.com/assets/1182323/16172939/fed3b05e-3547-11e6-8db8-c4cac423a34f.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 11 31 15 am](https://cloud.githubusercontent.com/assets/1182323/16172950/319d6534-3548-11e6-8a3a-ad975e4a6ec4.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 11 33 19 am](https://cloud.githubusercontent.com/assets/1182323/16172974/8bf8e774-3548-11e6-8f5f-9608bc603bb0.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 11 38 48 am](https://cloud.githubusercontent.com/assets/1182323/16172994/3fd9c286-3549-11e6-9939-1ee0057c0911.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 12 28 31 pm](https://cloud.githubusercontent.com/assets/1182323/16173252/30d0f546-3550-11e6-90e0-facf96c4240f.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 12 29 50 pm](https://cloud.githubusercontent.com/assets/1182323/16173259/60369a20-3550-11e6-958a-af61e601b540.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 12 34 25 pm](https://cloud.githubusercontent.com/assets/1182323/16173276/021ea7a6-3551-11e6-917d-e3ed680d4d46.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 12 54 09 pm](https://cloud.githubusercontent.com/assets/1182323/16173355/df7c8e54-3553-11e6-8c59-c5b75c1a48f0.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 12 56 07 pm](https://cloud.githubusercontent.com/assets/1182323/16173361/0e54935c-3554-11e6-9cf6-caf13e6d4a65.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 12 58 51 pm](https://cloud.githubusercontent.com/assets/1182323/16173377/6f788a9e-3554-11e6-8b13-76cc612fad84.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 12 59 52 pm](https://cloud.githubusercontent.com/assets/1182323/16173384/98b58fc4-3554-11e6-9382-819aa1d82c11.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 1 01 43 pm](https://cloud.githubusercontent.com/assets/1182323/16173392/d36f81ce-3554-11e6-9eab-b6e6794f913b.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 1 23 19 pm](https://cloud.githubusercontent.com/assets/1182323/16173504/dec01e3c-3557-11e6-9132-fa04ffcd0e4f.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 1 44 57 pm](https://cloud.githubusercontent.com/assets/1182323/16173591/eaf428a8-355a-11e6-9055-e94538de511a.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 4 46 29 pm](https://cloud.githubusercontent.com/assets/1182323/16174378/69ab388a-3574-11e6-96b4-8419db5f3584.png)

**Comment by vonnieda** [comment]
![screen shot 2016-06-18 at 4 52 04 pm](https://cloud.githubusercontent.com/assets/1182323/16174397/0395145c-3575-11e6-8566-dcecb5754606.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 06 57 am](https://cloud.githubusercontent.com/assets/1182323/19995185/fca56a28-a222-11e6-9bed-87458100683e.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 10 08 am](https://cloud.githubusercontent.com/assets/1182323/19995197/236c9abe-a223-11e6-9be6-bf5d45c36f02.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 11 11 am](https://cloud.githubusercontent.com/assets/1182323/19995219/39ec29ee-a223-11e6-9d86-e44639c30976.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 16 09 am](https://cloud.githubusercontent.com/assets/1182323/19995290/ea20b7da-a223-11e6-86aa-5971f7d26b9b.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 21 15 am](https://cloud.githubusercontent.com/assets/1182323/19995374/a05a2f7c-a224-11e6-8c55-4d09f53db2ff.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 21 55 am](https://cloud.githubusercontent.com/assets/1182323/19995382/b8fea24c-a224-11e6-8e85-443940ab3515.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 36 52 am](https://cloud.githubusercontent.com/assets/1182323/19995594/cf093488-a226-11e6-8eca-ce4671574e60.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 37 21 am](https://cloud.githubusercontent.com/assets/1182323/19995602/e035c88e-a226-11e6-8948-44900a3c8100.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 38 05 am](https://cloud.githubusercontent.com/assets/1182323/19995607/fae2a936-a226-11e6-849a-a026a0ece25a.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 39 59 am](https://cloud.githubusercontent.com/assets/1182323/19995638/3f65d13c-a227-11e6-9470-feb59faf5ff2.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 40 44 am](https://cloud.githubusercontent.com/assets/1182323/19995651/59edb0ce-a227-11e6-9380-a28aee1e2dc4.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 43 12 am](https://cloud.githubusercontent.com/assets/1182323/19995687/b253c942-a227-11e6-9798-049a43ee9f53.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 44 02 am](https://cloud.githubusercontent.com/assets/1182323/19995713/dfe91cae-a227-11e6-8aa0-880ec24022d1.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 51 27 am](https://cloud.githubusercontent.com/assets/1182323/19995823/d838e2d6-a228-11e6-9107-3fb9a8a0fb01.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 52 17 am](https://cloud.githubusercontent.com/assets/1182323/19995838/f66fc7b0-a228-11e6-98d1-75eca85eb6f1.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 57 15 am](https://cloud.githubusercontent.com/assets/1182323/19995930/a88b147c-a229-11e6-9252-e7895f1dc24b.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 58 14 am](https://cloud.githubusercontent.com/assets/1182323/19995951/d3de7510-a229-11e6-90d8-12f2e1668151.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 58 14 am](https://cloud.githubusercontent.com/assets/1182323/19995951/d3de7510-a229-11e6-90d8-12f2e1668151.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 1 02 58 am](https://cloud.githubusercontent.com/assets/1182323/19996017/755b5dea-a22a-11e6-84e1-3a220aa9f666.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 1 08 07 am](https://cloud.githubusercontent.com/assets/1182323/19996104/2e1c970e-a22b-11e6-9578-112ef11d6210.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 1 10 24 am](https://cloud.githubusercontent.com/assets/1182323/19996152/7dd1f604-a22b-11e6-80fa-f07df990358e.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 1 12 59 am](https://cloud.githubusercontent.com/assets/1182323/19996191/d9ecaa42-a22b-11e6-9892-d0f928377f9f.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 1 24 11 am](https://cloud.githubusercontent.com/assets/1182323/19996431/6d59cdb8-a22d-11e6-9671-979919847458.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 1 24 11 am](https://cloud.githubusercontent.com/assets/1182323/19996431/6d59cdb8-a22d-11e6-9671-979919847458.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 1 27 03 am](https://cloud.githubusercontent.com/assets/1182323/19996484/e023f382-a22d-11e6-9c26-ec355e0b1c16.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 24 01 pm](https://cloud.githubusercontent.com/assets/1182323/20015475/a0a3a91c-a289-11e6-9278-1346249d12cb.png)

**Comment by vonnieda** [comment]
![screen shot 2016-11-04 at 12 26 02 pm](https://cloud.githubusercontent.com/assets/1182323/20015546/df04dd20-a289-11e6-8350-298314ca5e2f.png)

**Comment by JacobChrist** [comment]
Jason,

Correct me if I'm wrong. Your posting these images so that you can link to
them in the Wiki documentation.  Might it be a good idea to store them in a
directory in the repo?

Jacob

Jacob Christ
*ProLinear/PONTECH, Inc.*
+1 (909) 652-0670 Phone
http://www.pontech.com

**Comment by vonnieda** [comment]
Hi Jacob,

You've got it right. I use this issue to store images that I am using in
the Wiki. I do it this way because Github supports image drag and drop into
Issues but not Wiki pages. So, I drag the images here and copy the URL that
gets generated for the Wiki. I find putting them in the repo to be a pain
and it really slows down my workflow for creating Wiki pages.

Jason

**Comment by JacobChrist** [comment]
Okay... After I sent the e-mail I thought it might make the repo bloated as
well.

Jacob

Jacob Christ
*ProLinear/PONTECH, Inc.*
+1 (909) 652-0670 Phone
http://www.pontech.com

**Comment by vonnieda** [comment]
![Screen Shot 2019-06-12 at 10 58 51 PM](https://user-images.githubusercontent.com/1182323/59403014-83449000-8d66-11e9-841e-40ee3717dc00.png)

**Comment by markmaker** [comment]
![Add Actuator](https://user-images.githubusercontent.com/9963310/183957702-706a9d6f-ea75-4910-a912-8f9ed60714f2.png)
![Select Actuator Type](https://user-images.githubusercontent.com/9963310/183957798-81caddf2-b24b-405c-8d09-63a7b714621f.png)
