### ISSUE TITLE
Simultaneous, multiple tool heads with different tools (enhancement)

### ISSUE THREAD

**Issue by aShure** [openpnp/openpnp#181]
Something like this:
Part list includes a parameter per part for a tool form, ie. smallest size nozzle type '0.2' for 01005 and largest type '20' for a large BGA. There are multiple Z and C axes available on the machine, each with fixed offsets in XY. If the feeders are placed apart at the same distance they could pick up parts all at once.
A head and it's tool is chosen by the parameters in the part list.

Additional feature: Each part or part size category has a maximum jerk or acceleration value attached.
The maximum jerk at any given time is determined by the part currently held up with the lowest jerk value. Maximum velocity is not really important.

**Comment by vonnieda** [comment]
I think you are probably referring to multiple nozzles, not heads, in OpenPnP parlance, at least. In OpenPnP a head is something that moves independently in X and Y while a nozzle is attached to a head and moves in Z and C. If that's what you are referring to, OpenPnP already supports this functionality although not exactly as described. You can choose which NozzleTips support which packages and the system will automatically plan placements based on that. If multiple nozzles are available OpenPnP will carry multiple parts per trip to the feeders.

Extending this functionality to jerk is machine / driver specific. Happy to accept a pull request for it but it's not a feature I intend to add to the core system.
