### ISSUE TITLE
Discussion for Driver refactoring, moveTo blocking, GCode, etc.

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#189]
Comments originally made on #183, moved to this issue for further discussion.

 cri-s commented 2 hours ago
Jason, i have extended the driver api a bit,
void dwell()  , wait until finished
void dwell(double)  wait time in seconds.
boolean GCode(string)
boolean GCode(string,time)

Actually the only not right is on firepick driver, where i probably
need community help if this
get accepted by you. Then i suggest to use GCode for driving it. I
suggest then to use GCode
for driving changer and i think, manual should be highest priority.
Currently i have tested only dwell(double) in order to go away with
thread sleeping and that
works.

2016-01-11 17:12 GMT+01:00, Jason von Nieda <notifications@github.com>:
…
 @vonnieda
  Owner
vonnieda commented an hour ago
void dwell() , wait until finished
void dwell(double) wait time in seconds.

What is the purpose of the dwell commands and how will they be used? I don't see this as being included because all of the driver methods are supposed to block until they are finished. If something is returning before it's complete then that is a bug.

boolean GCode(string)
boolean GCode(string,time)

These we will not include. The Driver interface is designed to be controller agnostic and this would make it specific to GCode. If you want GCode specific methods just extend the ReferenceDriver interface and implement them in your branch.
 @cri-s
  
 cri-s commented 44 minutes ago
dwell wait until all gcode are processed. No only some gcode are
blocking, the other return without being completed.
dwell(double seconds) wait seconds until and return after all previous
motion code are finished.
I have used it to replace    Thread.sleep(pickDwellMilliseconds);  as
otherwise it don't worked
because gcode and pc are never in sync.
GCode() would be nice for nozzle changer code and others, that are
always machine specific
and mostly have only moves inside it. You'r decision.

2016-01-11 18:04 GMT+01:00, Jason von Nieda <notifications@github.com>:
…
 @vonnieda
  Owner
vonnieda commented 32 minutes ago
@cri-s All driver calls should block until they are finished. This contract must be enforced or lots of other things will break. For instance, if moveTo() or place() does not block then the machine may try to move before it's finished placing. If you have driver calls that don't block, that is a bug and should be fixed. Just call dwell() internally in the driver, as many of the drivers already do.

We can't add GCode specific things to the driver interface because there are machines that don't use GCode. For instance, the TinyG and FirePick drivers use JSON for communication. Having a GCode command on it would be meaningless.

If it's very important for you to be able to send generic commands to the driver I would be okay with adding something like public Object sendCustomCommand(Object);. With this you could do something like sendCustomCommand("M100") and then process that as Gcode within your driver.

That being said, I suggest you extend ReferenceDriver and add these functions to your own driver. The program is designed to be extended like this.
 @cri-s
  
 cri-s commented 11 minutes ago
moveTo don't need to block, and it's contra productive. It's enought
that after pick and place
the call is blocking, and as example actors are not blocking too. .
GCode works for TinyG , FirePick , don't know i have left it as dummy
function for now.

**Comment by vonnieda** [comment]
@cri-s OpenPnP expects all driver interactions to complete before they return, i.e. block. Without this assumption there are many things that break in OpenPnP. Vision operations expect the camera not to be moving, pick and place operations expect movement to be complete, drag feed operations expect the solenoid to retract before moving, etc. This is a fundamental assumption in OpenPnP and it's not changing without a major redesign.

This is even in the interface documentation. See https://github.com/openpnp/openpnp/blob/develop/src/main/java/org/openpnp/machine/reference/ReferenceDriver.java#L32

As I said previously, if there is a function in the driver that does not block before returning currently then that is a bug that should be fixed.

**Comment by cri-s** [comment]
It is possible to use dwell(time) for all delays and on some utility class
the devell time
Is then converted to delay call.
This would allow coexistence with real gcode and wait until done as you
have actually made it. This development  was not noticed by me as the
default driver not works and the improvemnted was rejected on submission.

Il mercoledì 13 gennaio 2016, Jason von Nieda <notifications@github.com> ha
scritto:

**Comment by vonnieda** [comment]
@cri-s If you want this to be added please submit a clean pull request showing why it's needed and how it is used. From what you have described so far this seems to break the driver model as it is currently designed.

**Comment by cri-s** [comment]
As pure discussion , here one Driver. The addition to ReferenceDriver.

	public  boolean GCode(String command) throws Exception ;
	public  boolean GCode(String command, long timeout) throws Exception;
	public  void dwell()  throws Exception;
	public  void dwell(double Seconds)  throws Exception;

And instead of calling Thread.sleep(Milliseconds) it calls
driver.dwell(Milliseconds/1000.)
whenever the thread need waiting.
As you see, only pick and place are blocking on Gcode level (waiting
for end of motion).
All other opereration are queued on execution.
Further ther exist gcodes, as example M121 that calls relay and wait
for external acnowledge
on F_IN input.
The point is, that like on cnc machine, the gcode is streamed down,
not send line by line and
waited for completition, otherwise it's really slow, and camera
capture cannot be made on
65ms, it need a lot more, if doing this on PC waiting.
Thats the whole question. Actually i call driver.dwell() , but dwell()
function, that call driver
itself should be more generally used. As said, i don't have actually
solution for firepick driver.
If you say yes, i ask, otherwise it's just dummy function.
pc timing on sleep can be worst, serail usb buffering implies delays, ... .

package org.openpnp.machine.reference.driver;


import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.TimeoutException;

import javax.swing.Action;

import org.openpnp.gui.support.PropertySheetWizardAdapter;
import org.openpnp.gui.support.Wizard;
import org.openpnp.machine.reference.ReferenceActuator;
import org.openpnp.machine.reference.ReferenceHead;
import org.openpnp.machine.reference.ReferenceHeadMountable;
import org.openpnp.machine.reference.ReferenceNozzle;
import org.openpnp.machine.reference.driver.wizards.AbstractSerialPortDriverConfigurationWizard;
import org.openpnp.model.LengthUnit;
import org.openpnp.model.Location;
import org.openpnp.model.Part;
import org.openpnp.spi.PropertySheetHolder;
import org.simpleframework.xml.Attribute;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MultiHeadMultiRelayDriver extends
AbstractSerialPortDriver implements Runnable{
	private static final Logger logger =
LoggerFactory.getLogger(MultiHeadMultiRelayDriver.class);
	private static final double minimumRequiredVersion = 0.81;
	private double connectedVersion;
	private boolean disconnectRequested;
	
	private Object commandLock = new Object();
	
	private double x, y, z, z0, z1, c, c0, c1, f=0;
	private boolean tool=false;
    @Attribute(required=false)
    private int mm=0;
    @Attribute(required=false)
    private double delay=0;
    @Attribute(required=false)
    private double delay0=0;
    @Attribute(required=false)
    private double delay1=0;
    @Attribute(required=false)
    private double delay2=0;
    @Attribute(required=false)
    private double delay3=0;
    @Attribute(required=false)
    private int autoHeight=999;
    @Attribute(required=false)
    private int pickM=0x89;
    private int vacuum = 0;
    private boolean connected;
    private Thread readerThread;

    @Attribute(required=false)
    private double zCamRadius = 24;

    @Attribute(required=false)
    private double zCamWheelRadius = 9.5;

    @Attribute(required=false)
    private double zGap = 2;

	private Queue<String> responseQueue = new ConcurrentLinkedQueue<String>();
	
	@Override
	public void home(ReferenceHead head) throws Exception {
		sendCommand("G28"); //Go to Pre-Defined Position
        sendCommand("$H");
        sendCommand("G21");
        sendCommand("M11");
        sendCommand("M22");
        sendCommand("M24");
        sendCommand("M26");
        sendCommand("M28");
        sendCommand("G92 X0 Y0 Z0 C0",700);
        x = y = z= c = 0;
	}

	@Override
	public void moveTo(ReferenceHeadMountable hm, Location loc, double
speed) throws Exception {
        moveTo(hm,loc.getX(),loc.getY(),loc.getZ(),loc.getRotation(),f);
    }
    private void moveTo_(double x1, double y1, double z1, double c1,
double feedRateMmPerMinute)
            throws Exception {

     if (Double.isNaN(x1)||Double.isInfinite(x1))   x1 = this.x;
     if (Double.isNaN(y1)||Double.isInfinite(y1))   y1 = this.y;
     if (Double.isNaN(c1)||Double.isInfinite(z1))   z1 = this.z;
     if (Double.isNaN(c1)||Double.isInfinite(c1))   c1 = this.c;
     if (Double.isNaN(f)||Double.isInfinite(f))   feedRateMmPerMinute = this.f;
     if(f<0||f>99999) feedRateMmPerMinute=this.f;
     if(x1<-999.9||x1>999.9) x1=this.x;
     if(y1<-999.9||y1>999.9) y1=this.y;
     if(z1<-999.9||z1>999.9) z1=this.z;
     if(c1<-999.9||c1>999.9) z1=this.c;

        StringBuffer sb = new StringBuffer();
        if (x1 != this.x) {
            sb.append(String.format("X%2.2f ", x1));
        }
        if (y1 != this.y) {
            sb.append(String.format("Y%2.2f ", y1));
        }
        if (z1 != this.z) {
            double a;
            a = Math.toDegrees(Math.asin((z1 - zCamWheelRadius - zGap)
/ zCamRadius));
            logger.debug("nozzle {} {} {}", new Object[] { z, zCamRadius, a });
            if (tool) a*=-1;
    	if(pickM!=0)
            sb.append(String.format("Z%2.2f ", z1));
	else
            sb.append(String.format("A%2.2f ", a));
        }
        if (c1 != this.c) {
            // TODO see above bug note, and remove this when fixed.
            sb.append(String.format("%c%2.2f ",tool?'B':'C', c1));
        }
        if (sb.length() > 0) {
            if(feedRateMmPerMinute!=0)
            sb.append(String.format("F%2.2f", feedRateMmPerMinute));
            if(feedRateMmPerMinute!=0)
                sendCommand("G1 " + sb.toString());
            else
                sendCommand("G0 " + sb.toString());
            // $G();
        }
        this.x = x1;
        this.y = y1;
	this.c  = c1;
	this.z  = z1;
        if(tool) {
		this.z1 = z1;
		this.c1 = c1;
	}
	else	{
		this.z0 = z1;
		this.c0 = c1;
	}
/*
        if(head!=null)
            head.updateDuringMoveTo(this.x, this.y, this.z, this.c);
*/

    //System.out.println("done
moveTo("+head+","+this.x+","+this.y+","+this.z+","+this.c+")");

    }

    public void moveTo(ReferenceHeadMountable head, double x1, double
y1, double z1, double c1, double f1)
            throws Exception {
        // TODO: Due to a bug (of my creating) in Grbl, C movements are
    	// included in the linear movements, and since they are much slower
        // than X, Y movements they end up slowing the whole thing down.
        // So, as a temporary hack, if there is a C move to be made we'll
        ReferenceNozzle nozzle = null;
        if (head instanceof ReferenceNozzle)             nozzle =
(ReferenceNozzle) head;
        tool = (nozzle == null || nozzle.getName().equals("N1")) ? false : true;
    	if(pickM!=0) tool=false;

	if(tool) { this.z=this.z1; this.c=this.c1; }
	else     { this.z=this.z0; this.c=this.c0; }

	     if(f1==-1) f1=0;
	     if(f1<0||f1>99999) f1=this.f;
	     if (Double.isNaN(x1)||Double.isInfinite(x1))   x1 = this.x;
	     if (Double.isNaN(y1)||Double.isInfinite(y1))   y1 = this.y;
     	     if (Double.isNaN(z1)||Double.isInfinite(z1))   z1 = this.z;
    	     if (Double.isNaN(c1)||Double.isInfinite(c1))   c1 = this.c;
	     if (Double.isNaN(f1)||Double.isInfinite(f1))   f1 = this.f;
	
	     if(x1< -999.9||x1>999.9) x1=this.x;
	     if(y1< -999.9||y1>999.9) y1=this.y;
	     if(z1< -999.9||z1>999.9) z1=this.z;
	     if(c1< -999.9||c1>999.9) c1=this.c;

        if(f1!=0)
            this.f=f1;

    //System.out.println("MoveTo("+head+","+x+","+y+","+z+","+c+","+feedRateMmPerMinute+")");
	if(autoHeight!=999) {
        if(vacuum==0)
                if(z1<autoHeight&&this.z>autoHeight)   // down
                    moveTo_(this.x,this.y,autoHeight,c1,0);
                else
                if(z1<autoHeight) ;
                else f1=0;
/*
                if(z>autoHeight&&this.z<autoHeight)   // up
                    moveTo(head,this.x,this.y,autoHeight+0.1,this.c,f),f=0;
                if(z>autoHeight) f=0;
*/
		}

        // make it first.
        // Also, since C is so slow in comparison, we just increase it
        // by a factor of 10.

        if (c1 != this.c)
        if(f1!=0)
        if(Math.sqrt(     (x1-this.x)*(x1-this.x)
                +(y1-this.y)*(y1-this.y)
                +(z1-this.z)*(z1-this.z)
            )<=Math.sqrt(
                 (c1-this.c)*(c1-this.c)
            )
         )
            moveTo_(this.x, this.y, this.z, c1, f1*10);
            moveTo_(x1, y1, z1, c1, f1);
    //System.out.println("done
moveTo("+head+","+this.x+","+this.y+","+this.z+","+this.c+")");

    }



	@Override
	public Location getLocation(ReferenceHeadMountable hm) {
        return new Location(LengthUnit.Millimeters, x, y, z, c).add(hm
                .getHeadOffsets());
	}

	@Override
	public void pick(ReferenceNozzle head) throws Exception {
        double dly; dly=0.3+delay; int m=(pickM>>4)&0xf;
	if(m==0) m=21; int t=tool?2:0;
	if(vacuum==0) {
        	sendCommand("M10"); // off
		sendCommand("G4P"+(dly+delay0));
	}
        vacuum|= (1<<t);
        if(mm!=0)
	        if(y>mm&&y<(mm+10)) {
	            moveTo(head, x, y-40, z, c, f );
	            sendCommand("M"+(m+t));
	            moveTo(head, x, y, z-5.5, c, f );
	            sendCommand("G4P"+dly);
	            moveTo(head, x, y, z+5.5, c, f );
	            sendCommand("G4P0");
	            moveTo(head, x, y+40, z, c, f );
	            sendCommand("G4P0");
	        } else {
	            sendCommand("M"+(m+t));
	            sendCommand("G4P"+dly);
          } else {
            sendCommand("M"+(m+t));
	    sendCommand("G4P"+dly);
	  }
        //dwell();
    }

	@Override
	public void place(ReferenceNozzle nozzle) throws Exception {
        double dly; dly=0.3;
        dwell();
        int m1=(pickM>>4)&0xf , m2=pickM&0xf , m=pickM;
	if(m==0||m==199) // multi head
	{ int t=tool?2:0; m1=21+1+t; m2=21+4+t; if(m==199) { m1=9; m2=7;}
		place(nozzle,m1,delay1,m2,delay2,m2+1,delay3);
	} else { // single head
		place(nozzle,m1,delay1,m1,delay1,0,0);
	}
       }

	private void place(ReferenceNozzle nozzle,int m1, double dly1, int
m2, double dly2, int m3, double dly3) throws Exception {
	if(delay2<=delay1) { dly1-=dly2;
	if(dly3<0) dly3=0; if(dly2<0) dly2=0; if(dly1<0) dly1=0;
		if(m2>0) {
			sendCommand("G4P"+dly2);
        		sendCommand("M"+m2);
		}
		if(m1>0) {
			sendCommand("G4P"+dly1);
        		sendCommand("M"+m1);
		}
		if(m3>0) {
        		sendCommand("M"+m3);
			sendCommand("G4P"+dly3);
		}
	} else  place(nozzle,m2,dly2,m1,dly1,m3,dly3);

	dwell();
       }

	@Override
	public void actuate(ReferenceActuator actuator, boolean on) throws Exception {
		actuate(actuator,0,on);
	}
	@Override
	public void actuate(ReferenceActuator actuator, double value) throws
Exception {
		sendCommand("M20");
		actuate(actuator,0,value!=0.0);
	}
    private void actuate(ReferenceActuator head, int index, boolean on)
            throws Exception {
        if (index == 0)
            sendCommand(on ? "M7" : "M9");
        if (index == 1)
            sendCommand(on ? "M8" : "M9");
        if (index == 2)
            sendCommand(on ? "M10" : "M11");
        if (index == 3)
            sendCommand(on ? "M3" : "M5");
        if (index == 4)
            sendCommand(on ? "M4" : "M5");
        if (index == 5)
            sendCommand("M20");
        dwell();
    }

	private boolean enabled;
	@Override
	public void setEnabled(boolean enabled) throws Exception {
	    if (enabled && !connected) {
	        connect();
	    }
	    if (connected) {
	        if (enabled) {
	            //sendCommand("$X");
	            sendCommand("\030\030\030",1000);
	            sendCommand("\n",500);
	            sendCommand("\n",1000);
	            sendCommand("G92 X0 Y0 Z0 C0",700);
//	            sendCommand("$1000=" + (enabled ? "1" : "0"));
		}
	            vacuum=0;
			dwell();
        sendCommand("M11");
        sendCommand("M22");
        sendCommand("M24");
        sendCommand("M26");
        sendCommand("M28");
			dwell();
	        }
        x = y = z= c = 0;
	this.enabled=enabled;
	}

	@Override
	public Wizard getConfigurationWizard() {
		return new AbstractSerialPortDriverConfigurationWizard(this);
	}

	@Override
	public String getPropertySheetHolderTitle() {
		return getClass().getSimpleName();
	}

	@Override
	public PropertySheetHolder[] getChildPropertySheetHolders() {
		return null;
	}

	@Override
	public PropertySheet[] getPropertySheets() {
		return new PropertySheet[] {
                new PropertySheetWizardAdapter(getConfigurationWizard())
        };
	}

	@Override
	public Action[] getPropertySheetHolderActions() {
		return null;
	}

/////////////////////////////////////////////////////////////////
	private List<String> sendCommand(String command) throws Exception {
		return sendCommand(command, -1);
	}
	
	private List<String> sendCommand(String command, long timeout) throws
Exception {
		synchronized (commandLock) {
			if (command != null) {
				logger.debug("sendCommand({}, {})", command, timeout);
				logger.debug(">> " + command);
				output.write(command.getBytes());
				output.write("\n".getBytes());
			}
			if (timeout == -1) {
				commandLock.wait();
			}
			else {
				commandLock.wait(timeout);
			}
		}
		List<String> responses = drainResponseQueue();
		return responses;
	}
	private List<String> drainResponseQueue() {
		List<String> responses = new ArrayList<String>();
		String response;
		while ((response = responseQueue.poll()) != null) {
			responses.add(response);
		}
		return responses;
	}
    /**
     * Causes Grbl to block until all commands are complete.
     * @throws Exception
     */

        @Override
        public void dwell(double seconds) throws Exception {
                seconds*=1;
                GCode("G4 P"+seconds);
        }

        @Override
        public void dwell() throws Exception {
                GCode("G4 P0");
        }

        @Override
        public boolean GCode(String command) throws Exception {
                return  GCode(command, -1);
        }

        @Override
        public boolean GCode(String command, long timeout) throws Exception {
                if(connected&&enabled) {
                        sendCommand(command, timeout);
                        return true;
                }
                        return false;
        }
    public synchronized void connect()
            throws Exception {
        disconnect();
        System.out.println("Connect");
        super.connect();
        System.out.println("Connected");

        /**
         * Connection process notes:
         *
         * On some platforms, as soon as we open the serial port it will reset
         * Grbl and we'll start getting some data. On others, Grbl may already
         * be running and we will get nothing on connect.
         */

        List<String> responses;
        synchronized (commandLock) {
            // Start the reader thread with the commandLock held. This will
            // keep the thread from quickly parsing any responses messages
            // and notifying before we get a change to wait.
            readerThread = new Thread(this);
            readerThread.start();
            // Wait up to 3 seconds for Grbl to say Hi
            // If we get anything at this point it will have been the settings
            // dump that is sent after reset.
            responses = sendCommand(null, 3000);
        }

        processConnectionResponses(responses);

        for (int i = 0; i < 5 && !connected; i++) {
            responses = sendCommand("\030", 5000);
            processConnectionResponses(responses);
        }

        if (!connected)  {
            throw new Error(
                String.format("Unable to receive connection response
from Grbl. Check your port and baud rate, and that you are running at
least version %f of Grbl",
                        minimumRequiredVersion));
        }

        if (connectedVersion < minimumRequiredVersion) {
            throw new Error(String.format("This driver requires Grbl
version %.2f or higher. You are running version %.2f",
minimumRequiredVersion, connectedVersion));
        }

        // We are connected to at least the minimum required version now
        // So perform some setup

        // Turn off the stepper drivers
        setEnabled(false);

        // Reset all axes to 0, in case the firmware was not reset on
        // connect.
        sendCommand("G92 X0 Y0 Z0 C0");
    }

    private void processConnectionResponses(List<String> responses) {
        for (String response : responses) {
        	if(true) {
	            if (response.startsWith("$VERSION = ")) {
	                String[] versionComponents = response.split(" ");
	                connectedVersion = Double.parseDouble(versionComponents[2]);
	                connected = true;
	                logger.debug(String.format("Connected to Grbl
Version: %.2f", connectedVersion));
	            }
			} else {
	                connectedVersion = 0.9;
	                connected = true;
			}
        }
    }
    public synchronized void disconnect(){
        disconnectRequested = true;
        connected = false;
        System.out.println("DisConnect");
        try {
            if (readerThread != null && readerThread.isAlive()) {
                readerThread.join();
            }
        }
        catch (Exception e) {
            logger.error("disconnect()", e);
        }
        try {
			super.disconnect();
		} catch (Exception e) {
			logger.error("disconnect()", e);
		}

        disconnectRequested = false;
    }

    @Override
    public void run() {
        while (!disconnectRequested) {
                String line;
                try {
                    line = readLine().trim();
                }
                catch (TimeoutException ex) {
                    continue;
                }
                catch (IOException e) {
                    logger.error("Read error", e);
                    return;
                }
                line = line.trim();
                logger.debug("<< " + line);
                responseQueue.offer(line);
    if (line.equals("ok") || line.startsWith("error: ")
        || line.startsWith("$VERSION =")) {
        // This is the end of processing for a command
//System.out.println("Line = " + line);
        synchronized (commandLock) {
            commandLock.notify();
        }
    }
}
}




}


2016-01-13 15:59 GMT, Jason von Nieda <notifications@github.com>:

**Comment by vonnieda** [comment]
@cri-s Please submit a *clean* pull request that doesn't break other code and features and I will consider it. Otherwise just keep this change in your fork. See https://github.com/openpnp/openpnp/blob/develop/CONTRIBUTING.md
