### ISSUE TITLE
Fiducial check for board bottom fails by specifying a large angle.

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#191]
See discussion at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openpnp/LPS0sW7ucKw/1SBMraJ_DAAJ
And video at https://www.youtube.com/watch?v=OkH-prmXbsY

I tested this using the pnp-test dataset with the image mirrored and got a similar result. The fiducials are located properly but then the angle gets set to 90ish when it should be zero. Suspect this is related to #148 and #186

**Comment by cri-s** [comment]
can you retest it with latest fix_coord applied. Because of opencv bug, i cannot test it without modification of code

**Comment by vonnieda** [comment]
Bottom fiducials were broken entirely until now. This should be fixed in 5276563869193d32d305256795b9fbc481667df7. I've tested with many different board setups and it's all working nicely. Please reopen if it doesn't solve the problem.
