### ISSUE TITLE
Security error on new machine interface rewrite.

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#193]
When STOP button on GUI is pressed, the driver MUST immediatly call setEnabled() on driver.
It cannot wait that home process or other queued move end, because the driver send Reset requests
to controller and this immediatly stops any motion or actor and report machine to safe state.
It cannot queued for future actions.

**Comment by vonnieda** [comment]
Good catch, you are correct. This is a bug.

**Comment by cri-s** [comment]
I have doing this, but as expected, test cases don't working anymore
and so i have deleted
test cases. How to fix it. Further clearing the Motion Queue don't work.
Annother point is with this motion queue. openpnp calc with
getLocation from nozzle, whatever. Now until move is not completed,
the calc is wrong. One example is enabling
driver , homing and then clicking to motion, as example nozzle, , or
anything that is relative
and use that for calc. Result: big crash.


   @SuppressWarnings("serial")
        private Action stopMachineAction = new AbstractAction("STOP") {
                @Override
                public void actionPerformed(ActionEvent arg0) {
                ReferenceMachine machine;
                        machine = (ReferenceMachine) configuration.getMachine();
                        setEnabled(false);
                        try {
                        machine.getDriver().setEnabled(false);
                        machine.setEnabled(false);
                        } catch(Exception e) {;}
                }
        };


2016-01-20 15:54 GMT, Jason von Nieda <notifications@github.com>:
