### ISSUE TITLE
Question about supporting Fixtures.

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#196]
This are fixtures on cnc and relative Gcode, http://server2.smithy.com/media/jpg/ficture%20offsets.jpg
Fixture can hold Panel or Boards, Panels contains one or more Boards.
Should Fixtures be supported or not ?
Further, it's possible to clearify  Board/Panel dimension related to bottom side.
On Coordinate discussion, if i remember correctly, the Pcb zero Coordinate need to be set explitly
between bottom and top assembly. My preference is to use the pcb dimension and add the width/height to the inverted coordinate. This needs boards dimension too,
and probalby fixtures, panels, fiducials don't integrate well on the UI design.

**Comment by vonnieda** [comment]
I think it would be fine to support fixtures.

On coordinates, I'll address this when I work on #166. I agree with you, I think width and height is better than the current system.
