### ISSUE TITLE
Setting the location of the part in tray feeder clears the Z value

### ISSUE THREAD

**Issue by anthonywebb** [openpnp/openpnp#209]
Say I need to tweak slightly the location of the part in my tray feeder by centering on the part by pressing the camera button, when I do this, instead of just setting the X and Y it also sets the Z to 0 so it needs to be rekeyed every time.  Would be nice to be able to make this fine adjustment without losing the Z value each time.  Does this make sense?  If you need me to record a little video I can.

**Comment by vonnieda** [comment]
Yep, makes sense.

The way this was intended to work was that if you have your camera and nozzle offsets set up correctly when you capture the position it should all just magically work. But that's not really the case in many builds for complex reasons.

So, yea, I think it's probably best if the capture camera button doesn't set Z in general.
