### ISSUE TITLE
Lens distortion calibration and undistort

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#226]
To better handle cameras using lenses with significant distortion, the support for OpenCV undistort needs to be finished up. There is already code for loading the lens parameters as created by http://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html but there is no built in way to capture the parameters.

* Add a camera calibration routine to the reference camera wizard. 
* Move the distortion config and undistort code from OpenCvCamera to ReferenceCamera. This feature should work with any camera, not just OpenCV based ones.
* The "Apply Calibration" checkbox in the wizard should turn distortion on and off live, not buffered through the Apply button, so that users can quickly see the difference.

Notes:
* There is a Java tutorial for camera calibration at http://opencv-java-tutorials.readthedocs.org/en/latest/09-camera-calibration.html that I have used before and was helpful.
* I have found using the circle detection system referenced in the original tutorial to be much faster than the chessboard version, but someone has told me it's less accurate. Need to see how much less accurate.

This is an important part of #104 since many bottom cams will use a fisheye lens to keep focal height down.

**Comment by vonnieda** [comment]
There is a good calibration pattern at http://nerian.com/support/resources/patterns/pattern-letter.pdf

**Comment by vonnieda** [comment]
Preliminary documentation at https://github.com/openpnp/openpnp/wiki/Camera-Lens-Calibration

**Comment by kaza007** [comment]
> There is a good calibration pattern at http://nerian.com/support/resources/patterns/pattern-letter.pdf

This link is broken. Here is an alternative [https://calib.io/pages/camera-calibration-pattern-generator](https://calib.io/pages/camera-calibration-pattern-generator)

**Comment by tobydickenson** [comment]
> > There is a good calibration pattern at http://nerian.com/support/resources/patterns/pattern-letter.pdf
> 
> This link is broken. Here is an alternative https://calib.io/pages/camera-calibration-pattern-generator

Hi @kaza007 .

This issue is from 2016, and it describes a method which has been entirely superseded. If you are calibrating vision on your pick and place machine, check out Issues&Solutions Camera Calibration and Advanced Camera Calibration.

But your comment does highlight that the description in the wiki for the old method is now misleading. I have edited a wiki to link to the new method.
