### ISSUE TITLE
Camera rotation crops frame

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#228]
In ReferenceCamera#transformImage we apply several user defined transformations, one of which is rotation. The current rotation system crops the frame, especially in cases where the aspect ratio is not 1:1. There is a TODO in the code to correct this, and there is a good example at: http://stackoverflow.com/questions/22041699/rotate-an-image-without-cropping-in-opencv-in-c

* Change the transformImage code so that it adjusts the size of the image before rotating so that the full rotated image will fit in the new frame.

**Comment by cri-s** [comment]
Simple roation on 90 degree interval:

// rotate 90º counter-clockwise
Core.flip(img.t(), img, 0);

// rotate 90º clockwise
Core.flip(img.t(), img, 1);

// rotate 180º 
Core.flip(img, img, -1);
