### ISSUE TITLE
Optimization: Use cvInitUndistortMap to precalculate the lens distortion map.

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#229]
From comments by @cri-s:

[19:21:26]  <cri>	you choosed to do the slow way for undistort.
[19:21:38]  <cri>	the correct way is:
[19:21:45]  <cri>	cvInitUndistortMap(intrinsic,distortion,mapx,mapy);
[19:21:50]  <cri>	on init and then
[19:22:00]  <cri>	cvRemap( t, image, mapx, mapy );

**Comment by richard-sim** [comment]
GitHub has automatically merged this commit/pull request into #256. I'd have rather it had kept them separate so issues could be addressed if necessary without holding up the previous pull request, but oh well.

**Comment by vonnieda** [comment]
Hey Richard, thank you *so* much for these pull requests! I am out of town
at the moment so I am behind on getting these merged, but please don't let
that hold you back. So far these look great and I will get them merged as
soon as I have some computer time.

**Comment by richard-sim** [comment]
No problem! The best way to learn a codebase is usually by tackling the open issues, so happy to keep going as I explore things.
