### ISSUE TITLE
Crash in Linux related to OpenCV

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#230]
Discussion: https://groups.google.com/d/msgid/openpnp/45263b64-8ecc-4091-9f81-d5d87dd02679%40googlegroups.com?utm_medium=email&utm_source=footer

This is probably due to Mats not being released properly. I think we saw this before in the OpenCVDriver. Seems to be Linux specific as it's not happening elsewhere.

More info may be in #125 and #87

**Comment by cri-s** [comment]
It seem releasing the Mat on new code fixes the issue.
mojalovaa1 test it's more.

**Comment by vonnieda** [comment]
@cri-s Okay, thanks. Please submit a pull request if you have a fix.

**Comment by cri-s** [comment]
If someone need the code in the meantime, just send e-mail.

**Comment by vonnieda** [comment]
Can you just post the code here?

**Comment by vonnieda** [comment]
No further reports of this, closing. Please reopen if there is still an issue.

**Comment by cri-s** [comment]
It still happen on *buntu LTS. On not LTS it works.  As LTS is the
preferred version, nu.pattern need be commented out using external linking.
