### ISSUE TITLE
Zeva Retrofit Images (Ignore)

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#240]

**Comment by dandumit** [comment]
![endoscope and mounting adaptor](https://cloud.githubusercontent.com/assets/670552/13505265/1d5e9446-e181-11e5-8d32-328604c4e129.jpg)
![nozzle and camera impl](https://cloud.githubusercontent.com/assets/670552/13505269/2492ec58-e181-11e5-980e-b4803dbe5795.jpg)
