### ISSUE TITLE
Nozzle Tip Changer does not show currently loaded Nozzle Tip

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#247]
Discussion in https://groups.google.com/d/msgid/openpnp/91d61fc4-38d8-4c96-869c-be3997811d56%40googlegroups.com?utm_medium=email&utm_source=footer

Currently OpenPnP remembers which nozzle tip is loaded but does not allow the user to see this or to modify it.

Changes should include:
- [x] Show the currently loaded nozzle tip, if any.
- [x] Allow the user to manually set the currently loaded nozzle tip.

**Comment by sp-apertus** [comment]
I added the display of the currently attached nozzle here:
https://github.com/openpnp/openpnp/pull/416

**Comment by vonnieda** [comment]
You can now load a nozzle tip manually using the load/unload buttons.
