### ISSUE TITLE
Improve icon design language

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#263]
When the current icon set was first designed I had planned to make it such that any icon that would result in the machine moving (which is potentially dangerous) would include red as it's primary color (to indicate danger) and no other icon would include red. I've drifted from this since then and I need to update the current icons and replace any that don't fit that standard. The various feed buttons and the nozzle change buttons come immediately to mind.

**Comment by issus** [comment]
I'll take this one on, I'll hopefully get time to start looking at it next week.

**Comment by vonnieda** [comment]
I'm closing old issues that have seen little interest. PRs welcome.
