### ISSUE TITLE
Window unusably small on 2560x1600 Retina Display

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#268]
See thread at: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openpnp/tJDUyj3xt_Y/x_AfiWitKwAJ

<img width="1280" alt="screen shot 2016-05-03 at 17 40 48" src="https://cloud.githubusercontent.com/assets/1182323/14991022/540a0954-1114-11e6-85bb-ed4203b8b2b0.png">

I'm not exactly sure what the right way to fix this is. Going to require some research. If anyone has any experience with Java and Retina displays, please speak up.

Current thinking on a fix for this:
- Reduce wasted whitespace in jog controls and DROs.
- Allow user to choose font size to reduce the vertical height of the UI.

**Comment by vonnieda** [comment]
Some useful links on this subject:
http://bulenkov.com/2013/06/23/retina-support-in-oracle-jdk-1-7/
http://stefan.budeanu.com/blog/?p=88
http://stackoverflow.com/questions/20315371/retina-compatible-jlabel-image

**Comment by vonnieda** [comment]
Honing in on setting font size:
http://stackoverflow.com/questions/7434845/setting-the-default-font-of-swing-program

**Comment by richard-sim** [comment]
Perhaps the Machine Controls panel needs to have a vertical scrollbar, so all the controls will remain accessible (but may require a bit of scrolling) while the bottom panel can be any height. As you've found, technically the behaviour of Java is correct as-is; just the window layout doesn't work for low-res screens (which that Retina resolution essentially is!).

Doing this, the minimum height of the Machine Controls panel can be removed, and the user can expand the bottom panel substantially even on low-resolution screens.

**Comment by vonnieda** [comment]
Thanks @richard-sim, this is helpful. I think adding a scrollbar would be a good short term solution. Long term I'd like the window layout to work a little better for these screens.

**Comment by tracklogic** [comment]
Scrollbar also sounds sensible incase user tries to run on a tiny 10" Netbook!

**Comment by vonnieda** [comment]
With the changes in https://github.com/openpnp/openpnp/blob/develop/CHANGES.md#2016-12-20 I think we can call this one done.
