### ISSUE TITLE
Solder Paste Dispense Broken After JobProcessor Refactor

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#271]
Due to time constraints leading up to Maker Faire I am releasing #265 with solder paste dispensing broken. Users can use the master branch instead of develop until this is fixed.

**Comment by vonnieda** [comment]
Note to self: Make sure to update http://openpnp.org/downloads/ when this is resolved.

**Comment by tracklogic** [comment]
Fixed paste dispense on my branch

**Comment by vonnieda** [comment]
Fixed in previous PR.
