### ISSUE TITLE
GcodeDriver fails to update DROs after homing.

### ISSUE THREAD

**Issue by psykhon** [openpnp/openpnp#273]
The software wont set its DROs to zero after homing

**Comment by psykhon** [comment]
On a further review, seems like the Parking button is sending the noozle offset to the machine instead of the Head 0. Dont know if this is a misconfiguration of mine or a real bug

**Comment by vonnieda** [comment]
This is a bug in the GcodeDriver. It needs to send a head movement update after homing.

@psykhon Park moves the selected nozzle to the Park location, which you can define in Machine Setup -> ReferenceMachine.

**Comment by vonnieda** [comment]
Added a new issue for the Park specific part of this: https://github.com/openpnp/openpnp/issues/279

**Comment by vonnieda** [comment]
This was fixed quite a while back in the ReferenceHead.
