### ISSUE TITLE
Visual Homing

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#274]
To increase the accuracy of home location, we should have visual homing after mechanical homing.

See discussion at https://groups.google.com/d/msgid/openpnp/ecc9b101-e26c-4a60-8ec1-17d9cba83958%40googlegroups.com?utm_medium=email&utm_source=footer

Status: Feature is complete, needs documentation and UI.

**Comment by mrandt** [comment]
As you're probably aware of, this is solved in LitePlacer software by putting a "fiducial" marker on the table, which the camera homes onto after mechanical homing. 

I think it would be beneficial if user could provide a custom video processing pipeline for the detection of this mark so users would have flexibility in choice of black on white, white on black, hole in metal, etc. depending on the table top surface.

**Comment by tracklogic** [comment]
Implemented on branch, fiducial homing, will initiate a pull request to get into main

**Comment by vonnieda** [comment]
@tracklogic I just noticed that this throws an exception if no homing fiducial is defined. I thought it would just silently ignore it. I'm changing the code now so that it does, since this breaks anyone not using fiducial homing. Did you intend for this, or was there some other plan?

**Comment by vonnieda** [comment]
@tracklogic Fixed above in https://github.com/openpnp/openpnp/commit/833987580c373ac8d8178ffba37924cf5ee7af0c, please let me know if you have any thoughts on whether this should act differently.

**Comment by tracklogic** [comment]
Hi Jason

The intention was if none was defined, it wouldn't do the visual fiducial
homing - my apologies!

Matt

**Comment by vonnieda** [comment]
Fixed in previous PR.

**Comment by vonnieda** [comment]
Reopening until this feature is documented.

**Comment by vonnieda** [comment]
Documented at https://github.com/openpnp/openpnp/wiki/GcodeDriver#visual-homing
