### ISSUE TITLE
Reset feed count

### ISSUE THREAD

**Issue by psykhon** [openpnp/openpnp#276]
A very small but usefull feature, a button to reset Feed count on a tray feeder, better than to put 0 in the textbox and hit apply

**Comment by psykhon** [comment]
the currently "reset" button should be renamed "Cancel"

**Comment by vonnieda** [comment]
Agreed. We have this in the Strip Feeder, it should be added to the Tray Feeder as well.

**Comment by vonnieda** [comment]
Resolved by #322
