### ISSUE TITLE
Stopping a job should stop the job as soon as possible

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#278]
With the new JobProcessor refactor the Stop button is less useful than it was. It now signals the JobProcessor to stop after the current cycle finishes, and this may mean quite a few more operations.

Instead, the Stop button should stop the job immediately (after the current operation completes) and then perform the cleanup cycle.

**Comment by pk7639** [comment]
The same applies to the pause function. We commonly use pause on other machines to freeze the job  to trouble shoot things like a pick position error. At present the job processor will continue through to the end of the place operation before stopping.

**Comment by vonnieda** [comment]
This seems to be due to FSM processing in a while loop, and it seems like that should not be the case since already call next() in a loop, but removing it breaks the job at the cleanup stage. Still investigating.

**Comment by vonnieda** [comment]
The core issue is that the FSM loops while there is a nextMessage. I think the nextMessages are supposed to group "invisible" steps so it doesn't look like clicking step did nothing.
