### ISSUE TITLE
Park Improvements

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#279]
Originally from #273, some improvements to the Park system are needed:
- Park should be a method on head rather than being a bunch of copypasted code everywhere. One thing to consider is that this would break the UI which allows parking of XY, C or Z. Maybe the method would take those as booleans.
- Park should always park at the same location by subtracting the offsets of the object it moves. Due to the driver API we can't just send an absolute coordinate, but we can pre-subtract the head offsets from the default nozzle, for instance, and send that.

**Comment by cri-s** [comment]
Take care for machines having more then one head, and for that park can issue a exception if the move is not allowed because of position from other head.

**Comment by vonnieda** [comment]
@cri-s Do you know of any machines currently using OpenPnP with more than one head?
