### ISSUE TITLE
Pendant support for manual head operation

### ISSUE THREAD

**Issue by TomKeddie** [openpnp/openpnp#281]
I am wondering if OpenPNP supports MPG pendants ? I am thinking it would be helpful for setup just like it is on a CNC mill .....

(Submitted on behalf of Peter Betz)

**Comment by vonnieda** [comment]
Discussion at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openpnp/hFp_RPG6tks/9Lbl3mtZAQAJ

As noted in the discussion, pendants are not currently supported.

**Comment by vonnieda** [comment]
Per the discussion, I think we'd be best off handling this outside of OpenPnP using either keyboard emulation hardware or software. We may need to add a couple new shortcuts to handle things like absolute jog increments. The existing shortcuts are listed at https://github.com/openpnp/openpnp/wiki/User-Manual#shortcuts.

**Comment by TomKeddie** [comment]
I have one of the joystick shields shown below that I intend to hook up to an Arduino Leonardo and do keyboard emulation - there's enough controls for X, Y and Z plus step size change.  There's no indication of step size unfortunately, might hack in some leds.

![Shield](http://g03.a.alicdn.com/kf/HTB1jOcBIpXXXXa1XVXXq6xXFXXXS/Gamepads-JoyStick-Keypad-Shield-PS2-for-Arduino-nRF24L01-Nk-5110-LCD-I2C.jpg)

**Comment by vonnieda** [comment]
Based on discussion, it was decided to do this outside of OpenPnP via keyboard controls.
