### ISSUE TITLE
error saving config

### ISSUE THREAD

**Issue by psykhon** [openpnp/openpnp#284]
[https://drive.google.com/file/d/0B-ZJ2SAKAbyRMEhTTGpnODB4Ums/view?usp=sharing](url)

**Comment by vonnieda** [comment]
@psykhon This url is not valid. If it's for a screenshot or an image can you just drag and drop it into a comment here please?

**Comment by vonnieda** [comment]
@psykhon Nevermind previous comment, got the image.

![2016-06-09 1](https://cloud.githubusercontent.com/assets/1182323/15949278/293a48ce-2e5b-11e6-89a5-781a3cf6f3f9.png)

**Comment by vonnieda** [comment]
@psykhon It looks like you have the bottom vision pipeline for either a part or for the default and you've left the prefix blank on an ImageWriteDebug stage. If you find the one you modified you can just put any string there, or delete that stage and it should save.
