### ISSUE TITLE
PartAlignment API needs additional fields to do jaw based centering.

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#286]
To do jaw based centering the PartAlignment API needs BoardLocation and Placement data, and it needs a way to tell the JobProcessor not to rotate the part any further.

More information in this discussion: https://groups.google.com/d/msg/openpnp/ByDbMIFBMGU/43ZT-Ud3KgAJ

This is directly related to #264 and specifically related to the "Final Rotation" concept mentioned in that issue.

**Comment by tracklogic** [comment]
Implemented on my branch

**Comment by vonnieda** [comment]
Fixed in #311, thanks @tracklogic!
