### ISSUE TITLE
vision pipeline, standalone

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#296]
What is the command / build option for the standalone vision pipeline ?

**Comment by vonnieda** [comment]
@cri-s org.openpnp.vision.pipeline.ui.StandaloneEditor

**Comment by cri-s** [comment]
Instead of
 java -DconfigDir=cfg -jar target/openpnp-gui-0.0.1-alpha-SNAPSHOT.jar
 
 java -DconfigDir=cfg -cp target/openpnp-gui-0.0.1-alpha-SNAPSHOT.jar org.openpnp.vision.pipeline.ui.StandaloneEditor

Thanks.
