### ISSUE TITLE
screen space issue

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#300]
On linux at least, the space for configuration is extremly small after the change to integrate the 
jogging key into the gui.
original: https://s31.postimg.org/jhwwi32rf/org.png
drawing: https://s32.postimg.org/sqrq6k86d/new.png
other: https://s32.postimg.org/jdx41vlcl/other.png  using checkbox inside view/settings.

i don't exactly know the solution, for configuration settings, the space is really tiny and it's difficult to
setup.

**Comment by vonnieda** [comment]
Same issue as #268, we need to come up with a solution for screens with limited vertical resolution.
