### ISSUE TITLE
Tray Feeder Count Not Updating

### ISSUE THREAD

**Issue by jjpickett** [openpnp/openpnp#321]
**Summary:** The Tray Feeders feed count is not being updated when performing a feed and pick.

**Steps:**
1. Go to the bottom panel and select the tab Feeders
2. Create and set up a new Tray Feeder
3. Give the Tray Count some numbers (I used 1 and 3)
4. Select the "Perform a feed and pick on the selected feeder" button.

**Expected Result:** The Feed Count will update its number on the screen.

**Actual Result:** Notice that the Feed Count will display the same number as before.

**Note:** The process will still operate properly with the correct numbers. The issue is that this is not being displayed to the user.

[Video of Tray Feed Count Issue]
(https://github.com/openpnp/openpnp/files/411648/Feed.Count.Bug.Video.zip)

**Comment by vonnieda** [comment]
See ReferenceStripFeederConfigurationWizard for how to set up the bindings to make this work right.

**Comment by vonnieda** [comment]
Fixed by #323
