### ISSUE TITLE
Configure Camera Properties through machine XML

### ISSUE THREAD

**Issue by issus** [openpnp/openpnp#328]
Camera properties should be configurable through the machine XML. A list of OpenCV property names and values should be able to be user configured, such as CAP_PROP_EXPOSURE for manually setting the exposure.

When the camera is initialised, these will then be iterated through, and sent to the camera with the .set(propId, value) method: http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture-set
A list of the property types is listed in the link above. Not all the parameters are supported by all cameras.

Further reading on manual exposure for the ELP cameras:
http://www.makehardware.com/2016/06/21/manual-exposure-vs-auto-exposure-for-elp-2-mp-usb-camera/
http://xn--1-2fa.fr/?p=110
http://answers.opencv.org/question/27182/fully-manual-web-cam/

As a note, .set(CAP_PROP_SETTINGS,1); should display the operating systems configuration window for the camera, which will show which features are supported by the cameras, as it appears to disable properties that are unsupported.

**Comment by vonnieda** [comment]
Great idea!

**Comment by vonnieda** [comment]
For reference, in OpenCV 2.4.13 the following capture drivers mention exposure:
> grep CV_CAP_PROP_EXPOSURE -rl *
cap_android.cpp
cap_dc1394_v2.cpp
cap_dshow.cpp
cap_giganetix.cpp
cap_intelperc.cpp
cap_libv4l.cpp
cap_pvapi.cpp
cap_v4l.cpp
cap_ximea.cpp

In OpenCV 3.2.0:
> grep CV_CAP_PROP_EXPOSURE -rl *
cap_aravis.cpp
cap_dc1394_v2.cpp
cap_dshow.cpp
cap_giganetix.cpp
cap_gphoto2.cpp
cap_intelperc.cpp
cap_libv4l.cpp
cap_pvapi.cpp
cap_v4l.cpp
cap_ximea.cpp
