### ISSUE TITLE
Make Logging Easier to Configure

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#333]
The logging system has a couple limitations that are starting to become serious problems:

* You must edit log4j.properties and restart OpenPnP to make changes to logging.
* The log4j configuration is complex and difficult to understand for non-programmers.
* The logging window #288 is at the mercy of the log4j configuration.
* Logging categories are too granular and make it hard to get all the information you need.

I think we need to make some improvements to logging in general:

* Replace log4j with something much simpler and which can be configured at runtime programmatically.
* Create a number of basic categories and change all existing loggers to use them. For example: driver, machine, vision, job, etc. These should be fairly general.
* Make the logging window #288 be the controller for the logging configuration. Add UI for setting category log levels and make it easy to override so that you can turn on full system tracing with one click.

In general, we want to make it very easy for users to turn on increased logging since this is usually required for submitting a bug report or help request. In fact, we may want to get rid of categories altogether and just use a single log level across the board as many UNIX programs do. e.g. -v, -vv.

This is related to #83 in that we need to be able to readily enable and collect logs.

**Comment by cri-s** [comment]
When I was not able to configure it for the logging console on GUI,
I have asked you too, I simple switched to http://www.tinylog.org/ 
That worked without problem , finer configurability and some other advantage for the casual user like me.

**Comment by vonnieda** [comment]
Thanks Cri, tinylog looks nice.

**Comment by vonnieda** [comment]
tinylog does away with categories and per logger configuration entirely, which might be perfect for what we want to do. Instead of having configuration complexity, we could add some basic filtering to the logging window to make it possible for users to filter out things that annoy them.

**Comment by vonnieda** [comment]
Mostly implemented in the feature/logging branch. Just need to remove the temporary wrapper I added.
