### ISSUE TITLE
Tests run slow

### ISSUE THREAD

**Issue by pfried** [openpnp/openpnp#342]
The tests should run much faster, but as the Simulated Driver does a sleep it takes very long to complete.

An idea: Set the sleeptime in a variable and change that when running unit tests.

**Comment by vonnieda** [comment]
Good catch. The major delay has been removed but I think there are probably still camera delays, and maybe pick, place and feed delays. The biggest time consumer for the tests is the fiducial checks, and I think that is due to camera settle time. Definitely worth looking into.

**Comment by vonnieda** [comment]
Fixed in https://github.com/openpnp/openpnp/commit/ad35958f40f65416b8136536049137c2ef49c146
