### ISSUE TITLE
Actuator UI Improvements

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#343]
Discussion in: https://groups.google.com/d/msgid/openpnp/CA%2BQw0jwW%3D8dO5jNV37mip0Lp9OeWa2LkAw8sh-JCYM0ALw4hfQ%40mail.gmail.com?utm_medium=email&utm_source=footer
- Need a way to trigger both boolean and double actuators.
- Need to be able to see the state of the boolean actuator better, or alternately, just be able to send a fixed true or false.

**Comment by michalsok** [comment]
I am new to OpenPNP but I have noticed that Actuators are named and have an ID so there is an index / array of them of some sort. (or could easily be populated) 
Why not make the list of defined actuators available as a drop-down selector in places where they are selected like drag feeders, auto-feeders etc. Right now you have to type in the actuator name.
Thank you,

**Comment by vonnieda** [comment]
@michalsok Good idea!

**Comment by markmaker** [comment]
Some of this seems to already have been done in the meant-time:

Actuators are now drop-downs everywhere, as requested in the comment here. 

From the linked discussion, Jason said:
> Right now there's no way to tell if an actuator takes a boolean or double argument. It may make sense to add a flag that says which is which, and then we can have the UI react to that: checkbox for boolean actuators and a textfield for entering a value for double ones. 

#1095 added actuators types and fulfills this. 

![Actuator Types](https://user-images.githubusercontent.com/9963310/115995238-c0247380-a5da-11eb-8412-e4096dbe99b4.png)

In addition, **Default ON** and **Default OFF** values that can now be defined for non-boolean actuators for quick switching between two predefined states. Profile type actuators can provide selectable options.
