### ISSUE TITLE
Implement continuous jog

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#35]
Create an interface and implement it for continuous jog. This should be an optional interface that drivers can implement. It should be something like jog(doublex, double y, double z, double c) with positive numbers jogging positive direction, negative the opposite and 0 stopped and with the numbers representing the same 0-1 percentage as move() does.

When jog is called with any non-zero value the machine should start jogging and it should not stop until jog is called with all zero values. It should also be possible to start jogging in one axis and then add an additional axis by calling jog a second time with a second non-zero axis.

**Comment by cri-s** [comment]
If you want, i can do it.

**Comment by vonnieda** [comment]
Not likely to ever happen and focusing more on camera jog now anyway. Closing.
