### ISSUE TITLE
GCode driver timeout not configurable from GUI

### ISSUE THREAD

**Issue by kinnison** [openpnp/openpnp#387]
Jason's comments:

The Gcode Driver Timeout setting should be configurable from the GUI, not just in machine.xml. In addition, there are several other simple fields that should be added:

* units
* maxFeedRate
* timeoutMilliseconds
* connectWaitTimeMilliseconds

Original report below:

Hi,

I am part of a team working on a PnP machine using OpenPNP.  We are using a Smoothie board as our GCode interface, and in order to validate our hardware build, we're running the machine quite slowly while we verify performance and precision characteristics.  Sadly this means that OpenPNP often times out because 5 seconds is not long enough. While I *can* build a local version of OpenPNP with the timeout set higher, it would be awesome if it were a configurable item which could be set in machine.xml.

What do you think?

Daniel.

**Comment by vonnieda** [comment]
Hi @kinnison, are you referring to the movement timeout? This is set with the attribute timeout-milliseconds.  You can see it set to 5000 here:

```
<driver class="org.openpnp.machine.reference.driver.GcodeDriver" port-name="/dev/tty.usbmodem1411" baud="115200" flow-control="Off" data-bits="Eight" stop-bits="One" parity="None" set-dtr="false" set-rts="false" units="Millimeters" max-feed-rate="1000" timeout-milliseconds="5000" connect-wait-time-milliseconds="1000">
```

But you can change it to any value you like.

**Comment by kinnison** [comment]
Aah I failed to see it in the GUI, should I quit openpnp and edit the XML directly for those?

**Comment by vonnieda** [comment]
@kinnison Yes, for now. I'll update this issue to reflect that we should add it to the GUI.

**Comment by kinnison** [comment]
I have edited the XML and can confirm that things are now behaving as I would expect.  Yes it would be nice if the GUI could configure timeout, connect-timeout, and feed-rate then :-D

**Comment by vonnieda** [comment]
Merry Christmas! https://github.com/openpnp/openpnp/commit/6ce5c9657d6d015bf01e9b1eb7c4c8945d8c3942
