### ISSUE TITLE
Placement location calculation error on board bottom when using non-corner board origins

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#403]
1. Create a board that uses a non-corner board origin. In the test case it was near center.
2. Load board into job, select Bottom and set origin. Leave width = 0.
3. Use position camera button to move to a placement. It should position correctly.
4. Set width of board.
5. Use position camera button to move to the same placement. It will position incorrectly.

Discovered when debugging an issue @sp-apertus had.

Video showing the problem: https://www.youtube.com/watch?v=ed6nXiZQ4VA

# Workaround

To work around the issue, simply set board width to 0.

**Comment by sp-apertus** [comment]
Actually it should position correctly for the top side (with and without width set), but as soon as you switch to bottom side it will position incorrectly.

**Comment by vonnieda** [comment]
@sp-apertus Yes, this issue only affects bottom. Bottom is handled differently than top since everything is flipped and that extra handling is where the bug is.

**Comment by vonnieda** [comment]
Note to self, considering removing "New Method" entirely to simplify UI and code: https://groups.google.com/d/msg/openpnp/054jwfjeePY/g-WVQijSAQAJ

Also, an idea: Rendering the placements over the board and having a similar "grab two points" UI to the manual PnP tool would make it very easy to set board origin.

**Comment by vonnieda** [comment]
Closing as not a bug: If width is being used on a board bottom the origin needs to be set to the point that is the negative of the width.
