### ISSUE TITLE
Provide add/remove buttons for paste dispensers

### ISSUE THREAD

**Issue by dzach** [openpnp/openpnp#404]
I haven't found a way to add/remove a paste dispenser by using the GUI.
Can it be done only by editing _machine.xml_?
.

**Comment by vonnieda** [comment]
@dzach Yes, currently only through machine.xml. The dispense functionality is extremely young and has not seen much development. It needs a lot of work.

**Comment by vonnieda** [comment]
I'll accept a PR for dispense if it's complete and working, but until then I am closing dispense issues since we've decided to deprecate this feature.
