### ISSUE TITLE
Wiki Image Upload 

### ISSUE THREAD

**Issue by sp-apertus** [openpnp/openpnp#420]
![nozzletipchanger](https://cloud.githubusercontent.com/assets/4028409/22084570/eced8ab8-ddd0-11e6-9e53-a3dcf60e647b.JPG)

**Comment by vonnieda** [comment]
@sp-apertus If you close this are you still able to comment? I haven't tested that. I like these image upload issues to remain closed, if possible, so they don't clutter the work list.

**Comment by sp-apertus** [comment]
works !

**Comment by vonnieda** [comment]
Excellent, thanks!

**Comment by sp-apertus** [comment]
![non-suqareness-corraction](https://cloud.githubusercontent.com/assets/4028409/22855587/2b82cac6-f083-11e6-98f5-cd4471acb922.jpg)

**Comment by sp-apertus** [comment]
![non-suqareness-corraction](https://cloud.githubusercontent.com/assets/4028409/22855667/5b24e57e-f084-11e6-8bab-6e7d2c6e32dc.jpg)

**Comment by sp-apertus** [comment]
![bottom-vision-off-center](https://user-images.githubusercontent.com/4028409/40356160-9512c506-5db8-11e8-8e60-9b4b9cb29d8c.jpg)

**Comment by sp-apertus** [comment]
![chip-bv-error](https://user-images.githubusercontent.com/4028409/40357049-463f03f6-5dbb-11e8-8aa5-d36250614689.jpg)
