### ISSUE TITLE
Regression: mountsmd.ulp importer no longer imports DemoBoard v2 sample

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#424]
Noted by LA3PNA on IRC, the mountsmd.ulp importer is throwing a "No match found" exception when trying to import the DemoBoard v2 sample. 

Note: Fixing this will be a good opportunity to add unit tests for the importers.

**Comment by la3pna** [comment]
It seems to throw the error for any .mnt file.  Assume this is a problem with the importer, and not the file.
