### ISSUE TITLE
ReferenceSlotAutoFeeder Bugs

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#427]
Two bugs identified by Glen English:

* [ ] Sometimes goes into a spin loop sucking up CPU. Seems to happen when adding multiple slots, or possibly clicking into the slot name, or possibly scrolling through them rapidly.
    * Note: Reproduced this by adding four slots, clicking one row in table and then using keyboard to move up and down a few times. After a few movements CPU usage shot up and stuck.
* [x] Slot name gets corrupted if you double click it multiple times. This is due to how we override the name to include the feeder. Need to add a table cell renderer that shows the combined value but make sure when editing we only edit the actual name.

And some improvements:
* [x] Change the ID prefix for slot feeders to something other than FDR. Maybe SLF.
* [x] Change the ID prefix for slots to SLOT.

**Comment by vonnieda** [comment]
Spin loop error is due to Configuration.get().getBus().post(new FeederSelectedEvent(feeder)); call. Still determining why.

**Comment by vonnieda** [comment]
Looks like it's a loop in FeedersPanel.feederSelected, which I suppose makes sense.

**Comment by glenenglishgithub** [comment]
OK,  I concur that all seems to be bahaving itself now, thanks Jason !
