### ISSUE TITLE
Should Machine Setup tree start up expanded?

### ISSUE THREAD

**Issue by dzach** [openpnp/openpnp#439]
I just deleted most of the example feeders and all of my test feeders in the `Machine Setup` tree,  because I got tired of collapsing it in order to make space for the setup panels at the bottom of the right pane.

Wouldn't it be nice to have a checkbox that expanded / collapsed the tree according to the situation in hand? Like this perhaps?

![machinesetup-exp](https://cloud.githubusercontent.com/assets/1109829/22529607/c1c05224-e8e0-11e6-92d0-aaaf2b000185.png)

or, collapsed to the first level:

![machinesetup-coll](https://cloud.githubusercontent.com/assets/1109829/22529629/dd0843d4-e8e0-11e6-9b38-667069e89e24.png)

If you like the idea, I have code ready to be pushed.

Cheers!
Dimitrios

**Comment by vonnieda** [comment]
Looks good to me, although just so I know we're on the same page... you shouldn't have to collapse it to see the setup panels. You can scroll it. This is how mine looks normally:

![screen shot 2017-02-01 at 4 49 47 pm](https://cloud.githubusercontent.com/assets/1182323/22529803/78c2dbc4-e89e-11e6-9cc7-e9fe08bd24fa.png)

**Comment by dzach** [comment]
Ehm, I meant I don't want to keep enlarging and shrinking the top and the bottom panes to find what I need in each one of them. What I'd like is to have one branch of the tree open, the one I'm working on, but not have to go through all the leaves and collapse them manually. Having all expanded at start up is overwhelming.

**Comment by vonnieda** [comment]
Fair enough, PR when ready :)

**Comment by vonnieda** [comment]
Fixed in #440, thank you for the nice improvement @dzach!
