### ISSUE TITLE
possible typo ... Feedrate letter F at unexected position for move_to_command

### ISSUE THREAD

**Issue by ldpgh** [openpnp/openpnp#452]
Moveto command on the wiki pages [machine.xml](https://github.com/openpnp/openpnp/wiki/GcodeDriver%3A-Example-Configurations) respective [GcodeDriver: Command Reference, move_to_command example](https://github.com/openpnp/openpnp/wiki/GcodeDriver:-Command-Reference) specify letter 'F' for Feedrate different to [ GCode](http://reprap.org/wiki/G_code#G0_.26_G1:_Move)... maybe a typo.

F{FeedRate:%.0f}  ... vs. ...  {FeedRate:F%.0f}
^. . . . . . . . . . . . . . . . . . . . . . . . . . . . .^

**Comment by vonnieda** [comment]
This is by design. By having the F outside of the variable it will never be omitted from the command. In reality, it wouldn't matter because this variable is always supplied, but it works correctly this way.
