### ISSUE TITLE
import board named CSV crash if CSV is opened in excel

### ISSUE THREAD

**Issue by Misfittech** [openpnp/openpnp#460]
import board named CSV crash if CSV is opened in excel

Cannot create file "C:\Users\TSTERN\Google Drive\projects\Stepper_feedback\hardware\SmartStepper_NEMA23_A5995\Project Outputs for SmartStepper_NEMA23_A5995\Pick Place for SmartStepper_NEMA23_A5995.csv". The process cannot access the file because it is being used by another process

Exception Occurred In  GenerateReport

**Comment by Misfittech** [comment]
Might not have been an openpnp issue

**Comment by cri-s** [comment]
This is because excel uses ""foo""  instead of "foo" .
Never less I have seen some very wrong CSV from excel, where refid have one opening " without closing " and the rest have double " for opening and closing. 
If your  need it reopen the issue and I add it.
