### ISSUE TITLE
Manual pick with incorrect NozzleTip should warn user

### ISSUE THREAD

**Issue by trampas** [openpnp/openpnp#472]
In the parts tab if you click pick part with left nozzle active it will try and pick part even if nozzle tip does not work with that part. OpenPnP should ask if this is really what you wanted to do in this case before trying.

**Comment by vonnieda** [comment]
Note, this is an issue in the Feeders tab as well.

**Comment by markmaker** [comment]
This was handled by #942. It even changes the nozzle tip automatically, if required and enabled.
