### ISSUE TITLE
Test Alignment Z move as X and Y moves

### ISSUE THREAD

**Issue by Misfittech** [openpnp/openpnp#477]
If I got to parts tab and pick a part from strip feeder then click "check Alignment" button the Z axis moves at the same time the X and Y are moving.  This could lead to a nozzle crash, instead the Z should stay at safe height until it reaches the X and Y location then lower.

**Comment by Misfittech** [comment]
It appears it works correctly if vision is enabled, but does not if vision is not enabled.

**Comment by vonnieda** [comment]
Good catch, fixed in commit above.
