### ISSUE TITLE
pipeline editor usability increase

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#499]
Some stages have comment embedded inside for the user settable values. It would be helpful if this are visible as tooltips.

**Comment by vonnieda** [comment]
The comments are already visible in the properties setter if you click the info box icon:

![screen shot 2017-04-01 at 8 47 07 pm](https://cloud.githubusercontent.com/assets/1182323/24583792/63d24658-171c-11e7-987c-51764955eab3.png)

You have to click this icon:
![screen shot 2017-04-01 at 8 47 24 pm](https://cloud.githubusercontent.com/assets/1182323/24583795/6e14a2e6-171c-11e7-9e46-44bbfd2fab6c.png)
