### ISSUE TITLE
Nozzle Changer Movement Speed

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#506]
It should be possible to set the speed of movements for the nozzle changer.

Discussion at https://groups.google.com/d/msgid/openpnp/1b3f15c6-2213-4d42-92a7-efdcc9a1f04a%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by lilltroll77** [comment]
Is this now also solved with the latest build?

**Comment by vonnieda** [comment]
@lilltroll77 Yes, indeed! Closing.

**Comment by NathanielHorne** [comment]
How / where was it fixed? I'm running into this issue and I'm not sure where to go.
