### ISSUE TITLE
Squareness Compensation is ignored when coordinate doesn't change

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#529]
Due to how GcodeDriver skips axes that aren't involved in a move, if a movement happens in the axis that does not affect non-squareness compensation, it's possible the compensation will not be applied in repeated moves to only one axis.

**Comment by vonnieda** [comment]
This should fix it. Need to test: 
![screen shot 2017-04-19 at 9 09 30 am](https://cloud.githubusercontent.com/assets/1182323/25184401/f2a8004a-24df-11e7-8f6e-f95f3bc00635.png)

**Comment by vonnieda** [comment]
Note: This probably breaks backlash compensation, too.

**Comment by vonnieda** [comment]
Another note: This likely means that the position report code is broken, since it doesn't subtract the non-squareness value. Probably need to think about refactoring all of this to maintain controller state and internal state coordinates.

**Comment by vonnieda** [comment]
@sadman suggested the following fix: https://github.com/sadman/openpnp/commit/f8d1a9df8ecc39ec69dc60f5f90c707ef6f52b6e

**Comment by aauer1** [comment]
I also submitted a pull request for this issue #533 . It solves the same issue. Sorry for the duplicate.

**Comment by vonnieda** [comment]
This is now fixed. I used the basic idea in #533 but refactored the code to be easier to understand and also handle an edge case that was not handled in the original PR. Please test and report back.
