### ISSUE TITLE
Add a way to test pick a part from a feeder

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#53]
User suggests adding a button that will do a feed / pick cycle from a particular feeder and place it at a test location. The primary feature is just to make sure that a feeder is feeding and picking correctly without having to set up a job.

**Comment by FlyingLotus1983** [comment]
If this were left until after OpenPnP 1.0, it would be easy to implement this in a task-based approach.  Meaning, if you've got a front panel screen with a few choices (setup, pick and place, feeder setup, etc), then you could put this in a separate module for feeder setup.. In the meantime, I think doing it from a separate job.xml is perfectly acceptable.

**Comment by vonnieda** [comment]
This, along with a few other options were added a little while back.
