### ISSUE TITLE
Opening a new job when the current one is paused doesn't stop the job

### ISSUE THREAD

**Issue by sadman** [openpnp/openpnp#532]
1. Load a job with error
2. Start it, choose "Pause Job" in Job Error dialog
3. Load a new job
4. Start it, it will produce error from the previous job

**Comment by vonnieda** [comment]
Should be fixed, at the latest, as part of #280

**Comment by vonnieda** [comment]
I think it might make sense to fix this by implementing #516

**Comment by vonnieda** [comment]
Fixed by adding an error dialog if you try to open, new, import and open recent job. When #516 is fixed I'd like this to be fixed the same way, by just disabling the menu items. That's going to require a pretty large review of the action system though.
