### ISSUE TITLE
Question: How do I run the StandaloneEditor for the opencv pipeline?

### ISSUE THREAD

**Issue by dzach** [openpnp/openpnp#535]
Running it like this, gives me an error:
```
mvn package
java -cp target/openpnp-gui-0.0.1-alpha-SNAPSHOT.jar src/main/java/org/openpnp/vision/pipeline/ui/StandaloneEditor.java
Error: Could not find or load main class src.main.java.org.openpnp.vision.pipeline.ui.StandaloneEditor.java

```

**Comment by vonnieda** [comment]
Like this:
`java -cp target/openpnp-gui-0.0.1-alpha-SNAPSHOT.jar org.openpnp.vision.pipeline.ui.StandaloneEditor`

I'll add it to the Wiki.

**Comment by dzach** [comment]
Duh! I tried this and every other combination, but missed to omit the extension.

Thanks! That makes testing a lot easier.
