### ISSUE TITLE
pipeline editor not update description

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#561]
# Problem Report
## Describe the Issue
on pipeline editor description is not updated but remain cached.
Example of code used:

	public String getDescription() { return getDescription(null); }

    public String getDescription(String id) {
		if(mode==Mode._____)  		{
			if(id==null) 				return "Select Mode";
		}
		if(mode==Mode.Gammal) 	{
			if(id==null) 	return "Gamma adjust";
			if(id.equals("param1")) 	return "Gamma value";

## Steps to Reproduce
Jason surely know how to fix it without needing to reproduce iut.

## Expected Result
When the mode is changed the description should get updated.
Even enabling/disabling the description using the description help button don't change anything.

## Actual Result
result is cached

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
![e1](https://cloud.githubusercontent.com/assets/9506454/26038902/d90918c6-3912-11e7-900e-4d27418522ae.png)
![e2](https://cloud.githubusercontent.com/assets/9506454/26038903/d90fc450-3912-11e7-9dea-503323370673.png)

**Comment by vonnieda** [comment]
Fixed.

**Comment by cri-s** [comment]
Thanks.
I have annother strange UI problem,
When i run this stage, the ui blocks some seconds.
I test it now cloning the mat, if it works, but maybe it's totally different reason and you know 
immediatly why it's blocking. It is the orginal stage, just the enum is changed/increased.

package org.openpnp.vision.pipeline.stages;

import org.opencv.core.Mat;
import org.opencv.imgproc.Imgproc;
import org.openpnp.vision.FluentCv;
import org.openpnp.vision.pipeline.CvPipeline;
import org.openpnp.vision.pipeline.CvStage;
import org.simpleframework.xml.Attribute;

/**
 * Converts the color of the current working image to the specified conversion.
 */
public class ConvertColor extends CvStage {

    public enum ColorCode {
BGR2BGR555(Imgproc.COLOR_BGR2BGR555),
BGR2BGR565(Imgproc.COLOR_BGR2BGR565),
BGR2BGRA(Imgproc.COLOR_BGR2BGRA),
BGR2GRAY(Imgproc.COLOR_BGR2GRAY),
BGR2HLS(Imgproc.COLOR_BGR2HLS),
BGR2HLS_FULL(Imgproc.COLOR_BGR2HLS_FULL),
BGR2HSV(Imgproc.COLOR_BGR2HSV),
BGR2HSV_FULL(Imgproc.COLOR_BGR2HSV_FULL),
BGR2Lab(Imgproc.COLOR_BGR2Lab),
BGR2Luv(Imgproc.COLOR_BGR2Luv),
BGR2RGB(Imgproc.COLOR_BGR2RGB),
BGR2RGBA(Imgproc.COLOR_BGR2RGBA),
BGR2XYZ(Imgproc.COLOR_BGR2XYZ),
BGR2YCrCb(Imgproc.COLOR_BGR2YCrCb),
BGR2YUV(Imgproc.COLOR_BGR2YUV),
BGR2YUV_I420(Imgproc.COLOR_BGR2YUV_I420),
BGR2YUV_IYUV(Imgproc.COLOR_BGR2YUV_IYUV),
BGR2YUV_YV12(Imgproc.COLOR_BGR2YUV_YV12),
BGR5552BGR(Imgproc.COLOR_BGR5552BGR),
BGR5552BGRA(Imgproc.COLOR_BGR5552BGRA),
BGR5552GRAY(Imgproc.COLOR_BGR5552GRAY),
BGR5552RGB(Imgproc.COLOR_BGR5552RGB),
BGR5552RGBA(Imgproc.COLOR_BGR5552RGBA),
BGR5652BGR(Imgproc.COLOR_BGR5652BGR),
BGR5652BGRA(Imgproc.COLOR_BGR5652BGRA),
BGR5652GRAY(Imgproc.COLOR_BGR5652GRAY),
BGR5652RGB(Imgproc.COLOR_BGR5652RGB),
BGR5652RGBA(Imgproc.COLOR_BGR5652RGBA),
BGRA2BGR(Imgproc.COLOR_BGRA2BGR),
BGRA2BGR555(Imgproc.COLOR_BGRA2BGR555),
BGRA2BGR565(Imgproc.COLOR_BGRA2BGR565),
BGRA2GRAY(Imgproc.COLOR_BGRA2GRAY),
BGRA2RGB(Imgproc.COLOR_BGRA2RGB),
BGRA2RGBA(Imgproc.COLOR_BGRA2RGBA),
BGRA2YUV_I420(Imgproc.COLOR_BGRA2YUV_I420),
BGRA2YUV_IYUV(Imgproc.COLOR_BGRA2YUV_IYUV),
BGRA2YUV_YV12(Imgproc.COLOR_BGRA2YUV_YV12),
BayerBG2BGR(Imgproc.COLOR_BayerBG2BGR),
BayerBG2BGR_VNG(Imgproc.COLOR_BayerBG2BGR_VNG),
BayerBG2GRAY(Imgproc.COLOR_BayerBG2GRAY),
BayerBG2RGB(Imgproc.COLOR_BayerBG2RGB),
BayerBG2RGB_VNG(Imgproc.COLOR_BayerBG2RGB_VNG),
BayerGB2BGR(Imgproc.COLOR_BayerGB2BGR),
BayerGB2BGR_VNG(Imgproc.COLOR_BayerGB2BGR_VNG),
BayerGB2GRAY(Imgproc.COLOR_BayerGB2GRAY),
BayerGB2RGB(Imgproc.COLOR_BayerGB2RGB),
BayerGB2RGB_VNG(Imgproc.COLOR_BayerGB2RGB_VNG),
BayerGR2BGR(Imgproc.COLOR_BayerGR2BGR),
BayerGR2BGR_VNG(Imgproc.COLOR_BayerGR2BGR_VNG),
BayerGR2GRAY(Imgproc.COLOR_BayerGR2GRAY),
BayerGR2RGB(Imgproc.COLOR_BayerGR2RGB),
BayerGR2RGB_VNG(Imgproc.COLOR_BayerGR2RGB_VNG),
BayerRG2BGR(Imgproc.COLOR_BayerRG2BGR),
BayerRG2BGR_VNG(Imgproc.COLOR_BayerRG2BGR_VNG),
BayerRG2GRAY(Imgproc.COLOR_BayerRG2GRAY),
BayerRG2RGB(Imgproc.COLOR_BayerRG2RGB),
BayerRG2RGB_VNG(Imgproc.COLOR_BayerRG2RGB_VNG),
COLORCVT_MAX(Imgproc.COLOR_COLORCVT_MAX),
GRAY2BGR(Imgproc.COLOR_GRAY2BGR),
GRAY2BGR555(Imgproc.COLOR_GRAY2BGR555),
GRAY2BGR565(Imgproc.COLOR_GRAY2BGR565),
GRAY2BGRA(Imgproc.COLOR_GRAY2BGRA),
GRAY2RGB(Imgproc.COLOR_GRAY2RGB),
GRAY2RGBA(Imgproc.COLOR_GRAY2RGBA),
HLS2BGR(Imgproc.COLOR_HLS2BGR),
HLS2BGR_FULL(Imgproc.COLOR_HLS2BGR_FULL),
HLS2RGB(Imgproc.COLOR_HLS2RGB),
HLS2RGB_FULL(Imgproc.COLOR_HLS2RGB_FULL),
HSV2BGR(Imgproc.COLOR_HSV2BGR),
HSV2BGR_FULL(Imgproc.COLOR_HSV2BGR_FULL),
HSV2RGB(Imgproc.COLOR_HSV2RGB),
HSV2RGB_FULL(Imgproc.COLOR_HSV2RGB_FULL),
LBGR2Lab(Imgproc.COLOR_LBGR2Lab),
LBGR2Luv(Imgproc.COLOR_LBGR2Luv),
LRGB2Lab(Imgproc.COLOR_LRGB2Lab),
LRGB2Luv(Imgproc.COLOR_LRGB2Luv),
Lab2BGR(Imgproc.COLOR_Lab2BGR),
Lab2LBGR(Imgproc.COLOR_Lab2LBGR),
Lab2LRGB(Imgproc.COLOR_Lab2LRGB),
Lab2RGB(Imgproc.COLOR_Lab2RGB),
Luv2BGR(Imgproc.COLOR_Luv2BGR),
Luv2LBGR(Imgproc.COLOR_Luv2LBGR),
Luv2LRGB(Imgproc.COLOR_Luv2LRGB),
Luv2RGB(Imgproc.COLOR_Luv2RGB),
RGB2BGR(Imgproc.COLOR_RGB2BGR),
RGB2BGR555(Imgproc.COLOR_RGB2BGR555),
RGB2BGR565(Imgproc.COLOR_RGB2BGR565),
RGB2BGRA(Imgproc.COLOR_RGB2BGRA),
RGB2GRAY(Imgproc.COLOR_RGB2GRAY),
RGB2HLS(Imgproc.COLOR_RGB2HLS),
RGB2HLS_FULL(Imgproc.COLOR_RGB2HLS_FULL),
RGB2HSV(Imgproc.COLOR_RGB2HSV),
RGB2HSV_FULL(Imgproc.COLOR_RGB2HSV_FULL),
RGB2Lab(Imgproc.COLOR_RGB2Lab),
RGB2Luv(Imgproc.COLOR_RGB2Luv),
RGB2RGBA(Imgproc.COLOR_RGB2RGBA),
RGB2XYZ(Imgproc.COLOR_RGB2XYZ),
RGB2YCrCb(Imgproc.COLOR_RGB2YCrCb),
RGB2YUV(Imgproc.COLOR_RGB2YUV),
RGB2YUV_I420(Imgproc.COLOR_RGB2YUV_I420),
RGB2YUV_IYUV(Imgproc.COLOR_RGB2YUV_IYUV),
RGB2YUV_YV12(Imgproc.COLOR_RGB2YUV_YV12),
RGBA2BGR(Imgproc.COLOR_RGBA2BGR),
RGBA2BGR555(Imgproc.COLOR_RGBA2BGR555),
RGBA2BGR565(Imgproc.COLOR_RGBA2BGR565),
RGBA2BGRA(Imgproc.COLOR_RGBA2BGRA),
RGBA2GRAY(Imgproc.COLOR_RGBA2GRAY),
RGBA2RGB(Imgproc.COLOR_RGBA2RGB),
RGBA2YUV_I420(Imgproc.COLOR_RGBA2YUV_I420),
RGBA2YUV_IYUV(Imgproc.COLOR_RGBA2YUV_IYUV),
RGBA2YUV_YV12(Imgproc.COLOR_RGBA2YUV_YV12),
RGBA2mRGBA(Imgproc.COLOR_RGBA2mRGBA),
XYZ2BGR(Imgproc.COLOR_XYZ2BGR),
XYZ2RGB(Imgproc.COLOR_XYZ2RGB),
YCrCb2BGR(Imgproc.COLOR_YCrCb2BGR),
YCrCb2RGB(Imgproc.COLOR_YCrCb2RGB),
YUV2BGR(Imgproc.COLOR_YUV2BGR),
YUV2BGRA_I420(Imgproc.COLOR_YUV2BGRA_I420),
YUV2BGRA_IYUV(Imgproc.COLOR_YUV2BGRA_IYUV),
YUV2BGRA_NV12(Imgproc.COLOR_YUV2BGRA_NV12),
YUV2BGRA_NV21(Imgproc.COLOR_YUV2BGRA_NV21),
YUV2BGRA_UYNV(Imgproc.COLOR_YUV2BGRA_UYNV),
YUV2BGRA_UYVY(Imgproc.COLOR_YUV2BGRA_UYVY),
YUV2BGRA_Y422(Imgproc.COLOR_YUV2BGRA_Y422),
YUV2BGRA_YUNV(Imgproc.COLOR_YUV2BGRA_YUNV),
YUV2BGRA_YUY2(Imgproc.COLOR_YUV2BGRA_YUY2),
YUV2BGRA_YUYV(Imgproc.COLOR_YUV2BGRA_YUYV),
YUV2BGRA_YV12(Imgproc.COLOR_YUV2BGRA_YV12),
YUV2BGRA_YVYU(Imgproc.COLOR_YUV2BGRA_YVYU),
YUV2BGR_I420(Imgproc.COLOR_YUV2BGR_I420),
YUV2BGR_IYUV(Imgproc.COLOR_YUV2BGR_IYUV),
YUV2BGR_NV12(Imgproc.COLOR_YUV2BGR_NV12),
YUV2BGR_NV21(Imgproc.COLOR_YUV2BGR_NV21),
YUV2BGR_UYNV(Imgproc.COLOR_YUV2BGR_UYNV),
YUV2BGR_UYVY(Imgproc.COLOR_YUV2BGR_UYVY),
YUV2BGR_Y422(Imgproc.COLOR_YUV2BGR_Y422),
YUV2BGR_YUNV(Imgproc.COLOR_YUV2BGR_YUNV),
YUV2BGR_YUY2(Imgproc.COLOR_YUV2BGR_YUY2),
YUV2BGR_YUYV(Imgproc.COLOR_YUV2BGR_YUYV),
YUV2BGR_YV12(Imgproc.COLOR_YUV2BGR_YV12),
YUV2BGR_YVYU(Imgproc.COLOR_YUV2BGR_YVYU),
YUV2GRAY_420(Imgproc.COLOR_YUV2GRAY_420),
YUV2GRAY_I420(Imgproc.COLOR_YUV2GRAY_I420),
YUV2GRAY_IYUV(Imgproc.COLOR_YUV2GRAY_IYUV),
YUV2GRAY_NV12(Imgproc.COLOR_YUV2GRAY_NV12),
YUV2GRAY_NV21(Imgproc.COLOR_YUV2GRAY_NV21),
YUV2GRAY_UYNV(Imgproc.COLOR_YUV2GRAY_UYNV),
YUV2GRAY_UYVY(Imgproc.COLOR_YUV2GRAY_UYVY),
YUV2GRAY_Y422(Imgproc.COLOR_YUV2GRAY_Y422),
YUV2GRAY_YUNV(Imgproc.COLOR_YUV2GRAY_YUNV),
YUV2GRAY_YUY2(Imgproc.COLOR_YUV2GRAY_YUY2),
YUV2GRAY_YUYV(Imgproc.COLOR_YUV2GRAY_YUYV),
YUV2GRAY_YV12(Imgproc.COLOR_YUV2GRAY_YV12),
YUV2GRAY_YVYU(Imgproc.COLOR_YUV2GRAY_YVYU),
YUV2RGB(Imgproc.COLOR_YUV2RGB),
YUV2RGBA_I420(Imgproc.COLOR_YUV2RGBA_I420),
YUV2RGBA_IYUV(Imgproc.COLOR_YUV2RGBA_IYUV),
YUV2RGBA_NV12(Imgproc.COLOR_YUV2RGBA_NV12),
YUV2RGBA_NV21(Imgproc.COLOR_YUV2RGBA_NV21),
YUV2RGBA_UYNV(Imgproc.COLOR_YUV2RGBA_UYNV),
YUV2RGBA_UYVY(Imgproc.COLOR_YUV2RGBA_UYVY),
YUV2RGBA_Y422(Imgproc.COLOR_YUV2RGBA_Y422),
YUV2RGBA_YUNV(Imgproc.COLOR_YUV2RGBA_YUNV),
YUV2RGBA_YUY2(Imgproc.COLOR_YUV2RGBA_YUY2),
YUV2RGBA_YUYV(Imgproc.COLOR_YUV2RGBA_YUYV),
YUV2RGBA_YV12(Imgproc.COLOR_YUV2RGBA_YV12),
YUV2RGBA_YVYU(Imgproc.COLOR_YUV2RGBA_YVYU),
YUV2RGB_I420(Imgproc.COLOR_YUV2RGB_I420),
YUV2RGB_IYUV(Imgproc.COLOR_YUV2RGB_IYUV),
YUV2RGB_NV12(Imgproc.COLOR_YUV2RGB_NV12),
YUV2RGB_NV21(Imgproc.COLOR_YUV2RGB_NV21),
YUV2RGB_UYNV(Imgproc.COLOR_YUV2RGB_UYNV),
YUV2RGB_UYVY(Imgproc.COLOR_YUV2RGB_UYVY),
YUV2RGB_Y422(Imgproc.COLOR_YUV2RGB_Y422),
YUV2RGB_YUNV(Imgproc.COLOR_YUV2RGB_YUNV),
YUV2RGB_YUY2(Imgproc.COLOR_YUV2RGB_YUY2),
YUV2RGB_YUYV(Imgproc.COLOR_YUV2RGB_YUYV),
YUV2RGB_YV12(Imgproc.COLOR_YUV2RGB_YV12),
YUV2RGB_YVYU(Imgproc.COLOR_YUV2RGB_YVYU),
YUV420p2BGR(Imgproc.COLOR_YUV420p2BGR),
YUV420p2BGRA(Imgproc.COLOR_YUV420p2BGRA),
YUV420p2GRAY(Imgproc.COLOR_YUV420p2GRAY),
YUV420p2RGB(Imgproc.COLOR_YUV420p2RGB),
YUV420p2RGBA(Imgproc.COLOR_YUV420p2RGBA),
YUV420sp2BGR(Imgproc.COLOR_YUV420sp2BGR),
YUV420sp2BGRA(Imgproc.COLOR_YUV420sp2BGRA),
YUV420sp2GRAY(Imgproc.COLOR_YUV420sp2GRAY),
YUV420sp2RGB(Imgproc.COLOR_YUV420sp2RGB),
YUV420sp2RGBA(Imgproc.COLOR_YUV420sp2RGBA),
mRGBA2RGBA(Imgproc.COLOR_mRGBA2RGBA);

        private int code;

        ColorCode(int code) {
            this.code = code;
        }

        public int getCode() {
            return code;
        }
    }

    @Attribute
    private ColorCode conversion = ColorCode.BGR2GRAY;

    public ColorCode getConversion() {
        return conversion;
    }

    public void setConversion(ColorCode conversion) {
        this.conversion = conversion;
    }

    @Override
    public Result process(CvPipeline pipeline) throws Exception {
        Mat mat = pipeline.getWorkingImage();
        Imgproc.cvtColor(mat, mat, conversion.getCode());
        return null;
    }
}

**Comment by vonnieda** [comment]
Sorry, I don't know why that would happen. Try decreasing the enum to half
and see if it halves the time. If so, it could be that the property editor
component has poor support for large enums.
