### ISSUE TITLE
loose feeder

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#562]
Jason, it is possible that you give reference image for loose feeder and examples from mixed loose feeder. Reference image need have the component at center and Other components should not touch it. Example images are then just images without the reference. Further  the pipeline to separate components from background, that background  part is black. I provide then reference stage and modified loose feeder.

**Comment by cri-s** [comment]
I close this as the intent was to provide image and discussion for wiki.

**Comment by vonnieda** [comment]
Hi @cri-s, there are some test images at https://github.com/openpnp/openpnp-test-images/tree/master/Parts/Loose but these don't contain the reference type images you mentioned. Maybe you or @dzach could make the references? I'm short on time and the loose part feeder is low on my priority list right now.

**Comment by cri-s** [comment]
The point is that my lightning is far better as the average openpnp
user and as such not
replicable or usable as reference.
If it's low on you'r priority list, forget it.



2017-05-15 17:19 GMT+02:00, Jason von Nieda <notifications@github.com>:

**Comment by vonnieda** [comment]
@cri-s Okay, I see. I'll put a few up tonight. I don't have many parts on hand right now, but I should be able to put up at least 4-5.

**Comment by vonnieda** [comment]
@cri-s Okay, I tried taking some sample pictures, but it looks like my lighting is basically useless for this. Here are two examples:
![fiducial cam_2017-05-15_22 04 06 116](https://cloud.githubusercontent.com/assets/1182323/26088231/92d15ed2-39bb-11e7-9fa9-33463c6ee952.png)
![fiducial cam_2017-05-15_22 05 13 540](https://cloud.githubusercontent.com/assets/1182323/26088240/9a15f658-39bb-11e7-8c9a-1a1e97412955.png)

Here is the first part, but with the head moved so the lighting is offset:
![fiducial cam_2017-05-15_22 04 12 033](https://cloud.githubusercontent.com/assets/1182323/26088257/b11c0c66-39bb-11e7-8ac0-b539b4af1d03.png)

And here is the second part lit by a flashlight from about a 45 degree angle:
![fiducial cam_2017-05-15_22 11 12 001](https://cloud.githubusercontent.com/assets/1182323/26088266/bbba522c-39bb-11e7-82f8-39d2f78d2528.png)

With the offset lighting the markings are clearly visible. So, I think I need to improve my lighting before I can make useful images. 

What do you think?

**Comment by vonnieda** [comment]
Looping in @dzach since they may find this interesting.

**Comment by cri-s** [comment]
Can you please check the soic chip at the approx same offset position
as the capacitor.
On capacitor the marking can be read on that position, probably on the
soic chip too.
It is possible to make a picture too with both components, just to
have annother picture with component rotated, eventually more then 90
deg.

2017-05-16 5:14 GMT+02:00, Jason von Nieda <notifications@github.com>:

**Comment by vonnieda** [comment]
Sure, here they are:
![fiducial cam_2017-05-15_22 44 23 884](https://cloud.githubusercontent.com/assets/1182323/26089041/53323f12-39c0-11e7-8bcc-8465ac7da4c4.png)
![fiducial cam_2017-05-15_22 44 12 095](https://cloud.githubusercontent.com/assets/1182323/26089043/558bc2b0-39c0-11e7-94b6-1ec61ce38544.png)

And here are some more of all the parts I have handy:

![fiducial cam_2017-05-15_22 48 35 827](https://cloud.githubusercontent.com/assets/1182323/26089103/cba6df02-39c0-11e7-9b48-44ece8636bbc.png)
![fiducial cam_2017-05-15_22 48 40 171](https://cloud.githubusercontent.com/assets/1182323/26089104/cbab5ba4-39c0-11e7-8819-b3d68e2f8000.png)
![fiducial cam_2017-05-15_22 48 43 983](https://cloud.githubusercontent.com/assets/1182323/26089109/cbb40a7e-39c0-11e7-9f76-b00dd5bfbc22.png)
![fiducial cam_2017-05-15_22 48 48 008](https://cloud.githubusercontent.com/assets/1182323/26089106/cbad4220-39c0-11e7-9db6-ab1402e92ba1.png)
![fiducial cam_2017-05-15_22 48 52 405](https://cloud.githubusercontent.com/assets/1182323/26089105/cbacd812-39c0-11e7-912f-0494571c8bb7.png)
![fiducial cam_2017-05-15_22 48 57 015](https://cloud.githubusercontent.com/assets/1182323/26089107/cbb1275a-39c0-11e7-8bd6-d6fe80187c8e.png)
![fiducial cam_2017-05-15_22 49 00 851](https://cloud.githubusercontent.com/assets/1182323/26089108/cbb392e2-39c0-11e7-9d6b-4795176f944d.png)
![fiducial cam_2017-05-15_22 49 05 249](https://cloud.githubusercontent.com/assets/1182323/26089111/cbbe7ffe-39c0-11e7-9978-492cc5979802.png)
![fiducial cam_2017-05-15_22 49 08 920](https://cloud.githubusercontent.com/assets/1182323/26089110/cbb94b4c-39c0-11e7-8e41-1e81f0fb799c.png)
