### ISSUE TITLE
PR single merge issue

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#567]
# Read This First
To submit an issue for OpenPnP you must use this template or it will be deleted. Please fill out either the Problem Report or Feature Request section below and delete the other section.

-----------------------------------------------------------------------

# Problem Report
## Describe the Issue
I want create a PR for accessing Part inside pipeline.
changes shoud be adding variable part to pipeline,
and on 
public Part getPart() {
  if(part==null) if(feeder!=null) part=feeder.getPart(); else if(nozzle!=null) part=nozzle.getFeeder();
 return part;
}

How to commit this, if  for this #565 and #566 is needed in order to access to this variables ?
AS i have experienced, committing  file where thing is missing and adding this missing later,
block travis checking.

## Expected Result
Response how to submit such patch having the reuqirement to reduce patch to such small and detailed
patch level.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
The more information you can provide about the issue the more likely it is that a developer will be able to respond.

Whenever possible, please use the Menu -> Help -> Submit Diagnostics feature and include the URL here. Submit Diagnostics makes it easy to include log files, screen capture, debug images, configuration files, etc.

-----------------------------------------------------------------------

# Feature Request
## Describe the Feature
What do you want it to do? Be as descriptive as possible.

## How Will It Look?
If the feature will include changes to the user interface, how would they look? Include drawings or mockups if possible.

## Why Do We Need It?
1. What problem does it solve?
2. Is it useful for everyone, or does it only solve a problem for your machine?

## Provide Examples
Is this something that exists in other pick and place software? Provide examples and references if possible.

**Comment by vonnieda** [comment]
These are merged now, so it should be okay to add in your next change. If you mean to add getPart() to Pipeline, though, I'd prefer if you do it the same as the others and set it where needed, rather than try to derive it from Nozzle or Feeder. setPart and getPart will be more flexible.
