### ISSUE TITLE
TODO nozzleTip calibration pipeline.setNozzle.

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#568]
# Read This First
To submit an issue for OpenPnP you must use this template or it will be deleted. Please fill out either the Problem Report or Feature Request section below and delete the other section.

-----------------------------------------------------------------------

# Problem Report
## Describe the Issue
Cannot use pipeline.setNozzle() inside ReferenceNozzleTip.java on static class Calibration , because
it is not possible to use getParentNozzle() from a static class.
Accessing Nozzle from calibration is not essential, it could have some uses.

## Steps to Reproduce
  public CvPipeline getPipeline() throws Exception {
             pipeline.setCamera(VisionUtils.getBottomVisionCamera());
             pipeline.setCamera(VisionUtils.getBottomVisionCamera());
             pipeline.setNozzle(getParentNozzle());
             return pipeline;
         }
 
 
## Expected Result
setNozzle could be set

## Actual Result
not compile

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
this is a TODO note if relevant.
-----------------------------------------------------------------------

# Feature Request
## Describe the Feature
What do you want it to do? Be as descriptive as possible.

## How Will It Look?
If the feature will include changes to the user interface, how would they look? Include drawings or mockups if possible.

## Why Do We Need It?
1. What problem does it solve?
2. Is it useful for everyone, or does it only solve a problem for your machine?

## Provide Examples
Is this something that exists in other pick and place software? Provide examples and references if possible.

**Comment by vonnieda** [comment]
You can call nozzleTip.getParentNozzle() from calibrate(ReferenceNozzleTip).
