### ISSUE TITLE
Final Rotation Alignment Ignored Fiducials

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#575]
See discussion in https://groups.google.com/d/msgid/openpnp/CAJGcfUhOtApPf5OkwpufzX4thGyO1MjCtFzb9QjeSr5q_v-FwA%40mail.gmail.com.

The new final rotation alignment code added in https://github.com/openpnp/openpnp/pull/571 is not taking board fiducials into account. The fiducial updates are handled in ReferencePnpJobProcessor:657. This should be moved into the planning stage and the offsets applied there, so that any code past the planning stage has access to the correct board location.

**Comment by cri-s** [comment]
https://github.com/openpnp/openpnp/compare/develop...cri-s:patch-1
This patch could fix the fiducial bug.
As local fiducials are not working, maybe this sort of fix seems reasonable..

**Comment by vonnieda** [comment]
That code does not compile.
