### ISSUE TITLE
how to find out what the real reason is ? simple-xml should be more verbose what it parses.

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#578]
# Read This First
To submit an issue for OpenPnP you must use this template or it will be deleted. Please fill out either the Problem Report or Feature Request section below and delete the other section.

-----------------------------------------------------------------------

# Problem Report
## Describe the Issue
Simple-XML report to less about the problem when one is encountered

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
Vision pipeline, no custom stages, but apparently there is a inherent problem
it was not possible to close openpnp saving the changes made.
What was made:
added part, created vision pipeline for that part.

## Expected Result
What did you expect to happen? Be descriptive.
That it gives more info that help localize the problem.
As no custom stages was involved into that vision stage, i don't have idea why there was this issue.

## Actual Result
What actually happened? Be descriptive.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
The more information you can provide about the issue the more likely it is that a developer will be able to respond.

![dialog](https://cloud.githubusercontent.com/assets/9506454/26724912/1360f664-479c-11e7-98e3-b7fb2687e11f.jpg)

**Comment by vonnieda** [comment]
Add `e.printStackTrace();` around MainFrame.java:687 to see the full exception. This should help you find out what OpenPnP was trying to do when the error happened.
