### ISSUE TITLE
Open PNP won't load I.E Hangs on launch PLS Help

### ISSUE THREAD

**Issue by oricalworks** [openpnp/openpnp#582]
Hello, Thanks for looking at my issue! OpenPnP was working just fine until one day it froze/hang on launch, and since then I have updated Java, uninstalled and reinstalled many times, tried different versions all with no luck. Hopefully, some one can help me. Here is the system Log. 
[OpenPNP Launch Hang Log.txt](https://github.com/openpnp/openpnp/files/1064492/OpenPNP.Launch.Hang.Log.txt)

Thanks for all who Help !!!!

**Comment by vonnieda** [comment]
@oricalworks Please send or attach your machine.xml file.

**Comment by vonnieda** [comment]
Closing as there has been no response from @oricalworks. Will reopen if needed.
