### ISSUE TITLE
NullPointerException when adding actuator if simulated Up camera is present

### ISSUE THREAD

**Issue by lilltroll77** [openpnp/openpnp#589]
If you follow the steps at
[https://github.com/openpnp/openpnp/wiki/Setup-and-Calibration%3A-Camera-Lighting]
and have a SimulatedUpCamera under machine setup, openpnp will throw a NullPointerException when you press your (new) button under Machine Controls -> actuators.

Maybe at least update the documentation that you need to remove simulated cameras prior to adding an actuator-control for lightning.

![image](https://user-images.githubusercontent.com/493682/27516457-96a13c70-59ba-11e7-8551-e7860aa450f8.png)

**Comment by vonnieda** [comment]
@lilltroll77 What version did this happen on?

**Comment by lilltroll77** [comment]
2017-06-16 version under Win10 x64

**Comment by vonnieda** [comment]
Thanks for the report @lilltroll77, this is now fixed.
