### ISSUE TITLE
Documentation / wiki/Setup-and-Calibration%3A-Driver-Setup

### ISSUE THREAD

**Issue by johngrabner** [openpnp/openpnp#600]
# Problem Report
## Describe the Issue
Instruction to setup a driver shows an image that does not match actual.
Step "Set Serial Port and Baud rate" shows image 
![image](https://user-images.githubusercontent.com/8209285/28387370-691323c6-6c94-11e7-98c1-d63d4e186880.png)

but actual running program shows
![image](https://user-images.githubusercontent.com/8209285/28387392-864fae1e-6c94-11e7-85d4-e2c22c58993b.png)

I am a newbe, so this deviation confuses the learning process.
It appears that the documentation is outdated with the introduction of sub-drivers.  I would offer a fix, but being a newbe, I am more likely to mess things up.

## Steps to Reproduce
1. follow instruction under "Choosing a Driver"
1.1. select GcodDriver
1.2 click apply
1.3 quit the application and relaunch

## Expected Result
image in documentation match current version of code. 
![image](https://user-images.githubusercontent.com/8209285/28387609-64a88492-6c95-11e7-9523-f129662f936d.png)

## Actual Result
See above

**Comment by johngrabner** [comment]
To make things easier, here is the clean image that I believe should be used. 
![image](https://user-images.githubusercontent.com/8209285/28393523-d37163d2-6cac-11e7-951b-6a186cd62fa3.png)

**Comment by vonnieda** [comment]
Looks good, thanks @johngrabner. I've updated the Wiki with the image you provided. If it looks good to you, please close this issue.

**Comment by Duyvinh0307** [comment]
https://youtu.be/99Tx5tPeeZY
Hepl

**Comment by vonnieda** [comment]
Hi @Duyvinh0307 - this is a closed issue not related to the problem you are experiencing. Please post your question to http://groups.google.com/group/openpnp.
