### ISSUE TITLE
UI Bug: In Parts list in the Job tab. Deleting items with "Part/Side/Type" selected overwrites values in the next item.

### ISSUE THREAD

**Issue by yaddatrance** [openpnp/openpnp#607]
# Problem Report
## Describe the Issue

This is a "unexpected behavior" bug. Deleting an item in the Parts menu (under the Pick and Place tab of the Jobs tab) with the wrong element highlighted can cause the next item to inherit the first item's element.

Also seems to affect Side and Type columns.

Running on the development release of 2017-07-02_15_55-02.d43f075

## Steps to Reproduce

1. In the Job tab, load up a job with parts defined. 
2. Click on a line item using the "Part/Side/Type" column such that you see the dropdown 'v' on the right. The dropdown doesn't have to be open.
3. If you click on the red X to delete the part, 
4. the deleted item's "Part/Side/Type" gets set as the part/side/type for the next item in the list.

## Expected Result
Item should be deleted cleanly without affecting other items.

## Actual Result
The deleted item's "Part/Side/Type" gets set as the part/side/type for the next item in the list.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue

Image 1: Selecting the item with the Part column in focus, in this case a battery
![image](https://user-images.githubusercontent.com/30197387/28656328-33f1bdd4-7256-11e7-836c-8d3e4e8bcaf6.png)

Image 2: Deleting with the red X ends up overwriting the Part of the next item. R4 incorrectly shows CR-2032
![image](https://user-images.githubusercontent.com/30197387/28656363-5d33e42e-7256-11e7-88f9-1076413e1c51.png)

**Comment by vonnieda** [comment]
Reproduced as described. I think this is probably similar to the bug in #597 and a similar fix might work.

**Comment by vonnieda** [comment]
One of the recent UI fixes fixed this. Can no longer reproduce.
