### ISSUE TITLE
Interface Enhancement

### ISSUE THREAD

**Issue by terryjen** [openpnp/openpnp#608]
# Feature Request
1. User can choose to show the console. 
2. Have separate home button for X, Y, Z.
3. When turn off the machine, please disconnect with Smoothieboard.
-----------------------------------------------------------------------

## Describe the Feature
1. A console form floating on the program,it's movable.  It combines the console and log, very useful when calibrating. It can send command directly, and we can see the command send from OpenPNP to the machine and the returns in very brief information such as "G1 X1 Y1 Z1 F1 .........   OK" 
2. Please take a look at pronterface, it uses four corner of the control panel. so we can set home separately. and the move button in pronterface is interesting.
3. When turn off the machine, please disconnect with Smoothieboard. 

## Why Do We Need it?
1. During calibration, I have to send M999 many times, the man working on this project before me, didn't find the console in OpenPNP, so he told me to turn off OpenPNP(Click turn off button, actually still connected) and connected with pronterface, to send M999, and Start OpenPNP again. If we can have a console in a floating window, and we can open/close it, it might be very convenient during this period. 
It happened sometimes, when I want to move X 1mm, but it moves continuously until touch the limit switch, and shows timeout messagebox. and I know we can get detail information from log, but if we can directly see these brief information on the same console, it would be ideal.
2. During calibration, sometimes I want it can go home one by one.
3. As I said in No.1, sometime I use pronterface and OpenPNP together, but OpenPNP didn't disconnect with the smoothieboard when press turn off button, so I have to turn off the program, and start it again.

All these things are no big deal, and you may have different opinions, so just several suggestions.
If you have some idea about why it goes time out, please tell me, thanks very much.

Cheers,
Terry

**Comment by vonnieda** [comment]
Please submit only one change / feature request per issue. Combining multiple requests in a single issue makes it difficult to track what is happening with each.
