### ISSUE TITLE
Need help: APIs 

### ISSUE THREAD

**Issue by terryjen** [openpnp/openpnp#616]
# Feature Request
## Describe the Feature
Hi Mr. Jason von Nieda, 
Would you please help me perform the following 3 API tasks:
1. Control the Job Process to "Process one step of the job and pause".
2. Create a status message stating "step is complete process is paused"
3. Send a command to move the nozzle to a safe position. (Optional)

## Why Do I Need It?
I'm using a PnP machine with another 3 axis robot to work together. I need to let the two machines speak with eachother.  I only want one to be working at a time, so when the PnP is operating the other robot is dormant.  Once the PnP has completed its task, it sends a command to the robot to start its task.  Once the robot has completed its task, it sends a command back to the PnP etc. I hope I can program a sperate Java or javascript program to control the OpenPnP to do the 3 steps.

My major is in mechanical engineering and I am just starting to learn Java, I am more comfortable with VB. I have figured out how to send these commands to the 3 axis robot, but cannot figure out how to do it to and from your PnP source code. 

Any help or tips will be greatly appreciated. 

Thanks very much!
Terry

**Comment by vonnieda** [comment]
There isn't a good way to do this without adding significant code to the system. These APIs are not exposed outside of the program, so a way to expose them will need to be added, or new scripting hooks will need to be added. It would probably be easiest to add a new [Scripting Event](https://github.com/openpnp/openpnp/wiki/Scripting#scripting-events) that is fired after each placement is completed and then write a script in OpenPnP that sends commands to the other robot.

Please post your questions to the [mailing list](http://groups.google.com/group/openpnp) and maybe someone can help. Other people have done complex integrations like this in the past and may have some thoughts on it.
