### ISSUE TITLE
Stripfeeder Autosetup pop-up loop with broken pipeline

### ISSUE THREAD

**Issue by ticso24** [openpnp/openpnp#644]
-----------------------------------------------------------------------

# Problem Report
## Describe the Issue
When running an autosetup with a broken pipeline setup (e.g. disabled hole detection) you get a popup error message "unregognised result type".
This makes it hard to disable the autoscan.
Similar issue when running the pipeline configuration while doing an autosetup and then break it.

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
1. Select any stripfeeder.
2. activate autosetup.
3. enter pipeline editor
4. disable results (DetectFixedCirclesHough)

## Expected Result
Autosetup shouldn't retry after a popup error.

## Actual Result
PopUp reappears endless.

**Comment by vonnieda** [comment]
Fixed in https://github.com/openpnp/openpnp/pull/645
