### ISSUE TITLE
Camera resolution if applying transformation

### ISSUE THREAD

**Issue by mgrl** [openpnp/openpnp#649]
# Problem Report
## Describe the Issue
It seems if rotating the camera there is some math off. Rotating the camera view by 180 degrees, the resolution of the camera is different from the resolution if not rotating. see attached files.

## Steps to Reproduce
1. Start OpenPnP
2. Go to camera properties
3. set rotation to 180°
4. see the information in camera view and compare to the information given if rotation =0

## Expected Result
resolution should not change. 
![camera_nonrotated_setup](https://user-images.githubusercontent.com/3868450/30663974-8b40d5ee-9e4c-11e7-9b1d-73ec1a99b34a.png)

## Actual Result
It seems there are black borders added to the images delivered from the camera.

![camera_rotated_setup](https://user-images.githubusercontent.com/3868450/30663976-8bfa6644-9e4c-11e7-94d4-086ba6b6edc4.png)

snapshot:
![downlookingcam_2017-09-20_21 32 05 091](https://user-images.githubusercontent.com/3868450/30663975-8b56384e-9e4c-11e7-9397-17116476ec7f.png)

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
Added further logs which show the camera opening procedure.
![camera_log](https://user-images.githubusercontent.com/3868450/30663973-8b3d9172-9e4c-11e7-844c-858901a92c92.png)
Two things I would like to point out:
1: When opening a camera there are two logs to that. has this to do with some buffered cameras internally used or is there a duplicate of camera stream?
2: the resolution set and reported is wrong in the first time, the camera is opened, the second time its correct.

maybe thats all not a problem, but wanted to let you know...

**Comment by cri-s** [comment]
Rotation is for correcting alignments errors, example 3.456 degree. 
For 180 degree you should use both flip options.
640x480 resolution is displayed when the camera don't give out invalid image.
That happens when camera starts, the first 10-15 images are wrong or most of it are wrong and when getting that wrong image camera dimension change in your case. That is normal.

**Comment by mgrl** [comment]
OK, just flipping works for me.
