### ISSUE TITLE
Java Virtual Machine does not exit when using opencv camera on windows

### ISSUE THREAD

**Issue by Laczen** [openpnp/openpnp#65]
When using a opencv camera on windows the JVM continues running when exiting the program. The JVM needs to be killed using task manager to return to openpnp.bat.

**Comment by FlyingLotus1983** [comment]
I'm seeing this issue as well :(  I'm subscribing and will let you guys know if I come up with a way to mitigate it.

**Comment by vonnieda** [comment]
Note to self: A quick way to fix this without updating the API would be to use a MachineListener and disable the camera when the machine becomes disabled.
