### ISSUE TITLE
Full path of board filename in job

### ISSUE THREAD

**Issue by ticso24** [openpnp/openpnp#652]
# Feature Request
## Describe the Feature
I like to have a way to view the full pathname of a boardfile within the loaded job.

## How Will It Look?
Always showing the full pathname in the job list is likely a bad idea, but showing it as tooltip on the board filename would be nice.

## Why Do We Need It?
1. What problem does it solve?
Sometimes filenames are not all that informative without a path and so far the only way to lookup the complete path is by looking into the job.xml.
2. Is it useful for everyone, or does it only solve a problem for your machine?
It may be specific to the way I work with board files, but will likely useful for a few others as well.

**Comment by vonnieda** [comment]
Good suggestion. Should be easy to implement.

**Comment by vonnieda** [comment]
Fixed in #653. Thank you @pfried for this nice fix!

**Comment by vanthome** [comment]
@ticso24 I saw your videos on youtube. Can you share what hardware you used? Is it a DIY build? I'm also interested in building one.
