### ISSUE TITLE
GcodeDrivers Should Have an Editable Name

### ISSUE THREAD

**Issue by KarlZeilhofer** [openpnp/openpnp#665]
# Problem Report
## Describe the Issue
When using more than one GCode driver, the cannot be distinguished in the List. 
![image](https://user-images.githubusercontent.com/2773445/31603623-ff4d2000-b260-11e7-8658-fd20cde01e43.png)

**Comment by vonnieda** [comment]
Note: Updated title to reflect the change that should be made.

**Comment by KarlZeilhofer** [comment]
@vonnieda  Thanks for fixing this!

**Comment by KarlZeilhofer** [comment]
Looks much better:
![2017-10-27_006](https://user-images.githubusercontent.com/2773445/32105340-6750f1de-bb28-11e7-8c34-7623d35939ae.png)
