### ISSUE TITLE
Splitview not editable (any more) by drag and drop

### ISSUE THREAD

**Issue by mgrl** [openpnp/openpnp#676]
# Problem Report
## Describe the Issue
In the past one could move the splitscreen vertical bar by mouse. Noticed, this is not possible any more. 

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
1. Start OpenPnP
2. try to move vertical bar

## Expected Result
Camera view / tabs get scaled according movement

## Actual Result
nothing happens, vertical bar sticks

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
![split-view](https://user-images.githubusercontent.com/3868450/32214909-a0a647f4-be20-11e7-8f26-488108b411e7.PNG)

I'm on current version loaded from page. Windows if it matters.

Anybody seeing this issue, too?

**Comment by vonnieda** [comment]
@mgrl This is likely due to the large number of actuators you have, and that panel not flowing correctly. Try switching to the Jog tab and see if that helps.

**Comment by mgrl** [comment]
@vonnieda No, it's on every tab. Made the screenshot in the acutators tab to see where it may come from.
As workaround I don't use the window in fullscreen. then I make the whole window smaller, which makes the area on the left side smaller, too. afterwards I make the window on the right side bigger again. the jog-tab, etc. remain small then...

**Comment by vonnieda** [comment]
Did a quick test and it does seem to be related to the number of actuators, even when the panel flows correctly. Will need to look into this further. Possible that the layout manager for the actuators panel is locked for some reason.

**Comment by KarlZeilhofer** [comment]
same here. I've noticed this problem, but I ignored it for now. I still have a goot ratio between left and right pane. I never saw my actuator buttons in 2 or more rows, only a single row since I'm using openpnp. I'm running Linux Mint 18.2.
