### ISSUE TITLE
An X mounted Camera should not try to move Nozzle in Z or C.

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#69]
See this thread: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openpnp/dSnRUW8kd9Y/ZfIva7x1IP8J

**Comment by vonnieda** [comment]
This should be handled in the driver. It's handled in the OpenBuilds driver and for other drivers it should perhaps be a flag. Suggest adding it to GcodeDriver in #106 and retiring the others.

**Comment by dave-prosee** [comment]
I ran into this problem and changed to the GcodeDriver. So the desired behaviour is possible with a certain configuration. Since you have a lot of issues I would propose this could be closed to save your time.

**Comment by vonnieda** [comment]
Agreed, thanks @dave-prosee!
