### ISSUE TITLE
Machine.xml: Nozzle class default doesn't include required 'current-nozzle-tip-id="NT1"'

### ISSUE THREAD

**Issue by FlyingLotus1983** [openpnp/openpnp#71]
Reproducable steps:
Using commit 3c09c2b46132a96fc19b5088c41545b98ecc1cf8 [3c09c2b]
Let OpenPnP create default XML config.
Edit to change to real motion control driver (I picked MarlinDriver from our firepick repo)
Launch OpenPnP
Hit "START"
Hit <ctrl-tab>
Hit 'Pick' button
I get error "Can't pick, no nozzle tip loaded"

Adding current-nozzle-tip-id="NT1" to <nozzle>  in machine.xml temporarily fixes the problem, but 'current-nozzle-tip-id' should probably be added as an attribute as default to machine.xml when it's created.

**Comment by vonnieda** [comment]
Fixed in e1b3f87c550a2af4ebc2d7f436919d326f01743d
