### ISSUE TITLE
Update Camera Wiki

### ISSUE THREAD

**Issue by johnthagen** [openpnp/openpnp#717]
At this link: https://github.com/openpnp/openpnp/wiki/USB-Camera-Troubleshooting-FAQ#why-is-it-a-software-limitation

There are links to two issues which have since been marked closed. Should the wiki be updated to reflect this?

**Comment by markmaker** [comment]
Hi
 I just wanted to comment, that the USB limitation still applies to MJPEG cameras. At least with the two ELP Full HD cams I'm using. All the video modes just "fill up" the bandwith. If you choose a lower resolution you atomatically get a higher frame rate and vice versa. There seems no way (yet?) to set the native frame rate, it seems the driver will just throw away surplus frames when you choose a lower frame rate in OpenPNP. BTW: I also suffer from the [high CPU usage issue,](https://github.com/openpnp/openpnp/issues/687) 
_Mark

**Comment by vonnieda** [comment]
Updated, thanks!

**Comment by vonnieda** [comment]
@markmaker Updated Wiki to include stronger language about sticking to the recommendations: https://github.com/openpnp/openpnp/wiki/OpenPnpCaptureCamera#troubleshooting

Do you think this resolves the issue?

**Comment by markmaker** [comment]
@vonnieda Certainly an improvement. I'm still on it trying to find specific causes and effects and limits. 

Thanks.
