### ISSUE TITLE
OS freezes when starting "Edit Pipeline" in feeder settings

### ISSUE THREAD

**Issue by olablt** [openpnp/openpnp#723]
# Problem Report
## Describe the Issue
I am on the latest Fedora with the Java 8. Configured Gcode driver successfully, added USB camera to my cameras list and can not setup the vision for the openpnp.

## Steps to Reproduce
Going through steps in https://github.com/openpnp/openpnp/wiki/Setup-and-Calibration:-Feeders

1. Start OpenPnP
2. Click Feeders tab
3. Create new feeder by pressing "+"
4. Press "Edit Pipeline"

## Expected Result
I expect to be able to edit Pipeline

## Actual Result
I see Pipeline window but system is freezed - only mouse pointer moving but I am unable to click anything

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
Commind line log:
![image](https://user-images.githubusercontent.com/674574/39241463-a79b5abe-488f-11e8-93f5-4e8fb8d80bd0.png)

Vesion

![image](https://user-images.githubusercontent.com/674574/39407068-0b1ebd74-4bc9-11e8-8b5c-ffa41a35f093.png)

**Comment by olablt** [comment]
any ideas how I can debug the problem? maybe some dependencies are missing for vision to work?

**Comment by markmaker** [comment]
Do you have Java 8? When I had Java 9 I couldn't edit pipeline (though that was on Windows). Maybe it is related? 

See here:
https://groups.google.com/d/msg/openpnp/fs9gefGd15U/ZB38U3o-AQAJ

**Comment by olablt** [comment]
Thank you @markmaker for suggestion.

I am on the latest Fedora with the Java 8

![image](https://user-images.githubusercontent.com/674574/39406985-f568d150-4bc7-11e8-8ddf-edfa115cd1cd.png)

**Comment by olablt** [comment]
well.. it is working after I changed the default java from openjdk to downloaded install 

```
sudo alternatives --config java
```
