### ISSUE TITLE
Add UI warning when changing tabs without hitting 'Apply'

### ISSUE THREAD

**Issue by FlyingLotus1983** [openpnp/openpnp#74]
If you don't hit 'Apply', I believe your changes will not get saved and will be lost forever.  Would be nice to have a warning to make a user doesn't forget to save before switching.  Specifically, I'm seeing this currently on the feeder tab, when switching feeder ID#'s on the left-hand side, after changing, for exmaple, the part drop box, but not hitting apply.

**Comment by cri-s** [comment]
I propose to add field without apply cancel button. I can change the code wanted.

**Comment by vonnieda** [comment]
Also see #473

**Comment by vonnieda** [comment]
I'm closing old issues that have seen little interest. PRs welcome. Also, duplicate of #473
