### ISSUE TITLE
Tape feeder height

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#75]
Tape feeder have always the same picking height.
Actually the component height get added on picking, this is wrong.
It should be:
        picklocation =  location.sub(
        Location(getPart().getUnit(),0,0,getPart().getValue(),0)
        );

**Comment by vonnieda** [comment]
OpenPnP is designed for:

X positive right
Y positive ahead
Z positive up
C positive clockwise

In general, OpenPnP will handle whatever coordinate setup that you like
although I think this part height calculation might be the one place where
it assumes you are using Z as stated.
