### ISSUE TITLE
Add a way to emit a Gcode for moveToSafeZ.

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#751]
This might mean pushing safe-z into the driver interface, or maybe it could be implemented as "before any X/Y move after a Z move"

See https://groups.google.com/d/msgid/openpnp/da664461-5004-45d7-8283-2934725d51e7%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by wiegleyj** [comment]
Yes, in general you need better Z handling. After homing there should be a way to get an automatic move to a safe-z.

**Comment by markmaker** [comment]
This is covered by #1074 axis interlocking actuators. 

See
https://github.com/openpnp/openpnp/wiki/Axis-Interlock-Actuator
