### ISSUE TITLE
ReferenceStripFeeder Breaks When Part Pitch > Hole to Hole Distance

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#755]
Set hole to hole distance to 4mm, set part pitch to 8mm, attempt to feed. Feeder tries to go to -Infinity.

See https://groups.google.com/d/msgid/openpnp/CAAYwRibwxzE8xs9gvVsWvfqyk8hXK_8HzNphxQZLbN8gYuD_ZA%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by doppelgrau** [comment]
Can be closed? A PR has been merged in December.
