### ISSUE TITLE
Drivers Should Error on Bad Coordinates

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#756]
Based on #755, if a driver is commanded to go to a bad coordinate (like NaN, -Infinity, etc.) it should throw an error.

See: https://groups.google.com/d/msgid/openpnp/CAAYwRibwxzE8xs9gvVsWvfqyk8hXK_8HzNphxQZLbN8gYuD_ZA%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by markmaker** [comment]
I believe this is covered by Advanced Motion Control, but maybe not fully. 

Drivers never receive NaN, as these are substituted in the HeadMountable/Head raw coordinate transformation:

https://github.com/openpnp/openpnp/blob/b040a09c6239a55ed5e781093000a2236f19b2f7/src/main/java/org/openpnp/spi/base/AbstractHeadMountable.java#L289-L325

Furthermore, Infinity coordinates will be caught implicitly at if you have defined soft limits: 

https://github.com/openpnp/openpnp/blob/c6149415f40b7aca9760c6cd14cebd975b94c6c3/src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java#L448

Having soft limits enabled seems a reasonable prerequisite for this to be caught. But that's a judgement call.
