### ISSUE TITLE
CameraView Corruption

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#758]
When you move the head around the image in the camera view sometimes becomes corrupt, showing bits of the previous image. This may be restricted only to ImageCamera - haven't determined that yet.

To reproduce, start with a default configuration and then jog the head 10mm left then right. A small part of the image will be left behind for 1-2 frames.

I tried to figure out what was causing this but didn't get there. I took this note:

        // I think we need to respect the bounds of the source image. I think that's what's
        // causing partial images to be drawn. At 0,0 we're requesting -320,3760 from the
        // source image.

**Comment by markmaker** [comment]
Yes, that was a bug in the ImageCamera when the margin was in the view. Long ago solved ...

https://github.com/openpnp/openpnp/commit/3d2409ad4c0a4444faa0cdcb401f6b1b547607c2

... and later made obsolete when the new sub-pixel drawing method is enabled. 

https://github.com/openpnp/openpnp/blob/develop/src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java#L158-L190
