### ISSUE TITLE
Missing files in repository

### ISSUE THREAD

**Issue by uwekoenig** [openpnp/openpnp#763]
In openpnp/src/main/java/org/openpnp/machine/reference/camera/OpenPnpCaptureCamera.java are a few imports from the package `org.openpnp.capture`
I can't find any of these files in the repository.

**Comment by vonnieda** [comment]
@uwekoenig They are part of the capture package at https://github.com/openpnp/openpnp-capture. You'll get these dependencies automatically if you run `mvn package`. See https://github.com/openpnp/openpnp/wiki/Developers-Guide#building-openpnp
