### ISSUE TITLE
Home button remains yellow though "Home after ENABLED?" is checked

### ISSUE THREAD

**Issue by ldpgh** [openpnp/openpnp#781]
# Problem Report
## Describe the Issue
If "Home after ENABLED?" in MachineSetup/ReferenceMachine is enabled and "home" command is issued right after "enable".

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
1. Start OpenPnP
2. Click the Power On button.
3. Check color of the home-button in MachineControls.

## Expected Result
home-button in MachineControls filled/black color
Machine is "homed" perfectly.

## Actual Result
home-button in MachineControls filled/yellow color
Maybe the machine has still some pending settings to be reset.
A 2nd home is always issued manually after "enable" to turn the button color into black.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
... no real idea what to add in this visual color choose topic

**Comment by ldpgh** [comment]
![image](https://user-images.githubusercontent.com/13517069/46573296-957a5d00-c993-11e8-809c-0d65f865b23b.png)

**Comment by ldpgh** [comment]
![image](https://user-images.githubusercontent.com/13517069/46573357-3ff28000-c994-11e8-847f-9e33f5608032.png)

**Comment by vonnieda** [comment]
Should be an easy fix. Thanks for reporting it!

**Comment by vonnieda** [comment]
Fixed in https://github.com/openpnp/openpnp/commit/7de60a14686536cf9098d344f357a4f7044b4c2f

**Comment by ldpgh** [comment]
Develop binary (download 2018-10-13) works for me too.
