### ISSUE TITLE
AutoSave delay after each placement

### ISSUE THREAD

**Issue by mgrl** [openpnp/openpnp#801]
# Problem Report
## Describe the Issue
Coming back to my machine I found that the new autosave-feature adds a delay of about 1s on my windows machine after each placement.
![autosave-delay](https://user-images.githubusercontent.com/3868450/50961766-dde07400-14c8-11e9-9beb-d610d89c9400.PNG)

I know it was introduced for having reliable placement-data after a sudden shutdown, but 1s adds much time... I would propose to make it at least configurable in the GUI to disable that feature.
Alternative, can these IO-operations be made faster by threading them off and continue with the processing? 

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
1. Start OpenPnP
2. Run a job
3. see the delay

This is on win 7, 64 bit. Didn't anyone else having that delay until today?

**Comment by vonnieda** [comment]
WRT threading it out, it's not an easy change. See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openpnp/SKcP9xNd2_E/0kLOpvMMBwAJ

**Comment by mgrl** [comment]
okay, will do a patch in the near future to expose that setting

**Comment by mgrl** [comment]
I accidentally found out, that I had my job stored on a network share. Storing it local brings the delay down to about 20ms:
![local-file](https://user-images.githubusercontent.com/3868450/51025830-51e45000-158d-11e9-8f02-9df10dddeea6.PNG)

anyway I made a change and send a pull request #802
