### ISSUE TITLE
OpenCV Camera, id should be Text field

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#81]
As the Title Say, the ID should be text field.
It should be possible to enter -1, or as example http://178.169.93.71//axis-cgi/mjpg/video.cgi

I have trayed to replace ComboBox with TextField, but after starting the program the next time,
it have the value 0, maybe some trigger or validator is active.

Under Windows as example, if using 1400 or 700 instead of 0, normally the fps is higher, if the driver
is supported.  This because 0 uses the 200 driver instead of more advanced ones.

**Comment by FlyingLotus1983** [comment]
Karl created a camera class called org.firepick.FireFuseCamera that used a URL similar to your example above.  Rather than putting the URl in the camera ID, he added as a child element to the camera driver element.  For example:

```xml
            <cameras>
               <camera class="org.firepick.FireFuseCamera" id="C1" looking="Down" fps="1">
                  <units-per-pixel units="Millimeters" x="0.030745" y="0.030813" z="0.0" rotation="0.0"/>
                  <vision-provider class="org.firepick.FireSightVisionProvider"/>
                  <head-offsets units="Millimeters" x="0.0" y="-28.941" z="0.0" rotation="0.0"/>
                  <source-uri>http://10.0.1.4:8080/firerest/sync/cv/1/camera.jpg</source-uri>
               </camera>
            </cameras>
```

This was an older machine.xml so it might not be 100% usable but you get the idea. The `source-uri` holds the URL... Not the camera ID.

**Comment by cri-s** [comment]
Do you sugget to Autoproble from -1 to 2000 and every camera detected is on the DeviceID ?

**Comment by vonnieda** [comment]
This wouldn't work for the primary use case, which is using a local video
capture device. See:
http://docs.opencv.org/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture-open

OpenPnP calls bool VideoCapture::open(int device).

If you need to call bool VideoCapture::open(const string& filename) we
could add a second field called filename.

Jason

**Comment by cri-s** [comment]
It is not less difficult to have one text field and doing something like that:
Integer id ;
String ids[] = index.split(" ");
try { id=Integer.valueOf(ids[0]);} catch(Exception e) { id=null; }
and then
if (id==null) fg.open(Index); else fg.open(id);

Further the textfield can be hook for adding option, like resolution, disable automatic gain, ... 
Default for the text field should be -1

**Comment by vonnieda** [comment]
Sounds fine to me.

**Comment by cri-s** [comment]
clenup
