### ISSUE TITLE
Home Button does not change when homed with script

### ISSUE THREAD

**Issue by cncmachineguy** [openpnp/openpnp#814]
# Read This First
To submit an issue for OpenPnP you must use this template or it will be deleted. Please fill out either the Problem Report or Feature Request section below and delete the other section.

-----------------------------------------------------------------------

# Problem Report
## Describe the Issue
When using machine.home() to home the machine from a script, the home button remains yellow

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
Create a scrip such as:

load(scripting.getScriptsDirectory().toString() + '/Examples/JavaScript/Utility.js');

// Import some OpenPnP classes we'll use
var imports = new JavaImporter(org.openpnp.model, org.openpnp.util);

// Using the imports from above, do some work.
with (imports)
{
    task(function()
    {
        machine.home();
    });
}

Enable machine
Run script

## Expected Result
I expect the machine to home 
I expect the yellow home button to turn black 

## Actual Result
Machine homes as expected
Home button remains yellow

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
The machine is actually homed and will perform as expected, just the home button remains yellow. This seems like it may also be related to issue #781 

Whenever possible, please use the Menu -> Help -> Submit Diagnostics feature and include the URL here. Submit Diagnostics makes it easy to include log files, screen capture, debug images, configuration files, etc.

-----------------------------------------------------------------------

# Feature Request
## Describe the Feature
What do you want it to do? Be as descriptive as possible.

## How Will It Look?
If the feature will include changes to the user interface, how would they look? Include drawings or mockups if possible.

## Why Do We Need It?
1. What problem does it solve?
2. Is it useful for everyone, or does it only solve a problem for your machine?

## Provide Examples
Is this something that exists in other pick and place software? Provide examples and references if possible.

**Comment by vonnieda** [comment]
Will be converted to a bindable property "homed" on ReferenceMachine and have the button monitor the property.
