### ISSUE TITLE
Panel Board Placements Status Incorrect

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#823]
User reported that placement status is being shared across all boards in a panel, rather than being separate. 

> Hi guys
> I've noticed weird panelization bug today.
> I've panelized a board in two rows by 3 boards all together 6 boards. After starting a job openpnp marks all parts already placed on one board as placed on all boards. It actually places them on all boards but marks them as placed on all boards as soon as the part is placed on one. That's not a problem by itself but when the machine stops for error or you stop a job for whatever reason there is no way you can tell which parts are placed on all boards and which are not. Removing placed mark on one board immediately removes that mark on all boards.
> 
> Is this normal behavior or is this a bug? This way panelization does not make sense.
> I've even tried to input 6 separate boards from 6 separate boards files but this behavior ocuured again and marked all Ma parts placed on all boards when in fact they were placed only on one.
> 
> Any ideas.
> 
> TDarlic

See https://groups.google.com/d/msgid/openpnp/7ee97feb-c477-4995-b2da-d0d957515717%40googlegroups.com

**Comment by CircuitSetup** [comment]
I noticed this as well

**Comment by damancusonqn** [comment]
Same here, running in Ubuntu, my panel is 7x5 boards. It happens after a "No component detected after a pick" error or when the ReferenceStripFeeder reaches the end of the strip. Most often all components are wrongly marked as placed (in the actual board and the rest of the panel).

**Comment by MatSpy** [comment]
Hello. 

Is there any progress in this topic?
Penalization is very useful thing. And with this bug it is way harder to use. 

Regards,
Mateusz

**Comment by cyberwaelder1** [comment]
hi, I have the same problem. When one part is not picked, I have to remove all from the other boards to continue the step again.

**Comment by ma-lalonde** [comment]
Same.

**Comment by tonyluken** [comment]
@vonnieda,

Can we close this issue as I believe it was address by [PR1507](https://github.com/openpnp/openpnp/pull/1578)?

**Comment by vonnieda** [comment]
Wonderful, thank you @tonyluken!
