### ISSUE TITLE
Current jog position not set to machine position after homing

### ISSUE THREAD

**Issue by JulienDevillers** [openpnp/openpnp#830]
## Describe the Issue
After homing, the current jogged position is assumed to be (0,0,0) while machine may not be at this position after homing (for example, with smoothie, you may set alpha_homing_retract_mm to 5 mm to avoid triggering limit).
Then, if you jog click jog to the right 0.1mm, openPnp ask the controler to go to (0.1, 0, 0) which is actually in the left direction starting from real current position which is (5, 0, 0). 
Moreover, depeding on the accuracy of your zero switches, you may hit the xmin switch while jogging to the right 

 ## Steps to Reproduce
see above.

## What to do?
After homing, openPnp should call M114 to get controler's current position to initialize its internal jog position.

**Comment by vonnieda** [comment]
You can send an M114 at the end of your HOME_COMMAND, and configure POSITION_REPORT_REGEX to respond to it: https://github.com/openpnp/openpnp/wiki/GcodeDriver#position_report_regex

Or you can set your home coordinates in your axis config. See home-coordinate examples in https://github.com/openpnp/openpnp/wiki/GcodeDriver:-Axis-Mapping

You can also use G92 to tell Smoothie that it's at 0,0,0,0 after homing.
