### ISSUE TITLE
Stopping Job could tend to remove Start/Pause/Stop Button

### ISSUE THREAD

**Issue by bergyla** [openpnp/openpnp#837]
I faced some situations of Job run errors and Pausing where there is no way to restart the Job, while Start/Pause/Stop is grayed out.
In some of that situations openpnp will still tell to stop the Job, but Stop is still grayed out.

I will try to make a reproducible step by step report...

**Comment by vonnieda** [comment]
This should be fixed now in https://github.com/openpnp/openpnp/commit/97e5bfc54827965a24eb710fa0932c3cf46ce29f. Please try that and see if you are still able to reproduce.
