### ISSUE TITLE
Windows openpnp.bat some times fails to initiate the correct dll

### ISSUE THREAD

**Issue by la3pna** [openpnp/openpnp#84]
The openpnp.bat file some times fails to initate the correct dll with the current use of 
This issue should only be a problem on Intel based machines. 
The %PROCESSOR_ARCHITECTURE% returns AMD64 on all 64 bit systems. Suggest to move to using %PROCESSOR_IDENTIFIER% instead. 
For AMD64 this returns: 
AMD64 Family 22 Model 48 Stepping 1, AuthenicAMD
For Intel64 this returns:
Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

The complete batch file would then be: 

@echo off
set _test=%PROCESSOR_IDENTIFIER%
set archi=%_test:~0,3%

if not x%archi:X86=%==x%archi% java -Djava.library.path=lib\native\windows\x86 -jar target\openpnp-gui-0.0.1-alpha-SNAPSHOT.jar
if not x%archi:Int=%==x%archi% java -Djava.library.path=lib\native\windows\x86 -jar target\openpnp-gui-0.0.1-alpha-SNAPSHOT.jar
if not x%archi:AMD=%==x%archi% java -Djava.library.path=lib\native\windows\x64 -jar target\openpnp-gui-0.0.1-alpha-SNAPSHOT.jar

**Comment by la3pna** [comment]
This gives the 64 bit on my win7 64, but this machine (Intel i5 64 bit) needs the 32 bit driver to work.
Not sure if this is a isolated problem or if its related to Intel?

**Comment by vonnieda** [comment]
Oh, that's interesting. Are you running 32 bit Windows on a 64 bit
processor, by chance? Can you look in your system properties and check?

Thanks,
Jason


On Sat, Feb 21, 2015 at 9:16 PM, Thomas S. Knutsen <notifications@github.com

**Comment by la3pna** [comment]
Just had to look, and I'm running 64 bit Win 7.

**Comment by vonnieda** [comment]
Ah ha! So you must be running a 32 bit JVM?


On Sat, Feb 21, 2015 at 9:47 PM, Thomas S. Knutsen <notifications@github.com

**Comment by vonnieda** [comment]
Following up from IRC conversation, was indeed 32 bit JVM and switching to a 64 bit VM fixed it.
