### ISSUE TITLE
FR : OK / cancel button on pipeline window

### ISSUE THREAD

**Issue by JulienDevillers** [openpnp/openpnp#844]
# Feature Request
## Describe the Feature
Set the pipeline editor window modal and add ok/cancel button.

## Why Do We Need It?
A user edits a pipeline.
He does some changes.
Changes are a bad idea, he wants to get back to initial pipeline.
He can't do it.

It's a "standard" behaviour in softwares.

I can't see any reason to show several pipelines editrors at the same time. Does anybody has some?
And you can open several editors on the same pipeline. Can be confusing.

**Comment by vonnieda** [comment]
Agreed on all points - sounds like a good improvement.

**Comment by markmaker** [comment]
Seems to be modal for some time. Confirmation dialog was added by @tonyluken in #1098.
