### ISSUE TITLE
linuxcnc connection problem

### ISSUE THREAD

**Issue by mylucille** [openpnp/openpnp#846]
Hi, after I update to the new stable version from version 2018, I get this following error:

![photo_2019-05-17_23-03-52](https://user-images.githubusercontent.com/43699071/57948885-16211480-78f8-11e9-9867-f747b25a478e.jpg)

linuxcnc version: 2.7.0

Best Regards.

**Comment by vonnieda** [comment]
Hi @mylucille, it looks like LinuxCNC dropped the connection after the "set mdi G21" command. Can you check your LinuxCNC logs and see if they show the dropped connection?

**Comment by mylucille** [comment]
LinuxCNCrsh logs:

```
connected to x
linuxcncrsh: eof from client
linuxcncrsh: disconnecting client x (1.1)
```
Seems to be Openpnp bug, cause it was working fine before the update.

**Comment by vonnieda** [comment]
Please post your question to the discussion group: http://groups.google.com/group/openpnp

Perhaps someone else has seen this issue there.
