### ISSUE TITLE
GcodeDriver: How to set  POSITION_REPORT_REGEX with smoothieware

### ISSUE THREAD

**Issue by cxandy** [openpnp/openpnp#853]
How to set  POSITION_REPORT_REGEX with smoothieware. thanks
this can't working.
<Idle,MPos:(?<x>-?\d+\.\d+),(?<y>-?\d+\.\d+),(?<z>-?\d+\.\d+),(?<rotation>-?\d+\.\d+)>

**Comment by vonnieda** [comment]
Hi @cxandy, please post questions to the discussion group at https://groups.google.com/forum/#!forum/openpnp. The issues area is just for development concerns.
