### ISSUE TITLE
Configuration Load Error on first ever run, deleting config directory wouldn't help

### ISSUE THREAD

**Issue by tobiasvogel** [openpnp/openpnp#862]
# Problem Report
## OpenPnP throws "Configuration Load Error" on very first run!
Just installed the latest Stable .deb-package (2019.06.01.21.53.14.3891a53).
Tried to run for the first time ever, got a "Configuration Load Error".
("Error while reading machine.xml (null)")
Deleting the ".openpnp"-directory didn't help either.

The relevant lines from the log are
`2019-06-26 20:31:31.787 Configuration INFO: No packages.xml found in configuration directory, loading defaults.`
`2019-06-26 20:31:31.883 Configuration INFO: No parts.xml found in configuration directory, loading defaults.`
`2019-06-26 20:31:31.892 Configuration INFO: No machine.xml found in configuration directory, loading defaults.`
`2019-06-26 20:31:32.265 SystemLogger ERROR: java.lang.Exception: Error while reading machine.xml (null)`
`2019-06-26 20:31:32.266 SystemLogger ERROR: 	at org.openpnp.model.Configuration.load(Configuration.java:287)`
`2019-06-26 20:31:32.266 SystemLogger ERROR: 	at org.openpnp.gui.MainFrame.<init>(MainFrame.java:627)` 

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
1. Use a fresh installation of Lubuntu 19.04
2. Install OpenPnP stable from .deb package.
3. Run OpenPnP

## Expected Result
Expected OpenPnP to start up for the first time.

## Actual Result
It didn't start.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
See log attached.
[OpenPnP.log](https://github.com/openpnp/openpnp/files/3331504/OpenPnP.log)

**Comment by vonnieda** [comment]
Looks like this issue: https://github.com/openpnp/opencv/issues/44

Try downgrading Java to JDK 10 or 11.
