### ISSUE TITLE
Unsafe move during nozel calibration

### ISSUE THREAD

**Issue by c-riegel** [openpnp/openpnp#865]
Machine moves in x and y with nozzle fully extended during nozzle calibration move to camera

## Steps to Reproduce
1. Start OpenPnP
2. Click the Power On button.
3. Home machine
4. Open "Machine Setup" > ReferenceMachine > Nozzle Tips
5. Create nozzle tips "500" through "508"
6. Set all nozzles to "Compatible" for N1 and N2
7. Set "Loaded" on N1 for "501"
8. Set "Loaded" on N2 for "502"
9. Jog combobox is set to "Nozzle: N1 - 501 (Head: H1)"
10. Navigate: ReferenceMachine > Nozzle Tips > ReferenceNozzleTip 501 > Calibration
11. Status says "501 on N1: Uncalibrated"
12. Click button to move nozzle to bottom camera.
13. Nozzle 2 fully extends in Z, X&Y move so nozzle 1 is over camera, nozzle 2 retracts.

## Expected Result
Nozzle 2 to not move in Z.  Nozzle 2 to not stay extended during an xy movement.

## Actual Result
Nozzle 2 extended and broke my "502" tip :-(

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
Version 2019-06-29_05-35-04.13e9a0f
[bug_video.zip](https://github.com/openpnp/openpnp/files/3342087/bug_video.zip)
![screenshot](https://user-images.githubusercontent.com/52354621/60386831-757e5280-9a68-11e9-853b-62408141c3d0.png)

**Comment by markmaker** [comment]
Hi @c-riegel 

Sorry to hear you broke your tip. It looks as if your safe Z is not working right. The code uses the standard `moveToLocationAtSafeZ()` here:

https://github.com/openpnp/openpnp/blob/2a65e861f004c63477ce3fbf2b25e5132153f6ca/src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java#L507-L508

Note that this code will move **all** the "head mountables" i.e. all nozzles **and** the camera on the head to safe Z, not just the nozzle you are calibrating. So you need to setup all your nozzles for proper safe Z. Also you need to make sure your camera has the Z axis **not** mapped.

So:

1. Check your Safe Z setting on nozzle 2.
2. Make sure to follow this troubleshooting guide:
https://github.com/openpnp/openpnp/wiki/GcodeDriver#nozzle-is-moving-or-turning-when-camera-is-moved

_Mark
