### ISSUE TITLE
DRO is calculated wrong for selected "device".

### ISSUE THREAD

**Issue by wiegleyj** [openpnp/openpnp#873]
# Read This First
To submit an issue for OpenPnP you must use this template or it will be deleted. Please fill out either the Problem Report or Feature Request section below and delete the other section.

-----------------------------------------------------------------------

# Problem Report
## Describe the Issue
The Digital readout shows the wrong Z value when moving with head camera selected (assuming offsets are used for camera.

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
1. Start OpenPnP
2. Set all offsets to (0,0,0). (This should cause DRO to display raw machine/world coordinates.
3. Select the Camera: Head Camera from the pendant/move panel.
4. home the machine.
5. Select the "Nozzle: Head" in the pendant/move panel (because you can't move Z with a camera selected (This is also an issue.)
6. Move the camera so that the camera focuses on any selected point you consider (0,0,0) [such as the corner of the bed].
7. Record the negative values of the current DRO display as the camera offsets in the camera position. (For me, that is (-0.7, -8, -16).
8. Click Apply.
9: Select the "Camera: Head" from the pendant/move panel.
8. DRO now reads: (0, 0, -16). But It should read (0,0,0)

## Expected Result
I expect the DRO to read (0,0,0) (The result of the (Wx, Wy, Wz) + (CAMx, CAMy, CAMz) [world position + camera offset]

## Actual Result
DRO is reading (0,0,-16) (the result of (Wx, Wy, 0.0) + (CAMx, CAMy, CAMz) [a faulty Z value is used.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
Don't think this needs screen shots. Camera is looking at and focused on point (0,0,0) but DRO reads (0,0,CameraZOffset) and not (0,0,0)

NOTE: THIS MAY BE AN ASPECT OF A MORE DIFFICULT UNDERLYING ARCHITECTURE PROBLEM. I also have incorrect issues with the way the Offset Wizard for nozzle offsets calculates its Z offset value as. Calculation of Z in general seems to be problematic or confusing in several areas.

**Comment by markmaker** [comment]
I believe the issue in the main descriptions is a misunderstanding. The DRO is showing world coordinates of the selected tool. If the camera has a Z head offset, it will effectively give the constant Z coordinate of the camera. Therefore, the DRO is correct. 

After #1035 you can use a virtual Z axis on the camera and things become much more intuitive, because it behaves the same as a nozzle and coordinates captured after switching back and forth between camera and tool will not be lost. This was further improved in #1106 with ...

> * Auto-select tool in Machine Controls based on user action.
> * Automatically reset Virtual Z when moving out of a 5mm radius to prevent unexpected movement.

The issue described in the last paragraph ... 

> I also have incorrect issues with the way the Offset Wizard for nozzle offsets calculates its Z offset value as.

... was solved by #947.
