### ISSUE TITLE
I don't find config menu v2

### ISSUE THREAD

**Issue by bacrua** [openpnp/openpnp#880]
![OPnP_v1 vs v2](https://user-images.githubusercontent.com/48532007/62821718-07a66a00-bb82-11e9-8742-0c7ee66b340b.jpg)

How Set package for nozzle tip in V2.

**Comment by vonnieda** [comment]
It's on the Packages tab now.

**Comment by bacrua** [comment]
Wow! I see it!!!!
Thanks for your work.
