### ISSUE TITLE
Row index out of range error

### ISSUE THREAD

**Issue by gxurma** [openpnp/openpnp#909]
# Row index out of range error
## Describe the Issue
Stepping through the placements list of a board, when stepping from the last placement, it ends in "Error: Row index out of range" 

## Steps to Reproduce
clean install
load the pnp-test job.
click on any board
click on any placement
step through the placements with the icon "Position the camera at the next placements location"
step over the end of the list. You'll get the error

## Expected Result
It should just wrap to the first placement. Like it was in the v1 openpnp.

## Actual Result
throws an error
"Error: Row index out of range"

**Comment by K2AAE** [comment]
Just got Row index out of range error on 2019-12-5 (then long number I can't copy) same conditions gxurma
