### ISSUE TITLE
please help:the nano system cannot be accessed.

### ISSUE THREAD

**Issue by kiwifruit-guo** [openpnp/openpnp#927]
The nano board says that the power is on, the light is on, but the display is not responding, and the nano system cannot be accessed. The wireless network card can be connected to wifi. Whether it is a circular hole or a usb power supply, the nano system cannot be accessed. thanks for your help.

**Comment by vonnieda** [comment]
Hi @kiwifruit-guo - I'm sorry, but I do not understand what you are asking here. Are you having trouble with OpenPnP?

**Comment by kiwifruit-guo** [comment]
Hi，thanks for your reply! I have solved the problem yesterday 😂, it seems like the screen had something wrong.....&nbsp; Thanks so much !🤓😋



---Original---
