### ISSUE TITLE
Panelization: Miscalculated Placements

### ISSUE THREAD

**Issue by tyllurius** [openpnp/openpnp#949]
# Problem Report
## Describe the Issue
The X position of parts from some panelized boards for the job are calculated wrongly. For the GUI the positions are calculated correctly (means for example the camera moves to all parts of all panelized boards correctly).

See [thread](https://groups.google.com/forum/?pli=1#!topic/openpnp/Bss8ciLELgE) for discussion.

## Steps to Reproduce
1. Take a board, bottom side
2. Panelize it
4. Start the Job
5. The parts of the first board are misplaced (see picture), part of the other boards are placed correctly.

## Expected Result
Part position with correctly applied x and y offset per board.

## Actual Result
X position of some boards is wrong.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
![autpanelize_misplacement](https://user-images.githubusercontent.com/40373092/73700143-047dd800-46e6-11ea-8564-b1631148675c.png)

**Comment by tyllurius** [comment]
@tonyluken 
I will test next week and report back. Thanks for addressing this issue!

**Comment by tonyluken** [comment]
@tyllurius,

Any chance to test this?

**Comment by tonyluken** [comment]
Since I haven't heard anything to the contrary, I'm going to close this issue. You can always reopen it or start a new one if you are still having problems.
