### ISSUE TITLE
OpenBuilds Driver Miscalculating Position

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#95]
The OpenBuilds driver is failing to consider offsets for the Z axis in some cases. This causes certain moves to the exact offset value to be ignored. For instance, if the offset is -11.5 and the move to is to -11.5, the move is ignored because the driver thinks it's already there.

**Comment by vonnieda** [comment]
Code comment that triggered this issue:

        // TODO: Somewhere in this code the offsets are not being applied. When
        // we try to move Z to -11.5 (exactly) and we're at 0 nothing happens
        // because this check fails. Probably need ot make sure we're considering
        // offsets, maybe by using getLocation() instead of using the coordinates
        // directly.

**Comment by cri-s** [comment]
This is because of Z height and Cam angle are compared, and if both have same value, as it is the case
of  -11.5, then no movement is made.
 if (!Double.isNaN(z) && z != this.z) { // z is in mm
.. calc ..
        this.z = a;  // z is in degree
}
