### ISSUE TITLE
OpenPnP on Raspberry Pi 4

### ISSUE THREAD

**Issue by dronecz** [openpnp/openpnp#950]
# Problem Report
## Describe the Issue
I was able to setup OpenPnP on RPi 4 with 4 GB RAM. I´m following setup steps from wiki and i can not setup any camera. I know that ARM platform is not supported, but I was hopping that somebody will at least point me some solution. 

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
1. Start OpenPnP
2. Add any camera 
3. Unable to set some settings 

## Expected Result
I was hopping to setup a camera. 

## Actual Result
Camera settings will not show.I can not add some types of cameras. 

https://pastebin.com/7uSi3zUq

**Comment by vonnieda** [comment]
You can try the OpenCvCamera or WebcamCaptureCamera. The
OpenPnpCaptureCamera has not been ported to ARM.

Jason

**Comment by dronecz** [comment]
> You can try the OpenCvCamera or WebcamCaptureCamera. 

I tried to add OpenCVCamera and I can use RPI camera module at slot 0 and USB camera at slot 1 😍. I should test it more before I posted a question, but I hope it will help somebody in future. Many thanks for prompt reply.

**Comment by G-Pereira** [comment]
Hi @dronecz I am thinking going this route as well. Can you share your RAM and eMMC size recommendation?

**Comment by dronecz** [comment]
> Hi @dronecz I am thinking going this route as well. Can you share your RAM and eMMC size recommendation?

Hi, I have RPi 4 with 4 GB RAM and I used SD card.. 😉

**Comment by olovskos** [comment]
Will OpenPnpCaptureCamera be ported to ARM? And if so, is there an estimated release plan?

**Comment by olovskos** [comment]
So?

**Comment by markmaker** [comment]
Have you tried?

This says it should now work on the OpenPnP `test` version...

https://github.com/openpnp/openpnp-capture/pull/47#issuecomment-1100576011

... it was integrated after a long delay:

https://github.com/openpnp/openpnp/pull/1544

But I'm only talking about USB cameras. The PI cameras may not work yet:

https://github.com/openpnp/openpnp/issues/1437

_Mark

**Comment by olovskos** [comment]
Thanks for the hint, will try it. Usb camera is all I need :)

**Comment by darkomenz** [comment]
Would love to see the CSI cameras working on the CM4.

https://github.com/openpnp/openpnp-capture/issues/60
